------------------------------------------------------------------
-- DataNucleus SchemaTool (ran at 10/05/2012 20:08:35)
------------------------------------------------------------------
-- Schema diff for jdbc:postgresql://localhost/CoopDataNucleusPlayground and the following classes:-
--     softeng.coop.dataaccess.ActivitySector
--     softeng.coop.dataaccess.Address
--     softeng.coop.dataaccess.Attachment
--     softeng.coop.dataaccess.AuthenticatedUser
--     softeng.coop.dataaccess.Branch
--     softeng.coop.dataaccess.Category
--     softeng.coop.dataaccess.CoOp
--     softeng.coop.dataaccess.Company
--     softeng.coop.dataaccess.CompanyPerson
--     softeng.coop.dataaccess.Department
--     softeng.coop.dataaccess.Division
--     softeng.coop.dataaccess.EMail
--     softeng.coop.dataaccess.EmbeddableAddress
--     softeng.coop.dataaccess.EmbeddableEMail
--     softeng.coop.dataaccess.EmbeddableTelephone
--     softeng.coop.dataaccess.EntityAccess
--     softeng.coop.dataaccess.FacultyUser
--     softeng.coop.dataaccess.FinancialSource
--     softeng.coop.dataaccess.GeoLocation
--     softeng.coop.dataaccess.Group
--     softeng.coop.dataaccess.InsuranceCompany
--     softeng.coop.dataaccess.InsuranceContract
--     softeng.coop.dataaccess.Invitation
--     softeng.coop.dataaccess.Job
--     softeng.coop.dataaccess.JobPart
--     softeng.coop.dataaccess.JobPosting
--     softeng.coop.dataaccess.JobPostingPart
--     softeng.coop.dataaccess.Language
--     softeng.coop.dataaccess.Lesson
--     softeng.coop.dataaccess.Literal
--     softeng.coop.dataaccess.Location
--     softeng.coop.dataaccess.Multilingual
--     softeng.coop.dataaccess.Nationality
--     softeng.coop.dataaccess.Payment
--     softeng.coop.dataaccess.Permission
--     softeng.coop.dataaccess.Person
--     softeng.coop.dataaccess.Professor
--     softeng.coop.dataaccess.Registration
--     softeng.coop.dataaccess.Report
--     softeng.coop.dataaccess.ReportType
--     softeng.coop.dataaccess.Requirement
--     softeng.coop.dataaccess.Role
--     softeng.coop.dataaccess.Student
--     softeng.coop.dataaccess.Telephone
--     softeng.coop.dataaccess.Tracking
--     softeng.coop.dataaccess.University
--
-- Table "COMPANY" for classes [softeng.coop.dataaccess.InsuranceCompany, softeng.coop.dataaccess.Company]
CREATE TABLE "COMPANY"
(
    "ID" int4 NOT NULL,
    "ACTIVITYSECTOR_ID" int4 NULL,
    "CATEGORY_ID" int4 NULL,
    "CENTRALBRANCH_ID" int4 NULL,
    "COMMENTS_ID" int4 NULL,
    "CONTACTPERSON_ID" int4 NULL,
    "EMAIL" varchar(255) NULL,
    "NAME_ID" int4 NULL,
    "OFFERSCOMPENSATION" bool NULL,
    "TAXCODE" varchar(255) NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL,
    "WEBSITE" varchar(255) NULL
);

ALTER TABLE "COMPANY" ADD PRIMARY KEY ("ID");

-- Table "NATIONALITY" for classes [softeng.coop.dataaccess.Nationality]
CREATE TABLE "NATIONALITY"
(
    "ID" int4 NOT NULL,
    "NAME" varchar(255) NULL
);

ALTER TABLE "NATIONALITY" ADD PRIMARY KEY ("ID");

-- Table "PERMISSION" for classes [softeng.coop.dataaccess.Permission]
CREATE TABLE "PERMISSION"
(
    "ID" int4 NOT NULL,
    "COMMENT" varchar(255) NULL,
    "MANAGERNAME" varchar(255) NULL,
    "NAME" varchar(255) NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL
);

ALTER TABLE "PERMISSION" ADD PRIMARY KEY ("ID");

-- Table "ENTITYACCESS" for classes [softeng.coop.dataaccess.EntityAccess]
CREATE TABLE "ENTITYACCESS"
(
    "ID" int4 NOT NULL,
    "ACCESSINGALLDEPARTMENTS" bool NOT NULL,
    "ENTITYNAME" varchar(255) NULL,
    "OWNREADABLE" bool NOT NULL,
    "OWNWRITABLE" bool NOT NULL,
    "PERMISSION_ID" int4 NULL,
    "READABLE" bool NOT NULL,
    "WRITABLE" bool NOT NULL
);

ALTER TABLE "ENTITYACCESS" ADD PRIMARY KEY ("ID");

-- Table "LESSON" for classes [softeng.coop.dataaccess.Lesson]
CREATE TABLE "LESSON"
(
    "ID" int4 NOT NULL,
    "DEPARTMENT_ID" int4 NOT NULL,
    "NAME_ID" int4 NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL
);

ALTER TABLE "LESSON" ADD PRIMARY KEY ("ID");

-- Table "DEPARTMENT" for classes [softeng.coop.dataaccess.Department]
CREATE TABLE "DEPARTMENT"
(
    "ID" int4 NOT NULL,
    "NAME_ID" int4 NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL,
    "UNIVERSITY_ID" int4 NULL
);

ALTER TABLE "DEPARTMENT" ADD PRIMARY KEY ("ID");

-- Table "JOBPOSTINGPART" for classes [softeng.coop.dataaccess.JobPostingPart]
CREATE TABLE "JOBPOSTINGPART"
(
    "ID" int4 NOT NULL,
    "BRANCH_ID" int4 NULL,
    "DESCRIPTION_ID" int4 NULL,
    "DURATIONDAYS" int4 NOT NULL,
    "JOBPOSTING_ID" int4 NOT NULL,
    "MANAGINGCOMPANYPERSON_ID" int4 NULL,
    "STARTDAY" int4 NOT NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL
);

ALTER TABLE "JOBPOSTINGPART" ADD PRIMARY KEY ("ID");

-- Table "JOB" for classes [softeng.coop.dataaccess.Job]
CREATE TABLE "JOB"
(
    "ID" int4 NOT NULL,
    "COMMENTS" varchar(255) NULL,
    "ENDDATE" timestamptz NOT NULL,
    "GROUP_ID" int4 NULL,
    "JOBPOSTING_ID" int4 NOT NULL,
    "MANDAYVALUE" numeric NULL,
    "MANDAYSTOTAL" int4 NOT NULL,
    "STARTDATE" timestamptz NOT NULL,
    "STATE" varchar(255) NULL,
    "SUPERVISINGPROFESSOR_ID" int4 NOT NULL,
    "TOTALPAYMENT" numeric NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL
);

ALTER TABLE "JOB" ADD PRIMARY KEY ("ID");

-- Table "LITERAL" for classes [softeng.coop.dataaccess.Literal]
CREATE TABLE "LITERAL"
(
    "ID" int4 NOT NULL,
    "ISDEFAULT" bool NULL,
    "LANGUAGE_ID" int4 NULL,
    "MULTILINGUAL_ID" int4 NOT NULL,
    "TEXT" varchar(255) NULL
);

ALTER TABLE "LITERAL" ADD PRIMARY KEY ("ID");

-- Table "DIVISION" for classes [softeng.coop.dataaccess.Division]
CREATE TABLE "DIVISION"
(
    "ID" int4 NOT NULL,
    "DEPARTMENT_ID" int4 NOT NULL,
    "NAME" varchar(255) NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL
);

ALTER TABLE "DIVISION" ADD PRIMARY KEY ("ID");

-- Table "STUDENT" for classes [softeng.coop.dataaccess.Student]
CREATE TABLE "STUDENT"
(
    "ID" int4 NOT NULL,
    "ACTIVEREGISTRATION_ID" int4 NULL,
    "ADMISSIONDATE" date NOT NULL,
    "AMA" varchar(255) NULL,
    "HASDIPLOMA" bool NOT NULL,
    "HASSPECIALNEEDS" bool NOT NULL,
    "IBAN" varchar(255) NULL,
    "IDISSUER" varchar(255) NULL,
    "IDNUMBER" varchar(255) NULL,
    "IDTYPE" varchar(255) NULL,
    "INSURANCECONTRACT_ID" int4 NULL,
    "ISFOREIGN" bool NOT NULL,
    "ISSUERLOCATION_ID" int4 NULL,
    "NATIONALITY_ID" int4 NULL,
    "SERIALNUMBER" varchar(255) NULL,
    "SOCIALSECURITYID" varchar(255) NULL,
    "TAXDEPARTMENT" varchar(255) NULL,
    "TAXID" varchar(255) NULL,
    "WORKEXPERIENCE" varchar(255) NULL
);

ALTER TABLE "STUDENT" ADD PRIMARY KEY ("ID");

-- Table "LANGUAGE" for classes [softeng.coop.dataaccess.Language]
CREATE TABLE "LANGUAGE"
(
    "ID" int4 NOT NULL,
    "DEFAULT" bool NOT NULL,
    "LOCALECODE" varchar(255) NULL,
    "NAME" varchar(255) NULL
);

ALTER TABLE "LANGUAGE" ADD PRIMARY KEY ("ID");

-- Table "COMPANYPERSON" for classes [softeng.coop.dataaccess.CompanyPerson]
CREATE TABLE "COMPANYPERSON"
(
    "ID" int4 NOT NULL,
    "COMPANY_ID" int4 NOT NULL,
    "POSITION" varchar(255) NULL,
    "SALUTATION" varchar(255) NULL
);

ALTER TABLE "COMPANYPERSON" ADD PRIMARY KEY ("ID");

-- Table "LOCATION" for classes [softeng.coop.dataaccess.Location]
CREATE TABLE "LOCATION"
(
    "ID" int4 NOT NULL,
    "NAME" varchar(255) NULL,
    "PARENTLOCATION_ID" int4 NULL,
    "PATH" varchar(255) NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL,
    "TYPE" varchar(255) NULL
);

ALTER TABLE "LOCATION" ADD PRIMARY KEY ("ID");

-- Table "PAYMENT" for classes [softeng.coop.dataaccess.Payment]
CREATE TABLE "PAYMENT"
(
    "ID" int4 NOT NULL,
    "AMOUNT" numeric NULL,
    "COMMENT" varchar(255) NULL,
    "ENDDATE" date NOT NULL,
    "PAYMENTDATE" timestamptz NOT NULL,
    "REGISTRATION_ID" int4 NOT NULL,
    "REMOTE" bool NOT NULL,
    "SOURCE_ID" int4 NULL,
    "STARTDATE" date NOT NULL,
    "STATE" varchar(255) NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL,
    "TYPE" varchar(255) NULL
);

ALTER TABLE "PAYMENT" ADD PRIMARY KEY ("ID");

-- Table "REQUIREMENT" for classes [softeng.coop.dataaccess.Requirement]
CREATE TABLE "REQUIREMENT"
(
    "ID" int4 NOT NULL,
    "COOP_ID" int4 NOT NULL,
    "NAME_ID" int4 NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL,
    "TYPE" varchar(255) NULL
);

ALTER TABLE "REQUIREMENT" ADD PRIMARY KEY ("ID");

-- Table "FACULTYUSER" for classes [softeng.coop.dataaccess.FacultyUser]
CREATE TABLE "FACULTYUSER"
(
    "ID" int4 NOT NULL,
    "DIVISION_ID" int4 NULL
);

ALTER TABLE "FACULTYUSER" ADD PRIMARY KEY ("ID");

-- Table "FINANCIALSOURCE" for classes [softeng.coop.dataaccess.FinancialSource]
CREATE TABLE "FINANCIALSOURCE"
(
    "ID" int4 NOT NULL,
    "CODE" varchar(255) NULL,
    "DESCRIPTION" varchar(255) NULL,
    "NAME" varchar(255) NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL
);

ALTER TABLE "FINANCIALSOURCE" ADD PRIMARY KEY ("ID");

-- Table "REPORTTYPE" for classes [softeng.coop.dataaccess.ReportType]
CREATE TABLE "REPORTTYPE"
(
    "ID" int4 NOT NULL,
    "FINAL" bool NULL,
    "CODENAME" varchar(255) NULL,
    "COMMENTS_ID" int4 NULL,
    "FACTORYCLASSNAME" varchar(255) NULL,
    "ISAGGREGATE" bool NULL,
    "NAME_ID" int4 NULL,
    "PERMISSION_ID" int4 NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL
);

ALTER TABLE "REPORTTYPE" ADD PRIMARY KEY ("ID");

-- Table "ADDRESS" for classes [softeng.coop.dataaccess.Address]
CREATE TABLE "ADDRESS"
(
    "ID" int4 NOT NULL,
    "CITY" varchar(255) NULL,
    "COUNTRY" varchar(255) NULL,
    "LATITUDE" float8 NOT NULL,
    "LONGTITUDE" float8 NOT NULL,
    "LOCATION_ID" int4 NULL,
    "NUMBER" varchar(255) NULL,
    "PERSON_ID" int4 NOT NULL,
    "POBOX" varchar(255) NULL,
    "STREET" varchar(255) NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL,
    "TYPE" varchar(255) NULL
);

ALTER TABLE "ADDRESS" ADD PRIMARY KEY ("ID");

-- Table "CATEGORY" for classes [softeng.coop.dataaccess.Category]
CREATE TABLE "CATEGORY"
(
    "ID" int4 NOT NULL,
    "NAME_ID" int4 NULL,
    "PARENTCATEGORY_ID" int4 NULL,
    "PATH" varchar(255) NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL
);

ALTER TABLE "CATEGORY" ADD PRIMARY KEY ("ID");

-- Table "ROLE" for classes [softeng.coop.dataaccess.Role]
CREATE TABLE "ROLE"
(
    "ID" int4 NOT NULL,
    "COMMENT" varchar(255) NULL,
    "NAME" varchar(255) NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL
);

ALTER TABLE "ROLE" ADD PRIMARY KEY ("ID");

-- Table "REGISTRATION" for classes [softeng.coop.dataaccess.Registration]
CREATE TABLE "REGISTRATION"
(
    "ID" int4 NOT NULL,
    "COOP_ID" int4 NOT NULL,
    "GRADE" float8 NOT NULL,
    "GRADEDATE" timestamptz NOT NULL,
    "GROUP_ID" int4 NULL,
    "HOSTSATISFACTIONRATE" int4 NOT NULL,
    "PASSED" bool NOT NULL,
    "PREFERREDEND" date NOT NULL,
    "PREFERREDSTART" date NOT NULL,
    "QUALIFIEDFORASSIGMNENT" bool NOT NULL,
    "QUALIFIEDFORCOMPLETION" bool NOT NULL,
    "REGISTRATIONDATE" timestamptz NOT NULL,
    "STUDENT_ID" int4 NULL,
    "SUBJECTSATISFACTIONRATE" int4 NOT NULL,
    "SUPERVISIONSATISFACTIONRATE" int4 NOT NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL
);

ALTER TABLE "REGISTRATION" ADD PRIMARY KEY ("ID");

-- Table "JOBPOSTING" for classes [softeng.coop.dataaccess.JobPosting]
CREATE TABLE "JOBPOSTING"
(
    "ID" int4 NOT NULL,
    "BENEFITS_ID" int4 NULL,
    "COOP_ID" int4 NULL,
    "COMPANY_ID" int4 NOT NULL,
    "DESCRIPTION_ID" int4 NULL,
    "EXPEDITIONLOCATION_ID" int4 NULL,
    "ISSEATPERGROUP" bool NULL,
    "MANAGINGCOMPANYPERSON_ID" int4 NULL,
    "NAME_ID" int4 NULL,
    "REMAININGSEATS" int4 NOT NULL,
    "REMOTE" bool NOT NULL,
    "SALARY" numeric NULL,
    "SEATSNUMBER" int4 NOT NULL,
    "SUPERVISINGPROFESSOR_ID" int4 NOT NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL
);

ALTER TABLE "JOBPOSTING" ADD PRIMARY KEY ("ID");

-- Table "INVITATION" for classes [softeng.coop.dataaccess.Invitation]
CREATE TABLE "INVITATION"
(
    "ID" int4 NOT NULL,
    "DATE" timestamptz NOT NULL,
    "GROUP_ID" int4 NULL,
    "SENDER_ID" int4 NOT NULL,
    "TEXT_ID" int4 NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL
);

ALTER TABLE "INVITATION" ADD PRIMARY KEY ("ID");

-- Table "ATTACHMENT" for classes [softeng.coop.dataaccess.Attachment]
CREATE TABLE "ATTACHMENT"
(
    "ID" int4 NOT NULL,
    "CONTENT" bytea NULL,
    "CONTENTTYPE" varchar(255) NULL,
    "NAME" varchar(255) NULL,
    "REPORT_ID" int4 NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL
);

ALTER TABLE "ATTACHMENT" ADD PRIMARY KEY ("ID");

-- Table "ACTIVITYSECTOR" for classes [softeng.coop.dataaccess.ActivitySector]
CREATE TABLE "ACTIVITYSECTOR"
(
    "ID" int4 NOT NULL,
    "CODE" varchar(255) NULL,
    "DESCRIPTION" varchar(255) NULL,
    "PARENTACTIVITYSECTOR_ID" int4 NULL
);

ALTER TABLE "ACTIVITYSECTOR" ADD PRIMARY KEY ("ID");

-- Table "JOBPART" for classes [softeng.coop.dataaccess.JobPart]
CREATE TABLE "JOBPART"
(
    "ID" int4 NOT NULL,
    "BRANCH_ID" int4 NULL,
    "COMMENTS" varchar(255) NULL,
    "DESCRIPTION" varchar(255) NULL,
    "ENDDATE" date NOT NULL,
    "JOB_ID" int4 NULL,
    "MANAGINGCOMPANYPERSON_ID" int4 NULL,
    "STARTDATE" date NOT NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL
);

ALTER TABLE "JOBPART" ADD PRIMARY KEY ("ID");

-- Table "COOP" for classes [softeng.coop.dataaccess.CoOp]
CREATE TABLE "COOP"
(
    "ID" int4 NOT NULL,
    "ACADEMICYEAR" int4 NOT NULL,
    "ACTIVE" bool NOT NULL,
    "ENDDATE" date NOT NULL,
    "GRADEPOLICY" varchar(255) NULL,
    "HASGROUPGRADE" bool NOT NULL,
    "INREGISTRATION" bool NOT NULL,
    "INSTITUTIONALDIRECTOR_ID" int4 NOT NULL,
    "ISGROUPCOOP" bool NOT NULL,
    "ISINSIDEUNIVERSITY" bool NOT NULL,
    "JOBDURATIONDAYS" int4 NOT NULL,
    "LESSON_ID" int4 NOT NULL,
    "MANDAYVALUE" numeric NULL,
    "MANAGINGPROFESSOR_ID" int4 NOT NULL,
    "MAXGROUPSIZE" int4 NOT NULL,
    "NAME_ID" int4 NULL,
    "SEMESTER" int4 NOT NULL,
    "SETUP" bool NOT NULL,
    "STARTDATE" date NOT NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL
);

ALTER TABLE "COOP" ADD PRIMARY KEY ("ID");

-- Table "EMAIL" for classes [softeng.coop.dataaccess.EMail]
CREATE TABLE "EMAIL"
(
    "ID" int4 NOT NULL,
    "ADDRESS" varchar(255) NULL,
    "COMMENT" varchar(255) NULL
);

ALTER TABLE "EMAIL" ADD PRIMARY KEY ("ID");

-- Table "MULTILINGUAL" for classes [softeng.coop.dataaccess.Multilingual]
CREATE TABLE "MULTILINGUAL"
(
    "ID" int4 NOT NULL
);

ALTER TABLE "MULTILINGUAL" ADD PRIMARY KEY ("ID");

-- Table "GROUP" for classes [softeng.coop.dataaccess.Group]
CREATE TABLE "GROUP"
(
    "ID" int4 NOT NULL,
    "COOP_ID" int4 NOT NULL,
    "COMMENTS" varchar(255) NULL,
    "ISPENDINGFORMATION" bool NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL
);

ALTER TABLE "GROUP" ADD PRIMARY KEY ("ID");

-- Table "UNIVERSITY" for classes [softeng.coop.dataaccess.University]
CREATE TABLE "UNIVERSITY"
(
    "ID" int4 NOT NULL,
    "CITY" varchar(255) NULL,
    "COUNTRY" varchar(255) NULL,
    "LATITUDE" float8 NOT NULL,
    "LONGTITUDE" float8 NOT NULL,
    "LOCATION_ID" int4 NULL,
    "NUMBER" varchar(255) NULL,
    "POBOX" varchar(255) NULL,
    "STREET" varchar(255) NULL,
    "TYPE" varchar(255) NULL,
    "NAME_ID" int4 NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL
);

ALTER TABLE "UNIVERSITY" ADD PRIMARY KEY ("ID");

-- Table "AUTHENTICATEDUSER" for classes [softeng.coop.dataaccess.AuthenticatedUser]
CREATE TABLE "AUTHENTICATEDUSER"
(
    "ID" int4 NOT NULL,
    "DEFAULTCOOP_ID" int4 NULL,
    "DEPARTMENT_ID" int4 NOT NULL,
    "USERNAME" varchar(255) NULL
);

ALTER TABLE "AUTHENTICATEDUSER" ADD PRIMARY KEY ("ID");

-- Table "REPORT" for classes [softeng.coop.dataaccess.Report]
CREATE TABLE "REPORT"
(
    "ID" int4 NOT NULL,
    "ATTENDED" bool NULL,
    "DATESUBMITTED" timestamptz NOT NULL,
    "GRADE" float8 NOT NULL,
    "GROUP_ID" int4 NULL,
    "JOBPART_ID" int4 NULL,
    "PASSED" bool NULL,
    "REGISTRATION_ID" int4 NULL,
    "REPORTTYPE_ID" int4 NULL,
    "REPORTEDBY_ID" int4 NULL,
    "TITLE" varchar(255) NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL
);

ALTER TABLE "REPORT" ADD PRIMARY KEY ("ID");

-- Table "BRANCH" for classes [softeng.coop.dataaccess.Branch]
CREATE TABLE "BRANCH"
(
    "ID" int4 NOT NULL,
    "CITY" varchar(255) NULL,
    "COUNTRY" varchar(255) NULL,
    "LATITUDE" float8 NOT NULL,
    "LONGTITUDE" float8 NOT NULL,
    "LOCATION_ID" int4 NULL,
    "NUMBER" varchar(255) NULL,
    "POBOX" varchar(255) NULL,
    "STREET" varchar(255) NULL,
    "TYPE" varchar(255) NULL,
    "COMPANY_ID" int4 NOT NULL,
    "FAX" varchar(255) NULL,
    "NAME_ID" int4 NULL,
    "TELEPHONE" varchar(255) NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL
);

ALTER TABLE "BRANCH" ADD PRIMARY KEY ("ID");

-- Table "INSURANCECONTRACT" for classes [softeng.coop.dataaccess.InsuranceContract]
CREATE TABLE "INSURANCECONTRACT"
(
    "ID" int4 NOT NULL,
    "ATTACHMENT" bytea NULL,
    "COOP_ID" int4 NULL,
    "INSURANCECOMPANY_ID" int4 NULL,
    "NAME" varchar(255) NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL
);

ALTER TABLE "INSURANCECONTRACT" ADD PRIMARY KEY ("ID");

-- Table "PROFESSOR" for classes [softeng.coop.dataaccess.Professor]
CREATE TABLE "PROFESSOR"
(
    "ID" int4 NOT NULL,
    "RANK" varchar(255) NULL
);

ALTER TABLE "PROFESSOR" ADD PRIMARY KEY ("ID");

-- Table "PERSON" for classes [softeng.coop.dataaccess.Person]
CREATE TABLE "PERSON"
(
    "ID" int4 NOT NULL,
    "DATEOFBIRTH" date NOT NULL,
    "EMAIL" varchar(255) NULL,
    "FATHERNAME" varchar(255) NULL,
    "GENDER" varchar(255) NULL,
    "MOBILETELEPHONE" varchar(255) NULL,
    "MOTHERNAME" varchar(255) NULL,
    "NAME" varchar(255) NULL,
    "NOTES" varchar(255) NULL,
    "PREFERREDLANGUAGE_ID" int4 NULL,
    "SURNAME" varchar(255) NULL,
    "TELEPHONE" varchar(255) NULL,
    "CREATED" timestamptz NOT NULL,
    "CREATEDBY_ID" int4 NULL,
    "MODIFIED" timestamptz NOT NULL,
    "MODIFIEDBY_ID" int4 NULL
);

ALTER TABLE "PERSON" ADD PRIMARY KEY ("ID");

-- Table "TELEPHONE" for classes [softeng.coop.dataaccess.Telephone]
CREATE TABLE "TELEPHONE"
(
    "ID" int4 NOT NULL,
    "COMMENT" varchar(255) NULL,
    "NUMBER" varchar(255) NULL,
    "TYPE" varchar(255) NULL
);

ALTER TABLE "TELEPHONE" ADD PRIMARY KEY ("ID");

-- Table "REGISTRATION_LOCATION" for join relationship
CREATE TABLE "REGISTRATION_LOCATION"
(
    "PREFERREDBYREGISTRATIONS_ID" int4 NOT NULL,
    "PREFERREDLOCATIONS_ID" int4 NOT NULL
);

-- Table "ROLE_PERMISSION" for join relationship
CREATE TABLE "ROLE_PERMISSION"
(
    "PERMISSIONS_ID" int4 NOT NULL,
    "ROLES_ID" int4 NOT NULL
);

-- Table "BRANCH_COMPANYPERSON" for join relationship
CREATE TABLE "BRANCH_COMPANYPERSON"
(
    "PERSONS_ID" int4 NOT NULL,
    "BRANCHES_ID" int4 NOT NULL
);

-- Table "COOP_PROFESSOR" for join relationship
CREATE TABLE "COOP_PROFESSOR"
(
    "SUPERVISINGPROFESSORS_ID" int4 NOT NULL,
    "SUPERVISEDCOOPS_ID" int4 NOT NULL
);

-- Table "AUTHENTICATEDUSER_ROLE" for join relationship
CREATE TABLE "AUTHENTICATEDUSER_ROLE"
(
    "ROLES_ID" int4 NOT NULL,
    "USERS_ID" int4 NOT NULL
);

-- Table "COOP_FINANCIALSOURCE" for join relationship
CREATE TABLE "COOP_FINANCIALSOURCE"
(
    "FINANCIALSOURCES_ID" int4 NOT NULL,
    "COOPS_ID" int4 NOT NULL
);

-- Table "COOP_COMPANY" for join relationship
CREATE TABLE "COOP_COMPANY"
(
    "COMPANIES_ID" int4 NOT NULL,
    "COOPS_ID" int4 NOT NULL
);

-- Table "INVITATION_REGISTRATION" for join relationship
CREATE TABLE "INVITATION_REGISTRATION"
(
    "RECEPIENTS_ID" int4 NOT NULL,
    "RECEIVEDINVITATIONS_ID" int4 NOT NULL
);

-- Table "PROFESSOR_GROUP" for join relationship
CREATE TABLE "PROFESSOR_GROUP"
(
    "SUPERVISINGPROFESSORS_ID" int4 NOT NULL,
    "SUPERVISEDGROUPS_ID" int4 NOT NULL
);

-- Table "REGISTRATION_REQUIREMENT" for join relationship
CREATE TABLE "REGISTRATION_REQUIREMENT"
(
    "FULLFILLINGREGISTRATIONS_ID" int4 NOT NULL,
    "MEETSREQUIREMENTS_ID" int4 NOT NULL
);

-- Table "REGISTRATION_JOBPOSTING" for join relationship
CREATE TABLE "REGISTRATION_JOBPOSTING"
(
    "PREFERREDJOBPOSTINGS_ID" int4 NOT NULL,
    "PREFERREDBYREGISTRATIONS_ID" int4 NOT NULL
);

-- Table "REGISTRATION_CATEGORY" for join relationship
CREATE TABLE "REGISTRATION_CATEGORY"
(
    "PREFERREDBYREGISTRATIONS_ID" int4 NOT NULL,
    "PREFERREDCATEGORIES_ID" int4 NOT NULL
);

-- Constraints for table "COMPANY" for class(es) [softeng.coop.dataaccess.InsuranceCompany, softeng.coop.dataaccess.Company]
ALTER TABLE "COMPANY" ADD CONSTRAINT "COMPANY_FK1" FOREIGN KEY ("CONTACTPERSON_ID") REFERENCES "COMPANYPERSON" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "COMPANY" ADD CONSTRAINT "COMPANY_FK2" FOREIGN KEY ("CATEGORY_ID") REFERENCES "CATEGORY" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "COMPANY" ADD CONSTRAINT "COMPANY_FK3" FOREIGN KEY ("CENTRALBRANCH_ID") REFERENCES "BRANCH" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "COMPANY" ADD CONSTRAINT "COMPANY_FK4" FOREIGN KEY ("ACTIVITYSECTOR_ID") REFERENCES "ACTIVITYSECTOR" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "COMPANY" ADD CONSTRAINT "COMPANY_FK5" FOREIGN KEY ("COMMENTS_ID") REFERENCES "MULTILINGUAL" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "COMPANY" ADD CONSTRAINT "COMPANY_FK6" FOREIGN KEY ("NAME_ID") REFERENCES "MULTILINGUAL" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "COMPANY_N49" ON "COMPANY" ("ACTIVITYSECTOR_ID");

CREATE INDEX "COMPANY_N50" ON "COMPANY" ("CONTACTPERSON_ID");

CREATE INDEX "COMPANY_N51" ON "COMPANY" ("COMMENTS_ID");

CREATE INDEX "COMPANY_N52" ON "COMPANY" ("NAME_ID");

CREATE INDEX "COMPANY_N53" ON "COMPANY" ("CENTRALBRANCH_ID");

CREATE INDEX "COMPANY_N54" ON "COMPANY" ("CATEGORY_ID");


-- Constraints for table "NATIONALITY" for class(es) [softeng.coop.dataaccess.Nationality]

-- Constraints for table "PERMISSION" for class(es) [softeng.coop.dataaccess.Permission]

-- Constraints for table "ENTITYACCESS" for class(es) [softeng.coop.dataaccess.EntityAccess]
ALTER TABLE "ENTITYACCESS" ADD CONSTRAINT "ENTITYACCESS_FK1" FOREIGN KEY ("PERMISSION_ID") REFERENCES "PERMISSION" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "ENTITYACCESS_N49" ON "ENTITYACCESS" ("PERMISSION_ID");


-- Constraints for table "LESSON" for class(es) [softeng.coop.dataaccess.Lesson]
ALTER TABLE "LESSON" ADD CONSTRAINT "LESSON_FK1" FOREIGN KEY ("DEPARTMENT_ID") REFERENCES "DEPARTMENT" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "LESSON" ADD CONSTRAINT "LESSON_FK2" FOREIGN KEY ("NAME_ID") REFERENCES "MULTILINGUAL" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "LESSON_N50" ON "LESSON" ("DEPARTMENT_ID");

CREATE INDEX "LESSON_N49" ON "LESSON" ("NAME_ID");


-- Constraints for table "DEPARTMENT" for class(es) [softeng.coop.dataaccess.Department]
ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "DEPARTMENT_FK2" FOREIGN KEY ("UNIVERSITY_ID") REFERENCES "UNIVERSITY" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "DEPARTMENT_FK1" FOREIGN KEY ("NAME_ID") REFERENCES "MULTILINGUAL" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "DEPARTMENT_N49" ON "DEPARTMENT" ("NAME_ID");

CREATE INDEX "DEPARTMENT_N50" ON "DEPARTMENT" ("UNIVERSITY_ID");


-- Constraints for table "JOBPOSTINGPART" for class(es) [softeng.coop.dataaccess.JobPostingPart]
ALTER TABLE "JOBPOSTINGPART" ADD CONSTRAINT "JOBPOSTINGPART_FK1" FOREIGN KEY ("MANAGINGCOMPANYPERSON_ID") REFERENCES "COMPANYPERSON" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "JOBPOSTINGPART" ADD CONSTRAINT "JOBPOSTINGPART_FK2" FOREIGN KEY ("JOBPOSTING_ID") REFERENCES "JOBPOSTING" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "JOBPOSTINGPART" ADD CONSTRAINT "JOBPOSTINGPART_FK3" FOREIGN KEY ("DESCRIPTION_ID") REFERENCES "MULTILINGUAL" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "JOBPOSTINGPART" ADD CONSTRAINT "JOBPOSTINGPART_FK4" FOREIGN KEY ("BRANCH_ID") REFERENCES "BRANCH" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "JOBPOSTINGPART_N50" ON "JOBPOSTINGPART" ("DESCRIPTION_ID");

CREATE INDEX "JOBPOSTINGPART_N51" ON "JOBPOSTINGPART" ("MANAGINGCOMPANYPERSON_ID");

CREATE INDEX "JOBPOSTINGPART_N52" ON "JOBPOSTINGPART" ("BRANCH_ID");

CREATE INDEX "JOBPOSTINGPART_N49" ON "JOBPOSTINGPART" ("JOBPOSTING_ID");


-- Constraints for table "JOB" for class(es) [softeng.coop.dataaccess.Job]
ALTER TABLE "JOB" ADD CONSTRAINT "JOB_FK1" FOREIGN KEY ("SUPERVISINGPROFESSOR_ID") REFERENCES "PROFESSOR" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "JOB" ADD CONSTRAINT "JOB_FK2" FOREIGN KEY ("JOBPOSTING_ID") REFERENCES "JOBPOSTING" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "JOB" ADD CONSTRAINT "JOB_FK3" FOREIGN KEY ("GROUP_ID") REFERENCES "GROUP" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "JOB_N49" ON "JOB" ("JOBPOSTING_ID");

CREATE INDEX "JOB_N50" ON "JOB" ("GROUP_ID");

CREATE INDEX "JOB_N51" ON "JOB" ("SUPERVISINGPROFESSOR_ID");


-- Constraints for table "LITERAL" for class(es) [softeng.coop.dataaccess.Literal]
ALTER TABLE "LITERAL" ADD CONSTRAINT "LITERAL_FK1" FOREIGN KEY ("LANGUAGE_ID") REFERENCES "LANGUAGE" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "LITERAL" ADD CONSTRAINT "LITERAL_FK2" FOREIGN KEY ("MULTILINGUAL_ID") REFERENCES "MULTILINGUAL" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "LITERAL_N49" ON "LITERAL" ("LANGUAGE_ID");

CREATE INDEX "LITERAL_N50" ON "LITERAL" ("MULTILINGUAL_ID");


-- Constraints for table "DIVISION" for class(es) [softeng.coop.dataaccess.Division]
ALTER TABLE "DIVISION" ADD CONSTRAINT "DIVISION_FK1" FOREIGN KEY ("DEPARTMENT_ID") REFERENCES "DEPARTMENT" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "DIVISION_N49" ON "DIVISION" ("DEPARTMENT_ID");


-- Constraints for table "STUDENT" for class(es) [softeng.coop.dataaccess.Student]
ALTER TABLE "STUDENT" ADD CONSTRAINT "STUDENT_FK1" FOREIGN KEY ("ID") REFERENCES "AUTHENTICATEDUSER" ("ID") ;

ALTER TABLE "STUDENT" ADD CONSTRAINT "STUDENT_FK2" FOREIGN KEY ("ISSUERLOCATION_ID") REFERENCES "LOCATION" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "STUDENT" ADD CONSTRAINT "STUDENT_FK3" FOREIGN KEY ("ACTIVEREGISTRATION_ID") REFERENCES "REGISTRATION" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "STUDENT" ADD CONSTRAINT "STUDENT_FK4" FOREIGN KEY ("INSURANCECONTRACT_ID") REFERENCES "INSURANCECONTRACT" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "STUDENT" ADD CONSTRAINT "STUDENT_FK5" FOREIGN KEY ("NATIONALITY_ID") REFERENCES "NATIONALITY" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "STUDENT_N50" ON "STUDENT" ("NATIONALITY_ID");

CREATE INDEX "STUDENT_N51" ON "STUDENT" ("INSURANCECONTRACT_ID");

CREATE INDEX "STUDENT_N52" ON "STUDENT" ("ACTIVEREGISTRATION_ID");

CREATE INDEX "STUDENT_N49" ON "STUDENT" ("ISSUERLOCATION_ID");


-- Constraints for table "LANGUAGE" for class(es) [softeng.coop.dataaccess.Language]

-- Constraints for table "COMPANYPERSON" for class(es) [softeng.coop.dataaccess.CompanyPerson]
ALTER TABLE "COMPANYPERSON" ADD CONSTRAINT "COMPANYPERSON_FK2" FOREIGN KEY ("COMPANY_ID") REFERENCES "COMPANY" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "COMPANYPERSON" ADD CONSTRAINT "COMPANYPERSON_FK1" FOREIGN KEY ("ID") REFERENCES "PERSON" ("ID") ;

CREATE INDEX "COMPANYPERSON_N49" ON "COMPANYPERSON" ("COMPANY_ID");


-- Constraints for table "LOCATION" for class(es) [softeng.coop.dataaccess.Location]
ALTER TABLE "LOCATION" ADD CONSTRAINT "LOCATION_FK1" FOREIGN KEY ("PARENTLOCATION_ID") REFERENCES "LOCATION" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "LOCATION_N49" ON "LOCATION" ("PARENTLOCATION_ID");


-- Constraints for table "PAYMENT" for class(es) [softeng.coop.dataaccess.Payment]
ALTER TABLE "PAYMENT" ADD CONSTRAINT "PAYMENT_FK1" FOREIGN KEY ("REGISTRATION_ID") REFERENCES "REGISTRATION" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "PAYMENT" ADD CONSTRAINT "PAYMENT_FK2" FOREIGN KEY ("SOURCE_ID") REFERENCES "FINANCIALSOURCE" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "PAYMENT_N50" ON "PAYMENT" ("REGISTRATION_ID");

CREATE INDEX "PAYMENT_N49" ON "PAYMENT" ("SOURCE_ID");


-- Constraints for table "REQUIREMENT" for class(es) [softeng.coop.dataaccess.Requirement]
ALTER TABLE "REQUIREMENT" ADD CONSTRAINT "REQUIREMENT_FK1" FOREIGN KEY ("COOP_ID") REFERENCES "COOP" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "REQUIREMENT" ADD CONSTRAINT "REQUIREMENT_FK2" FOREIGN KEY ("NAME_ID") REFERENCES "MULTILINGUAL" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "REQUIREMENT_N49" ON "REQUIREMENT" ("NAME_ID");

CREATE INDEX "REQUIREMENT_N50" ON "REQUIREMENT" ("COOP_ID");


-- Constraints for table "FACULTYUSER" for class(es) [softeng.coop.dataaccess.FacultyUser]
ALTER TABLE "FACULTYUSER" ADD CONSTRAINT "FACULTYUSER_FK1" FOREIGN KEY ("ID") REFERENCES "AUTHENTICATEDUSER" ("ID") ;

ALTER TABLE "FACULTYUSER" ADD CONSTRAINT "FACULTYUSER_FK2" FOREIGN KEY ("DIVISION_ID") REFERENCES "DIVISION" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "FACULTYUSER_N49" ON "FACULTYUSER" ("DIVISION_ID");


-- Constraints for table "FINANCIALSOURCE" for class(es) [softeng.coop.dataaccess.FinancialSource]

-- Constraints for table "REPORTTYPE" for class(es) [softeng.coop.dataaccess.ReportType]
ALTER TABLE "REPORTTYPE" ADD CONSTRAINT "REPORTTYPE_FK1" FOREIGN KEY ("NAME_ID") REFERENCES "MULTILINGUAL" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "REPORTTYPE" ADD CONSTRAINT "REPORTTYPE_FK2" FOREIGN KEY ("COMMENTS_ID") REFERENCES "MULTILINGUAL" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "REPORTTYPE" ADD CONSTRAINT "REPORTTYPE_FK3" FOREIGN KEY ("PERMISSION_ID") REFERENCES "PERMISSION" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "REPORTTYPE_N49" ON "REPORTTYPE" ("COMMENTS_ID");

CREATE INDEX "REPORTTYPE_N50" ON "REPORTTYPE" ("PERMISSION_ID");

CREATE INDEX "REPORTTYPE_N51" ON "REPORTTYPE" ("NAME_ID");


-- Constraints for table "ADDRESS" for class(es) [softeng.coop.dataaccess.Address]
ALTER TABLE "ADDRESS" ADD CONSTRAINT "ADDRESS_FK1" FOREIGN KEY ("LOCATION_ID") REFERENCES "LOCATION" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "ADDRESS" ADD CONSTRAINT "ADDRESS_FK2" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "ADDRESS_N49" ON "ADDRESS" ("PERSON_ID");

CREATE INDEX "ADDRESS_N50" ON "ADDRESS" ("LOCATION_ID");


-- Constraints for table "CATEGORY" for class(es) [softeng.coop.dataaccess.Category]
ALTER TABLE "CATEGORY" ADD CONSTRAINT "CATEGORY_FK1" FOREIGN KEY ("NAME_ID") REFERENCES "MULTILINGUAL" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "CATEGORY" ADD CONSTRAINT "CATEGORY_FK2" FOREIGN KEY ("PARENTCATEGORY_ID") REFERENCES "CATEGORY" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "CATEGORY_N49" ON "CATEGORY" ("PARENTCATEGORY_ID");

CREATE INDEX "CATEGORY_N50" ON "CATEGORY" ("NAME_ID");


-- Constraints for table "ROLE" for class(es) [softeng.coop.dataaccess.Role]

-- Constraints for table "REGISTRATION" for class(es) [softeng.coop.dataaccess.Registration]
ALTER TABLE "REGISTRATION" ADD CONSTRAINT "REGISTRATION_FK1" FOREIGN KEY ("STUDENT_ID") REFERENCES "STUDENT" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "REGISTRATION" ADD CONSTRAINT "REGISTRATION_FK2" FOREIGN KEY ("COOP_ID") REFERENCES "COOP" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "REGISTRATION" ADD CONSTRAINT "REGISTRATION_FK3" FOREIGN KEY ("GROUP_ID") REFERENCES "GROUP" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "REGISTRATION_N50" ON "REGISTRATION" ("COOP_ID");

CREATE INDEX "REGISTRATION_N51" ON "REGISTRATION" ("GROUP_ID");

CREATE INDEX "REGISTRATION_N49" ON "REGISTRATION" ("STUDENT_ID");


-- Constraints for table "JOBPOSTING" for class(es) [softeng.coop.dataaccess.JobPosting]
ALTER TABLE "JOBPOSTING" ADD CONSTRAINT "JOBPOSTING_FK1" FOREIGN KEY ("MANAGINGCOMPANYPERSON_ID") REFERENCES "COMPANYPERSON" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "JOBPOSTING" ADD CONSTRAINT "JOBPOSTING_FK2" FOREIGN KEY ("SUPERVISINGPROFESSOR_ID") REFERENCES "PROFESSOR" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "JOBPOSTING" ADD CONSTRAINT "JOBPOSTING_FK3" FOREIGN KEY ("EXPEDITIONLOCATION_ID") REFERENCES "LOCATION" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "JOBPOSTING" ADD CONSTRAINT "JOBPOSTING_FK4" FOREIGN KEY ("BENEFITS_ID") REFERENCES "MULTILINGUAL" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "JOBPOSTING" ADD CONSTRAINT "JOBPOSTING_FK5" FOREIGN KEY ("COOP_ID") REFERENCES "COOP" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "JOBPOSTING" ADD CONSTRAINT "JOBPOSTING_FK6" FOREIGN KEY ("DESCRIPTION_ID") REFERENCES "MULTILINGUAL" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "JOBPOSTING" ADD CONSTRAINT "JOBPOSTING_FK7" FOREIGN KEY ("NAME_ID") REFERENCES "MULTILINGUAL" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "JOBPOSTING" ADD CONSTRAINT "JOBPOSTING_FK8" FOREIGN KEY ("COMPANY_ID") REFERENCES "COMPANY" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "JOBPOSTING_N51" ON "JOBPOSTING" ("SUPERVISINGPROFESSOR_ID");

CREATE INDEX "JOBPOSTING_N52" ON "JOBPOSTING" ("COMPANY_ID");

CREATE INDEX "JOBPOSTING_N53" ON "JOBPOSTING" ("COOP_ID");

CREATE INDEX "JOBPOSTING_N54" ON "JOBPOSTING" ("DESCRIPTION_ID");

CREATE INDEX "JOBPOSTING_N55" ON "JOBPOSTING" ("BENEFITS_ID");

CREATE INDEX "JOBPOSTING_N56" ON "JOBPOSTING" ("EXPEDITIONLOCATION_ID");

CREATE INDEX "JOBPOSTING_N49" ON "JOBPOSTING" ("MANAGINGCOMPANYPERSON_ID");

CREATE INDEX "JOBPOSTING_N50" ON "JOBPOSTING" ("NAME_ID");


-- Constraints for table "INVITATION" for class(es) [softeng.coop.dataaccess.Invitation]
ALTER TABLE "INVITATION" ADD CONSTRAINT "INVITATION_FK1" FOREIGN KEY ("SENDER_ID") REFERENCES "REGISTRATION" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "INVITATION" ADD CONSTRAINT "INVITATION_FK2" FOREIGN KEY ("GROUP_ID") REFERENCES "GROUP" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "INVITATION" ADD CONSTRAINT "INVITATION_FK3" FOREIGN KEY ("TEXT_ID") REFERENCES "MULTILINGUAL" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "INVITATION_N50" ON "INVITATION" ("TEXT_ID");

CREATE INDEX "INVITATION_N51" ON "INVITATION" ("GROUP_ID");

CREATE INDEX "INVITATION_N49" ON "INVITATION" ("SENDER_ID");


-- Constraints for table "ATTACHMENT" for class(es) [softeng.coop.dataaccess.Attachment]
ALTER TABLE "ATTACHMENT" ADD CONSTRAINT "ATTACHMENT_FK1" FOREIGN KEY ("REPORT_ID") REFERENCES "REPORT" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "ATTACHMENT_N49" ON "ATTACHMENT" ("REPORT_ID");


-- Constraints for table "ACTIVITYSECTOR" for class(es) [softeng.coop.dataaccess.ActivitySector]
ALTER TABLE "ACTIVITYSECTOR" ADD CONSTRAINT "ACTIVITYSECTOR_FK1" FOREIGN KEY ("PARENTACTIVITYSECTOR_ID") REFERENCES "ACTIVITYSECTOR" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "ACTIVITYSECTOR_N49" ON "ACTIVITYSECTOR" ("PARENTACTIVITYSECTOR_ID");


-- Constraints for table "JOBPART" for class(es) [softeng.coop.dataaccess.JobPart]
ALTER TABLE "JOBPART" ADD CONSTRAINT "JOBPART_FK1" FOREIGN KEY ("BRANCH_ID") REFERENCES "BRANCH" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "JOBPART" ADD CONSTRAINT "JOBPART_FK2" FOREIGN KEY ("JOB_ID") REFERENCES "JOB" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "JOBPART" ADD CONSTRAINT "JOBPART_FK3" FOREIGN KEY ("MANAGINGCOMPANYPERSON_ID") REFERENCES "COMPANYPERSON" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "JOBPART_N49" ON "JOBPART" ("MANAGINGCOMPANYPERSON_ID");

CREATE INDEX "JOBPART_N50" ON "JOBPART" ("JOB_ID");

CREATE INDEX "JOBPART_N51" ON "JOBPART" ("BRANCH_ID");


-- Constraints for table "COOP" for class(es) [softeng.coop.dataaccess.CoOp]
ALTER TABLE "COOP" ADD CONSTRAINT "COOP_FK1" FOREIGN KEY ("LESSON_ID") REFERENCES "LESSON" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "COOP" ADD CONSTRAINT "COOP_FK2" FOREIGN KEY ("MANAGINGPROFESSOR_ID") REFERENCES "PROFESSOR" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "COOP" ADD CONSTRAINT "COOP_FK3" FOREIGN KEY ("INSTITUTIONALDIRECTOR_ID") REFERENCES "PROFESSOR" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "COOP" ADD CONSTRAINT "COOP_FK4" FOREIGN KEY ("NAME_ID") REFERENCES "MULTILINGUAL" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "COOP_N49" ON "COOP" ("LESSON_ID");

CREATE INDEX "COOP_N50" ON "COOP" ("INSTITUTIONALDIRECTOR_ID");

CREATE INDEX "COOP_N51" ON "COOP" ("NAME_ID");

CREATE INDEX "COOP_N52" ON "COOP" ("MANAGINGPROFESSOR_ID");


-- Constraints for table "EMAIL" for class(es) [softeng.coop.dataaccess.EMail]

-- Constraints for table "MULTILINGUAL" for class(es) [softeng.coop.dataaccess.Multilingual]

-- Constraints for table "GROUP" for class(es) [softeng.coop.dataaccess.Group]
ALTER TABLE "GROUP" ADD CONSTRAINT "GROUP_FK1" FOREIGN KEY ("COOP_ID") REFERENCES "COOP" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "GROUP_N49" ON "GROUP" ("COOP_ID");


-- Constraints for table "UNIVERSITY" for class(es) [softeng.coop.dataaccess.University]
ALTER TABLE "UNIVERSITY" ADD CONSTRAINT "UNIVERSITY_FK1" FOREIGN KEY ("NAME_ID") REFERENCES "MULTILINGUAL" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "UNIVERSITY_N49" ON "UNIVERSITY" ("NAME_ID");


-- Constraints for table "AUTHENTICATEDUSER" for class(es) [softeng.coop.dataaccess.AuthenticatedUser]
ALTER TABLE "AUTHENTICATEDUSER" ADD CONSTRAINT "AUTHENTICATEDUSER_FK1" FOREIGN KEY ("ID") REFERENCES "PERSON" ("ID") ;

ALTER TABLE "AUTHENTICATEDUSER" ADD CONSTRAINT "AUTHENTICATEDUSER_FK2" FOREIGN KEY ("DEFAULTCOOP_ID") REFERENCES "COOP" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "AUTHENTICATEDUSER" ADD CONSTRAINT "AUTHENTICATEDUSER_FK3" FOREIGN KEY ("DEPARTMENT_ID") REFERENCES "DEPARTMENT" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "AUTHENTICATEDUSER_N50" ON "AUTHENTICATEDUSER" ("DEPARTMENT_ID");

CREATE INDEX "AUTHENTICATEDUSER_N49" ON "AUTHENTICATEDUSER" ("DEFAULTCOOP_ID");


-- Constraints for table "REPORT" for class(es) [softeng.coop.dataaccess.Report]
ALTER TABLE "REPORT" ADD CONSTRAINT "REPORT_FK1" FOREIGN KEY ("REGISTRATION_ID") REFERENCES "REGISTRATION" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "REPORT" ADD CONSTRAINT "REPORT_FK2" FOREIGN KEY ("REPORTEDBY_ID") REFERENCES "AUTHENTICATEDUSER" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "REPORT" ADD CONSTRAINT "REPORT_FK3" FOREIGN KEY ("JOBPART_ID") REFERENCES "JOBPART" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "REPORT" ADD CONSTRAINT "REPORT_FK4" FOREIGN KEY ("REPORTTYPE_ID") REFERENCES "REPORTTYPE" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "REPORT" ADD CONSTRAINT "REPORT_FK5" FOREIGN KEY ("GROUP_ID") REFERENCES "GROUP" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "REPORT_N52" ON "REPORT" ("REGISTRATION_ID");

CREATE INDEX "REPORT_N53" ON "REPORT" ("JOBPART_ID");

CREATE INDEX "REPORT_N49" ON "REPORT" ("GROUP_ID");

CREATE INDEX "REPORT_N50" ON "REPORT" ("REPORTTYPE_ID");

CREATE INDEX "REPORT_N51" ON "REPORT" ("REPORTEDBY_ID");


-- Constraints for table "BRANCH" for class(es) [softeng.coop.dataaccess.Branch]
ALTER TABLE "BRANCH" ADD CONSTRAINT "BRANCH_FK2" FOREIGN KEY ("COMPANY_ID") REFERENCES "COMPANY" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "BRANCH" ADD CONSTRAINT "BRANCH_FK1" FOREIGN KEY ("NAME_ID") REFERENCES "MULTILINGUAL" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "BRANCH_N49" ON "BRANCH" ("COMPANY_ID");

CREATE INDEX "BRANCH_N50" ON "BRANCH" ("NAME_ID");


-- Constraints for table "INSURANCECONTRACT" for class(es) [softeng.coop.dataaccess.InsuranceContract]
ALTER TABLE "INSURANCECONTRACT" ADD CONSTRAINT "INSURANCECONTRACT_FK1" FOREIGN KEY ("COOP_ID") REFERENCES "COOP" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "INSURANCECONTRACT" ADD CONSTRAINT "INSURANCECONTRACT_FK2" FOREIGN KEY ("INSURANCECOMPANY_ID") REFERENCES "COMPANY" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "INSURANCECONTRACT_N49" ON "INSURANCECONTRACT" ("INSURANCECOMPANY_ID");

CREATE INDEX "INSURANCECONTRACT_N50" ON "INSURANCECONTRACT" ("COOP_ID");


-- Constraints for table "PROFESSOR" for class(es) [softeng.coop.dataaccess.Professor]
ALTER TABLE "PROFESSOR" ADD CONSTRAINT "PROFESSOR_FK1" FOREIGN KEY ("ID") REFERENCES "FACULTYUSER" ("ID") ;


-- Constraints for table "PERSON" for class(es) [softeng.coop.dataaccess.Person]
ALTER TABLE "PERSON" ADD CONSTRAINT "PERSON_FK1" FOREIGN KEY ("PREFERREDLANGUAGE_ID") REFERENCES "LANGUAGE" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "PERSON_N49" ON "PERSON" ("PREFERREDLANGUAGE_ID");


-- Constraints for table "TELEPHONE" for class(es) [softeng.coop.dataaccess.Telephone]

-- Constraints for table "REGISTRATION_LOCATION"
ALTER TABLE "REGISTRATION_LOCATION" ADD CONSTRAINT "REGISTRATION_LOCATION_FK1" FOREIGN KEY ("PREFERREDBYREGISTRATIONS_ID") REFERENCES "REGISTRATION" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "REGISTRATION_LOCATION" ADD CONSTRAINT "REGISTRATION_LOCATION_FK2" FOREIGN KEY ("PREFERREDLOCATIONS_ID") REFERENCES "LOCATION" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "REGISTRATION_LOCATION_N50" ON "REGISTRATION_LOCATION" ("PREFERREDBYREGISTRATIONS_ID");

CREATE INDEX "REGISTRATION_LOCATION_N49" ON "REGISTRATION_LOCATION" ("PREFERREDLOCATIONS_ID");


-- Constraints for table "ROLE_PERMISSION"
ALTER TABLE "ROLE_PERMISSION" ADD CONSTRAINT "ROLE_PERMISSION_FK1" FOREIGN KEY ("PERMISSIONS_ID") REFERENCES "PERMISSION" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "ROLE_PERMISSION" ADD CONSTRAINT "ROLE_PERMISSION_FK2" FOREIGN KEY ("ROLES_ID") REFERENCES "ROLE" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "ROLE_PERMISSION_N50" ON "ROLE_PERMISSION" ("PERMISSIONS_ID");

CREATE INDEX "ROLE_PERMISSION_N49" ON "ROLE_PERMISSION" ("ROLES_ID");


-- Constraints for table "BRANCH_COMPANYPERSON"
ALTER TABLE "BRANCH_COMPANYPERSON" ADD CONSTRAINT "BRANCH_COMPANYPERSON_FK1" FOREIGN KEY ("PERSONS_ID") REFERENCES "COMPANYPERSON" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "BRANCH_COMPANYPERSON" ADD CONSTRAINT "BRANCH_COMPANYPERSON_FK2" FOREIGN KEY ("BRANCHES_ID") REFERENCES "BRANCH" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "BRANCH_COMPANYPERSON_N49" ON "BRANCH_COMPANYPERSON" ("BRANCHES_ID");

CREATE INDEX "BRANCH_COMPANYPERSON_N50" ON "BRANCH_COMPANYPERSON" ("PERSONS_ID");


-- Constraints for table "COOP_PROFESSOR"
ALTER TABLE "COOP_PROFESSOR" ADD CONSTRAINT "COOP_PROFESSOR_FK1" FOREIGN KEY ("SUPERVISINGPROFESSORS_ID") REFERENCES "PROFESSOR" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "COOP_PROFESSOR" ADD CONSTRAINT "COOP_PROFESSOR_FK2" FOREIGN KEY ("SUPERVISEDCOOPS_ID") REFERENCES "COOP" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "COOP_PROFESSOR_N49" ON "COOP_PROFESSOR" ("SUPERVISINGPROFESSORS_ID");

CREATE INDEX "COOP_PROFESSOR_N50" ON "COOP_PROFESSOR" ("SUPERVISEDCOOPS_ID");


-- Constraints for table "AUTHENTICATEDUSER_ROLE"
ALTER TABLE "AUTHENTICATEDUSER_ROLE" ADD CONSTRAINT "AUTHENTICATEDUSER_ROLE_FK1" FOREIGN KEY ("ROLES_ID") REFERENCES "ROLE" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "AUTHENTICATEDUSER_ROLE" ADD CONSTRAINT "AUTHENTICATEDUSER_ROLE_FK2" FOREIGN KEY ("USERS_ID") REFERENCES "AUTHENTICATEDUSER" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "AUTHENTICATEDUSER_ROLE_N50" ON "AUTHENTICATEDUSER_ROLE" ("USERS_ID");

CREATE INDEX "AUTHENTICATEDUSER_ROLE_N49" ON "AUTHENTICATEDUSER_ROLE" ("ROLES_ID");


-- Constraints for table "COOP_FINANCIALSOURCE"
ALTER TABLE "COOP_FINANCIALSOURCE" ADD CONSTRAINT "COOP_FINANCIALSOURCE_FK2" FOREIGN KEY ("COOPS_ID") REFERENCES "COOP" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "COOP_FINANCIALSOURCE" ADD CONSTRAINT "COOP_FINANCIALSOURCE_FK1" FOREIGN KEY ("FINANCIALSOURCES_ID") REFERENCES "FINANCIALSOURCE" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "COOP_FINANCIALSOURCE_N49" ON "COOP_FINANCIALSOURCE" ("COOPS_ID");

CREATE INDEX "COOP_FINANCIALSOURCE_N50" ON "COOP_FINANCIALSOURCE" ("FINANCIALSOURCES_ID");


-- Constraints for table "COOP_COMPANY"
ALTER TABLE "COOP_COMPANY" ADD CONSTRAINT "COOP_COMPANY_FK1" FOREIGN KEY ("COMPANIES_ID") REFERENCES "COMPANY" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "COOP_COMPANY" ADD CONSTRAINT "COOP_COMPANY_FK2" FOREIGN KEY ("COOPS_ID") REFERENCES "COOP" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "COOP_COMPANY_N50" ON "COOP_COMPANY" ("COMPANIES_ID");

CREATE INDEX "COOP_COMPANY_N49" ON "COOP_COMPANY" ("COOPS_ID");


-- Constraints for table "INVITATION_REGISTRATION"
ALTER TABLE "INVITATION_REGISTRATION" ADD CONSTRAINT "INVITATION_REGISTRATION_FK1" FOREIGN KEY ("RECEPIENTS_ID") REFERENCES "REGISTRATION" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "INVITATION_REGISTRATION" ADD CONSTRAINT "INVITATION_REGISTRATION_FK2" FOREIGN KEY ("RECEIVEDINVITATIONS_ID") REFERENCES "INVITATION" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "INVITATION_REGISTRATION_N49" ON "INVITATION_REGISTRATION" ("RECEPIENTS_ID");

CREATE INDEX "INVITATION_REGISTRATION_N50" ON "INVITATION_REGISTRATION" ("RECEIVEDINVITATIONS_ID");


-- Constraints for table "PROFESSOR_GROUP"
ALTER TABLE "PROFESSOR_GROUP" ADD CONSTRAINT "PROFESSOR_GROUP_FK1" FOREIGN KEY ("SUPERVISINGPROFESSORS_ID") REFERENCES "PROFESSOR" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "PROFESSOR_GROUP" ADD CONSTRAINT "PROFESSOR_GROUP_FK2" FOREIGN KEY ("SUPERVISEDGROUPS_ID") REFERENCES "GROUP" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "PROFESSOR_GROUP_N49" ON "PROFESSOR_GROUP" ("SUPERVISEDGROUPS_ID");

CREATE INDEX "PROFESSOR_GROUP_N50" ON "PROFESSOR_GROUP" ("SUPERVISINGPROFESSORS_ID");


-- Constraints for table "REGISTRATION_REQUIREMENT"
ALTER TABLE "REGISTRATION_REQUIREMENT" ADD CONSTRAINT "REGISTRATION_REQUIREMENT_FK1" FOREIGN KEY ("FULLFILLINGREGISTRATIONS_ID") REFERENCES "REGISTRATION" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "REGISTRATION_REQUIREMENT" ADD CONSTRAINT "REGISTRATION_REQUIREMENT_FK2" FOREIGN KEY ("MEETSREQUIREMENTS_ID") REFERENCES "REQUIREMENT" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "REGISTRATION_REQUIREMENT_N49" ON "REGISTRATION_REQUIREMENT" ("FULLFILLINGREGISTRATIONS_ID");

CREATE INDEX "REGISTRATION_REQUIREMENT_N50" ON "REGISTRATION_REQUIREMENT" ("MEETSREQUIREMENTS_ID");


-- Constraints for table "REGISTRATION_JOBPOSTING"
ALTER TABLE "REGISTRATION_JOBPOSTING" ADD CONSTRAINT "REGISTRATION_JOBPOSTING_FK1" FOREIGN KEY ("PREFERREDJOBPOSTINGS_ID") REFERENCES "JOBPOSTING" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "REGISTRATION_JOBPOSTING" ADD CONSTRAINT "REGISTRATION_JOBPOSTING_FK2" FOREIGN KEY ("PREFERREDBYREGISTRATIONS_ID") REFERENCES "REGISTRATION" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "REGISTRATION_JOBPOSTING_N50" ON "REGISTRATION_JOBPOSTING" ("PREFERREDBYREGISTRATIONS_ID");

CREATE INDEX "REGISTRATION_JOBPOSTING_N49" ON "REGISTRATION_JOBPOSTING" ("PREFERREDJOBPOSTINGS_ID");


-- Constraints for table "REGISTRATION_CATEGORY"
ALTER TABLE "REGISTRATION_CATEGORY" ADD CONSTRAINT "REGISTRATION_CATEGORY_FK1" FOREIGN KEY ("PREFERREDBYREGISTRATIONS_ID") REFERENCES "REGISTRATION" ("ID") INITIALLY DEFERRED ;

ALTER TABLE "REGISTRATION_CATEGORY" ADD CONSTRAINT "REGISTRATION_CATEGORY_FK2" FOREIGN KEY ("PREFERREDCATEGORIES_ID") REFERENCES "CATEGORY" ("ID") INITIALLY DEFERRED ;

CREATE INDEX "REGISTRATION_CATEGORY_N49" ON "REGISTRATION_CATEGORY" ("PREFERREDBYREGISTRATIONS_ID");

CREATE INDEX "REGISTRATION_CATEGORY_N50" ON "REGISTRATION_CATEGORY" ("PREFERREDCATEGORIES_ID");



------------------------------------------------------------------
-- Sequences and SequenceTables
