package softeng.coop.ui.composites;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import softeng.coop.dataaccess.Benefits;
import softeng.coop.ui.ICoopContext;
import softeng.coop.ui.forms.BenefitsForm;
import softeng.coop.ui.viewdefinitions.IFormView;
import softeng.ui.vaadin.mvp.IView;
import softeng.ui.vaadin.mvp.Presenter;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.util.BeanItem;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Component;
import com.vaadin.ui.Field;
import com.vaadin.ui.FormFieldFactory;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class BenefitsComponent 
extends CoopComponent<BeanItem<Benefits>>
implements IFormView<BeanItem<Benefits>>
{

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private BenefitsForm form;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	
	private CheckBox accommodationOfferedCheckBox = new CheckBox();
	private CheckBox salaryOfferedCheckBox = new CheckBox();
	private CheckBox transportationOfferedCheckBox = new CheckBox();
	private CheckBox insuranceOfferedCheckBox = new CheckBox();
	
	private static List<String> propertyIds = createPropetyIds();

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public BenefitsComponent()
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	private static List<String> createPropetyIds()
	{
		ArrayList<String> list = new ArrayList<String>();
		
		list.add("salaryOffered");
		list.add("accommodationOffered");
		list.add("insuranceOffered");
		list.add("transportationOffered");
		
		return list;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout()
	{
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// form
		form = new BenefitsForm();
		form.setImmediate(false);
		form.setWidth("100.0%");
		form.setHeight("-1px");
		mainLayout.addComponent(form);
		
		return mainLayout;
	}

	@Override
	public boolean isDataValid()
	{
		return form.isValid();
	}

	@Override
	public void discardChanges()
	{
		form.discard();
	}

	@Override
	public void commitChangesToModel()
	{
		form.commit();
	}

	@Override
	protected Presenter<BeanItem<Benefits>, ICoopContext, ? extends IView<BeanItem<Benefits>, ICoopContext>> supplyPresenter()
	{
		return null;
	}

	@Override
	public void dataBind()
	{
		form.setItemDataSource(getModel(), propertyIds);
	}

	@Override
	protected void setupUI()
	{
		super.setupUI();
		
		form.setWriteThrough(false);
		
		form.setFormFieldFactory(new FormFieldFactory()
		{
			
			@Override
			public Field createField(Item item, Object propertyId, Component uiContext)
			{
				if (propertyId.equals("accommodationOffered"))
				{
					accommodationOfferedCheckBox.setCaption(getLocalizedString("ACCOMMODATION_OFFERED_CAPTION"));
					accommodationOfferedCheckBox.setWidth("100%");
					
					return accommodationOfferedCheckBox;
				}
				else if (propertyId.equals("salaryOffered"))
				{
					salaryOfferedCheckBox.setCaption(getLocalizedString("SALARY_OFFERED_CAPTION"));
					salaryOfferedCheckBox.setWidth("100%");
					
					return salaryOfferedCheckBox;
				}
				else if (propertyId.equals("insuranceOffered"))
				{
					insuranceOfferedCheckBox.setCaption(getLocalizedString("INSURANCE_OFFERED_CAPTION"));
					insuranceOfferedCheckBox.setWidth("100%");
					
					return insuranceOfferedCheckBox;
				}
				else if (propertyId.equals("transportationOffered"))
				{
					transportationOfferedCheckBox.setCaption(getLocalizedString("TRANSPORTATION_OFFERED_CAPTION"));
					transportationOfferedCheckBox.setWidth("100%");
					
					return transportationOfferedCheckBox;
				}

				return null;
			}
		});
	}

	@Override
	protected void setupLocalizedCaptions(Locale locale)
	{
		super.setupLocalizedCaptions(locale);
		
		form.setCaption(getLocalizedString("FORM_CAPTION"));

		accommodationOfferedCheckBox.setCaption(getLocalizedString("ACCOMMODATION_OFFERED_CAPTION"));
		salaryOfferedCheckBox.setCaption(getLocalizedString("SALARY_OFFERED_CAPTION"));
		insuranceOfferedCheckBox.setCaption(getLocalizedString("INSURANCE_OFFERED_CAPTION"));
		transportationOfferedCheckBox.setCaption(getLocalizedString("TRANSPORTATION_OFFERED_CAPTION"));
	}
	
	@Override
	public void setReadOnly(boolean readOnly)
	{
		super.setReadOnly(readOnly);
		
		form.setReadOnly(readOnly);
	}

}
