package softeng.coop.ui.composites;

import java.util.Locale;
import java.util.Vector;

import softeng.coop.business.Session;
import softeng.coop.dataaccess.AuthenticatedUser;
import softeng.coop.dataaccess.CoOp;
import softeng.coop.dataaccess.Student;
import softeng.coop.ui.ICoopContext;
import softeng.coop.ui.presenters.HeaderPresenter;
import softeng.coop.ui.viewdefinitions.IHeaderView;
import softeng.coop.ui.viewdefinitions.viewmodels.HeaderViewModel;
import softeng.coop.ui.viewdefinitions.viewmodels.LanguageInfo;
import softeng.ui.vaadin.mvp.IView;
import softeng.ui.vaadin.mvp.IViewListener;
import softeng.ui.vaadin.mvp.Presenter;
import softeng.ui.vaadin.mvp.ViewEvent;
import softeng.ui.vaadin.mvp.ViewEventSubscription;

import com.vaadin.addon.beanvalidation.BeanValidationForm;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.Property;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.util.BeanItem;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Component;
import com.vaadin.ui.Field;
import com.vaadin.ui.FormFieldFactory;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.Reindeer;

public class HeaderComponent 
	extends CoopComponent<HeaderViewModel>
	implements IHeaderView
{
	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private HorizontalLayout horizontalLayout;

	@AutoGenerated
	private ComboBox languagesComboBox;

	@AutoGenerated
	private Button registerButton;

	@AutoGenerated
	private UserForm userForm;

	@AutoGenerated
	private Label headerLabel;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	public static class UserForm extends BeanValidationForm<AuthenticatedUser>
	{
		private static final long serialVersionUID = 1L;

		public UserForm()
		{
			super(AuthenticatedUser.class);
		}
	}
	
	private static final long serialVersionUID = 1L;

	private ViewEventSubscription<HeaderViewModel, ICoopContext, IHeaderView> languageChangedSubscription =
		new ViewEventSubscription<HeaderViewModel, ICoopContext, IHeaderView>();
	
	private ViewEventSubscription<HeaderViewModel, ICoopContext, IHeaderView> selectedCoopChangedSubscription =
		new ViewEventSubscription<HeaderViewModel, ICoopContext, IHeaderView>();
	
	private ViewEventSubscription<HeaderViewModel, ICoopContext, IHeaderView> suggestRegistrationSubscription =
		new ViewEventSubscription<HeaderViewModel, ICoopContext, IHeaderView>();
	
	private ViewEventSubscription<HeaderViewModel, ICoopContext, IHeaderView> registerSubscription =
		new ViewEventSubscription<HeaderViewModel, ICoopContext, IHeaderView>();
	
	private CoopPickerField coopPickerField;
	
	private TextField userNameTextBox;
	
	private BeanItemContainer<LanguageInfo> languagesContainer;
	
	private BeanItem<? extends AuthenticatedUser> userItem;
	
	private boolean inhibitCoopChangeEvents = false;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public HeaderComponent()
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		mainLayout.addStyleName(Reindeer.LAYOUT_BLACK);
	}

	@Override
	public void addLanguageChangedListener(IViewListener<HeaderViewModel, ICoopContext, IHeaderView> listener)
	{
		this.languageChangedSubscription.add(listener);
	}

	@Override
	public void removeLanguageChangedListener(IViewListener<HeaderViewModel, ICoopContext, IHeaderView> listener)
	{
		this.languageChangedSubscription.remove(listener);
	}

	@Override
	public LanguageInfo getSelectedLanguageInfo()
	{
		return (LanguageInfo)this.languagesComboBox.getValue();
	}

	@Override
	public void setSelectedLanguageInfo(LanguageInfo languageInfo)
	{
		this.languagesComboBox.setValue(languageInfo);
	}

	@Override
	protected Presenter<HeaderViewModel, ICoopContext, ? extends IView<HeaderViewModel, ICoopContext>> supplyPresenter()
	{
		return new HeaderPresenter(this);
	}

	@Override
	public void dataBind()
	{
		if (this.languagesContainer == null)
		{
			this.languagesContainer =
				new BeanItemContainer<LanguageInfo>(LanguageInfo.class, this.getModel().getLanguageInfos());
			
			languagesComboBox.setContainerDataSource(this.languagesContainer);
			
			languagesComboBox.setItemCaptionPropertyId("languageName");
			languagesComboBox.setItemIconPropertyId("icon");
		}
		
		this.userItem = this.getModel().getAuthenticatedUser();
		
		if (userItem != null)
		{
			Vector<String> properties = new Vector<String>();
			
			//properties.add("userName");
			properties.add("defaultCoOp");
			
			this.userForm.setVisible(true);
			
			this.userForm.setItemDataSource(userItem, properties);
			
			if (this.getModel().getAuthenticatedUser().getBean() instanceof Student)
			{
				this.registerButton.setVisible(true);
			}
			else
			{
				this.registerButton.setVisible(false);
			}
		}
		else
		{
			this.userForm.setVisible(false);
			this.userForm.setItemDataSource(null);
			this.registerButton.setVisible(false);
		}
	}

	@Override
	protected void setupLocalizedCaptions(Locale locale)
	{
		super.setupLocalizedCaptions(locale);
		
//		this.headerLabel.setValue(
//				"<h1>" + getLocalizedString("APPLICATION_TITLE") + "</h1>");
		this.headerLabel.setValue(
				getLocalizedString("APPLICATION_TITLE"));
		
		if (this.coopPickerField != null)
			this.coopPickerField.setCaption(getLocalizedString("COOP_CAPTION"));
		
		if (this.userNameTextBox != null)
			this.userNameTextBox.setCaption(getLocalizedString("USER_NAME_CAPTION"));
		
		if (this.registerButton != null)
		{
			this.registerButton.setCaption(getLocalizedString("REGISTER_CAPTION"));
			this.registerButton.setDescription(getLocalizedString("REGISTER_DESCRIPTION"));
		}
	}

	@SuppressWarnings("serial")
	@Override
	protected void setupUI()
	{
		super.setupUI();
		
		this.languagesComboBox.setImmediate(true);
		this.languagesComboBox.setNullSelectionAllowed(false);
		this.languagesComboBox.setTextInputAllowed(false);
		
		final HeaderComponent me = this;
		
		this.languagesComboBox.addListener(new Property.ValueChangeListener()
		{
			@Override
			public void valueChange(ValueChangeEvent event)
			{
				languageChangedSubscription.fire(
						new ViewEvent<HeaderViewModel, ICoopContext, IHeaderView>(me));
			}
		});
		
		FormLayout formLayout = new FormLayout();
		
		formLayout.setMargin(false);
		
		userForm.setLayout(formLayout);
		userForm.setWriteThrough(false);
		
		userForm.setFormFieldFactory(new FormFieldFactory()
		{
			@Override
			public Field createField(Item item, Object propertyId, Component uiContext)
			{
				if (propertyId.equals("defaultCoOp"))
				{
					coopPickerField = 
						new CoopPickerField(getContext(), getLocalizedString("COOP_CAPTION"));
					
					coopPickerField.setReadThrough(false);

					coopPickerField.setWidth("100%");
					coopPickerField.setClearAllowed(false);
					coopPickerField.addListener(new Property.ValueChangeListener()
					{
						@Override
						public void valueChange(ValueChangeEvent event)
						{
							onDefaultCoopChange();
						}

					});
					
					return coopPickerField;
				}
				else if (propertyId.equals("userName"))
				{
					userNameTextBox = new TextField(getLocalizedString("USER_NAME_CAPTION"));
					userNameTextBox.setWidth("100%");
					userNameTextBox.setReadOnly(true);
					
					return userNameTextBox;
				}
				
				return null;
			}
		});
		
		registerButton.addListener(new Button.ClickListener()
		{
			@Override
			public void buttonClick(ClickEvent event)
			{
				onRegister();
			}
		});

	}

	private void onRegister()
	{
		if (this.userItem == null) return;
		if (!(this.userItem.getBean() instanceof Student)) return;
		
		registerSubscription.fire(new ViewEvent<HeaderViewModel, ICoopContext, IHeaderView>(this));
	}

	private void onDefaultCoopChange()
	{
		if (inhibitCoopChangeEvents) return;
		
		this.selectedCoopChangedSubscription.fire(
				new ViewEvent<HeaderViewModel, ICoopContext, IHeaderView>(this));
	}

	@Override
	public void addSelectedCoopChangedListener(IViewListener<HeaderViewModel, ICoopContext, IHeaderView> listener)
	{
		this.selectedCoopChangedSubscription.add(listener);
	}

	@Override
	public void removeSelectedCoopChangedListener(IViewListener<HeaderViewModel, ICoopContext, IHeaderView> listener)
	{
		this.selectedCoopChangedSubscription.remove(listener);
	}

	@Override
	public CoOp getSelectedCoop()
	{
		if (this.getModel().getAuthenticatedUser() == null) return null;
		
		if (this.coopPickerField == null) return null;
		
		return (CoOp)this.coopPickerField.getValue();
	}

	@Override
	public void fireSuggestRegistration()
	{
		suggestRegistrationSubscription.fire(new ViewEvent<HeaderViewModel, ICoopContext, IHeaderView>(this));
	}

	@Override
	public void addSuggestRegistrationListener(IViewListener<HeaderViewModel, ICoopContext, IHeaderView> listener)
	{
		suggestRegistrationSubscription.add(listener);
	}

	@Override
	public void removeSuggestRegistrationListener(IViewListener<HeaderViewModel, ICoopContext, IHeaderView> listener)
	{
		suggestRegistrationSubscription.remove(listener);
	}

	@Override
	public void addRegisterListener(IViewListener<HeaderViewModel, ICoopContext, IHeaderView> listener)
	{
		registerSubscription.add(listener);
	}

	@Override
	public void removeRegisterListener(IViewListener<HeaderViewModel, ICoopContext, IHeaderView> listener)
	{
		registerSubscription.remove(listener);
	}

	@Override
	public void reattachToSession()
	{
		Session session = getContext().getSession();
		
		AuthenticatedUser currentUser = session.getAuthenticatedUser();
		
		HeaderViewModel model = getModel();
		
		session.clean();
		
		if (currentUser != null)
		{
			currentUser = (AuthenticatedUser)session.attach(currentUser);
			//session.refreshEntity(currentUser);
			
			if (model != null)
			{
				model.setAuthenticatedUser(new BeanItem<AuthenticatedUser>(currentUser));
				
				inhibitCoopChangeEvents = true;
				
				try
				{
					dataBind();
				}
				finally
				{
					inhibitCoopChangeEvents = false;
				}
			}
		}
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout()
	{
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// horizontalLayout
		horizontalLayout = buildHorizontalLayout();
		mainLayout.addComponent(horizontalLayout);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout()
	{
		// common part: create layout
		horizontalLayout = new HorizontalLayout();
		horizontalLayout.setImmediate(false);
		horizontalLayout.setWidth("100.0%");
		horizontalLayout.setHeight("-1px");
		horizontalLayout.setMargin(false);
		horizontalLayout.setSpacing(true);
		
		// headerLabel
		headerLabel = new Label();
		headerLabel.setStyleName("logotype");
		headerLabel.setImmediate(false);
		headerLabel.setWidth("-1px");
		headerLabel.setHeight("-1px");
		headerLabel.setValue("Header here");
		headerLabel.setContentMode(3);
		horizontalLayout.addComponent(headerLabel);
		horizontalLayout.setComponentAlignment(headerLabel, new Alignment(33));
		
		// userForm
		userForm = new UserForm();
		userForm.setImmediate(false);
		userForm.setWidth("100.0%");
		userForm.setHeight("-1px");
		horizontalLayout.addComponent(userForm);
		horizontalLayout.setExpandRatio(userForm, 1.0f);
		horizontalLayout.setComponentAlignment(userForm, new Alignment(24));
		
		// registerButton
		registerButton = new Button();
		registerButton.setCaption("Εγγραφή...");
		registerButton.setImmediate(true);
		registerButton.setWidth("-1px");
		registerButton.setHeight("-1px");
		horizontalLayout.addComponent(registerButton);
		horizontalLayout.setComponentAlignment(registerButton, new Alignment(24));
		
		// languagesComboBox
		languagesComboBox = new ComboBox();
		languagesComboBox.setImmediate(false);
		languagesComboBox.setWidth("-1px");
		languagesComboBox.setHeight("-1px");
		horizontalLayout.addComponent(languagesComboBox);
		horizontalLayout.setComponentAlignment(languagesComboBox, new Alignment(10));
		
		return horizontalLayout;
	}

}
