package softeng.coop.ui.composites;

import java.util.Locale;
import java.util.Vector;

import softeng.coop.dataaccess.Branch;
import softeng.coop.dataaccess.Company;
import softeng.coop.dataaccess.JobPostingPart;
import softeng.coop.dataaccess.JobSiteType;
import softeng.coop.dataaccess.Location;
import softeng.coop.ui.EnumComboBox;
import softeng.coop.ui.ICoopContext;
import softeng.coop.ui.data.MultilingualValidationForm;
import softeng.coop.ui.viewdefinitions.IJobPostingPartFormView;
import softeng.ui.vaadin.mvp.IView;
import softeng.ui.vaadin.mvp.Presenter;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.Property;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.util.BeanItem;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Component;
import com.vaadin.ui.Field;
import com.vaadin.ui.FormFieldFactory;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class JobPostingPartComponent 
	extends CoopComponent<BeanItem<JobPostingPart>>
	implements IJobPostingPartFormView
{
	private static final long serialVersionUID = 1L;

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private JobPostingPartForm form;
	
	private TextField descriptionTextArea;
	private BranchPickerField branchField;
	private TextField startDayField;
	private TextField durationDaysField;
	private BranchCompanyPersonPicker managingCompanyPersonPicker;
	private TextField paidDaysTextField;
	private ComboBox siteTypeComboBox;
	private GeoLocationPickerField expeditionGeoLocationPickerField;
	private LocationPickerField expeditionLocationPickerField;
	private JobPostingPartSpecialPayablesTableComponent specialPayablesTableComponent;
	
	private Company company = null;
	
	private static Vector<String> propertyIds = createPropertyIds();
	
	private class BranchChangeListener implements Property.ValueChangeListener
	{
		@Override
		public void valueChange(ValueChangeEvent event)
		{
			if (branchField == null || managingCompanyPersonPicker == null) return;
			
			managingCompanyPersonPicker.setValue(null);
			
			if (branchField.getValue() != null)
			{
				managingCompanyPersonPicker.setBranch((Branch) branchField.getValue());
			}
			else
			{
				managingCompanyPersonPicker.setBranch(null);
			}
		}
	}
	
	private BranchChangeListener branchChangeListener = new BranchChangeListener();
	
	private class JobPostingPartForm 
		extends MultilingualValidationForm<JobPostingPart>
	{
		private static final long serialVersionUID = 1L;

		public JobPostingPartForm() 
		{
			super(JobPostingPart.class);
		}
	}
	
	
	public JobPostingPartComponent()
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);

	}
	
	@Override
	public void setReadOnly(boolean readOnly) 
	{
		super.setReadOnly(readOnly);
		
		this.form.setReadOnly(readOnly);
	}

	@Override
	public void dataBind() 
	{
		form.setItemDataSource(this.getModel(), propertyIds);
	}

	private static Vector<String> createPropertyIds()
	{
		Vector<String> properties = new Vector<String>();
		
		properties.add("description");
		properties.add("branch");
		properties.add("startDay");
		properties.add("durationDays");
		properties.add("managingCompanyPerson");
		properties.add("siteType");
		properties.add("expeditionLocation");
		properties.add("expeditionGeoLocation");
		properties.add("paidDays");
		properties.add("specialPayables");
		
		return properties;
	}

	@Override
	protected void setupUI() 
	{
		super.setupUI();
		
		this.form.setImmediate(true);
		this.form.setWriteThrough(false);
		
		this.form.setFormFieldFactory(new FormFieldFactory() 
		{
			@Override
			public Field createField(Item item, Object propertyId, Component uiContext) 
			{
				if (propertyId.equals("description"))
				{
					descriptionTextArea = new TextField();
					descriptionTextArea.setCaption(getLocalizedString("DESCRIPTION_CAPTION"));
					descriptionTextArea.setWidth("100%");
					descriptionTextArea.setNullRepresentation("");
					//descriptionRichTextArea.setHeight("135px");
					
					return descriptionTextArea;
				}
				else if (propertyId.equals("branch"))
				{
					if (branchField != null)
					{
						branchField.removeListener(branchChangeListener);
					}
					
					branchField = new BranchPickerField();
					branchField.setCaption(getLocalizedString("BRANCH_CAPTION"));
					branchField.setWidth("100%");
					branchField.setCompanyBrowsingAllowed(true);
					branchField.setCompany(company);
					
					branchField.addListener(branchChangeListener);
					
					branchField.setParentAdjuster(new PickerField.ParentAdjuster<Branch>()
					{
						@Override
						public void addToParent(Branch element)
						{
							if (!getContext().getSession().isLoaded(element, "jobPostingParts")) 
								return;
					
							element.getJobPostingParts().add(getModel().getBean());
						}

						@Override
						public void removeFromParent(Branch element)
						{
							if (!getContext().getSession().isLoaded(element, "jobPostingParts")) 
								return;
					
							element.getJobPostingParts().remove(getModel().getBean());
						}
					});
					
					return branchField;
				}
				else if (propertyId.equals("startDay"))
				{
					startDayField = new TextField();
					startDayField.setCaption(getLocalizedString("START_DAY_CAPTION"));
					startDayField.setDescription(getLocalizedString("START_DAY_DESCRIPTION"));
					startDayField.setWidth("100%");
					
					return startDayField;
				}
				else if (propertyId.equals("durationDays"))
				{
					durationDaysField = new TextField();
					durationDaysField.setCaption(getLocalizedString("DURATION_DAYS_CAPTION"));
					durationDaysField.setDescription(getLocalizedString("DURATION_DAYS_DESCRIPTION"));
					durationDaysField.setWidth("100%");
					durationDaysField.setNullRepresentation("");
					
					return durationDaysField;
				}
				else if (propertyId.equals("managingCompanyPerson"))
				{
					managingCompanyPersonPicker = new BranchCompanyPersonPicker();
					managingCompanyPersonPicker.setCaption(getLocalizedString("MANAGING_COMPANY_PERSON_CAPTION"));
					managingCompanyPersonPicker.setWidth("100%");
					managingCompanyPersonPicker.setBranch(getModel().getBean().getBranch());
					
					return managingCompanyPersonPicker;
				}
				else if (propertyId.equals("paidDays"))
				{
					paidDaysTextField = new TextField();
					paidDaysTextField.setCaption(getLocalizedString("PAID_DAYS_CAPTION"));
					paidDaysTextField.setDescription(getLocalizedString("PAID_DAYS_DESCRIPTION"));
					paidDaysTextField.setWidth("100%");
					paidDaysTextField.setNullRepresentation("");
					paidDaysTextField.setNullSettingAllowed(true);
					
					return paidDaysTextField;
				}
				else if (propertyId.equals("siteType"))
				{
					siteTypeComboBox = new EnumComboBox(JobSiteType.class);
					siteTypeComboBox.setCaption(getLocalizedString("SITE_TYPE_CAPTION"));
					siteTypeComboBox.setWidth("100%");
					siteTypeComboBox.setNullSelectionAllowed(false);
					siteTypeComboBox.setTextInputAllowed(false);
					
					return siteTypeComboBox;
				}
				else if (propertyId.equals("expeditionLocation"))
				{
					expeditionLocationPickerField = new LocationPickerField();
					expeditionLocationPickerField.setCaption(getLocalizedString("EXPEDITION_LOCATION_CAPTION"));
					expeditionLocationPickerField.setWidth("100%");
					
					expeditionLocationPickerField.setParentAdjuster(new PickerField.ParentAdjuster<Location>()
					{
						@Override
						public void addToParent(Location element)
						{
							if (!getContext().getSession().isLoaded(element, "jobPostingPartsInExpedition")) 
								return;
					
							element.getJobPostingPartsInExpedition().add(getModel().getBean());
						}

						@Override
						public void removeFromParent(Location element)
						{
							if (!getContext().getSession().isLoaded(element, "jobPostingPartsInExpedition")) 
								return;
					
							element.getJobPostingPartsInExpedition().remove(getModel().getBean());
						}
					});
					
					return expeditionLocationPickerField;
				}
				else if (propertyId.equals("expeditionGeoLocation"))
				{
					expeditionGeoLocationPickerField = new GeoLocationPickerField();
					expeditionGeoLocationPickerField.setCaption(getLocalizedString("EXPEDITION_GEO_LOCATION_CAPTION"));
					expeditionGeoLocationPickerField.setWidth("100%");
					
					return expeditionGeoLocationPickerField;
				}
				else if (propertyId.equals("specialPayables"))
				{
					specialPayablesTableComponent = 
						new JobPostingPartSpecialPayablesTableComponent(getContext().getSelectedCoop());
					specialPayablesTableComponent.setCaption(getLocalizedString("SPECIAL_PAYABLES_CAPTION"));
					specialPayablesTableComponent.setDescription(getLocalizedString("SPECIAL_PAYABLES_DESCRIPTION"));
					specialPayablesTableComponent.setWidth("100%");
					specialPayablesTableComponent.setParentModel(getModel().getBean());
					
					return specialPayablesTableComponent;
				}
				
				return null;
			}
		});
		
	}

	@Override
	protected void setupLocalizedCaptions(Locale locale) 
	{
		super.setupLocalizedCaptions(locale);
		
		form.setCaption(getLocalizedString("FORM_CAPTION"));
		
		if (descriptionTextArea != null)
			descriptionTextArea.setCaption(getLocalizedString("DESCRIPTION_CAPTION"));
		
		if (branchField != null)
			branchField.setCaption(getLocalizedString("BRANCH_CAPTION"));
		
		if (startDayField != null)
		{
			startDayField.setCaption(getLocalizedString("START_DAY_CAPTION"));
			startDayField.setDescription(getLocalizedString("START_DAY_DESCRIPTION"));
		}
		
		if (durationDaysField != null)
		{
			durationDaysField.setCaption(getLocalizedString("DURATION_DAYS_CAPTION"));
			durationDaysField.setDescription(getLocalizedString("DURATION_DAYS_DESCRIPTION"));
		}
		
		if (managingCompanyPersonPicker != null)
			managingCompanyPersonPicker.setCaption(getLocalizedString("MANAGING_COMPANY_PERSON_CAPTION"));
		
		if (paidDaysTextField != null)
		{
			paidDaysTextField.setCaption(getLocalizedString("PAID_DAYS_CAPTION"));
			paidDaysTextField.setDescription(getLocalizedString("PAID_DAYS_DESCRIPTION"));
		}
		
		if (siteTypeComboBox != null)
			siteTypeComboBox.setCaption(getLocalizedString("SITE_TYPE_CAPTION"));
		
		if (expeditionLocationPickerField != null)
			expeditionLocationPickerField.setCaption(getLocalizedString("EXPEDITION_LOCATION_CAPTION"));
		
		if (expeditionGeoLocationPickerField != null)
			expeditionGeoLocationPickerField.setCaption(getLocalizedString("EXPEDITION_GEO_LOCATION_CAPTION"));
		
		if (specialPayablesTableComponent != null)
		{
			specialPayablesTableComponent.setCaption(getLocalizedString("SPECIAL_PAYABLES_CAPTION"));
			specialPayablesTableComponent.setDescription(getLocalizedString("SPECIAL_PAYABLES_DESCRIPTION"));
		}
	}

	@Override
	public boolean isDataValid() 
	{
		return this.form.isValid();
	}

	@Override
	public void discardChanges() 
	{
		this.form.discard();
	}

	@Override
	public void commitChangesToModel() 
	{
		this.form.commit();
	}

	@Override
	protected Presenter<BeanItem<JobPostingPart>, ICoopContext, ? extends IView<BeanItem<JobPostingPart>, ICoopContext>> 
		supplyPresenter() 
	{
		
		return null;
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout()
	{
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// form
		form = new JobPostingPartForm();
		form.setCaption("Τμήμα Εργασίας");
		form.setImmediate(false);
		form.setWidth("100.0%");
		form.setHeight("-1px");
		mainLayout.addComponent(form);
		
		return mainLayout;
	}

	@Override
	public void setCompanyForJobPostingPart(Company company) 
	{
		this.company = company;
	}

	@Override
	public Company getCompanyForJobPostingPart() 
	{
		return this.company;
	}

}
