package softeng.coop.ui.composites;

import java.util.Locale;
import java.util.Vector;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.Property;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.util.BeanItem;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Component;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Field;
import com.vaadin.ui.FormFieldFactory;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import softeng.coop.dataaccess.Branch;
import softeng.coop.dataaccess.Company;
import softeng.coop.dataaccess.JobPart;
import softeng.coop.dataaccess.JobSiteType;
import softeng.coop.dataaccess.Location;
import softeng.coop.ui.EnumComboBox;
import softeng.coop.ui.ICoopContext;
import softeng.coop.ui.data.MultilingualValidationForm;
import softeng.coop.ui.viewdefinitions.IJobPartFormView;
import softeng.ui.vaadin.mvp.IView;
import softeng.ui.vaadin.mvp.Presenter;

@SuppressWarnings("serial")
public class JobPartComponent 
	extends CoopComponent<BeanItem<JobPart>> 
	implements IJobPartFormView
{
	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private JobPartForm form;
	
	private TextArea descriptionTextField;
	private BranchPickerField branchField;
	private DateField startDateField;
	private DateField endDateField;
	private BranchCompanyPersonPicker managingCompanyPersonPicker;
	private TextArea commentsTextArea;
	private ComboBox siteTypeComboBox;
	private TextField paidDaysTextField;
	private LocationPickerField expeditionLocationPickerField;
	private GeoLocationPickerField expeditionGeoLocationPickerField;
	private JobPartSpecialPayablesTableComponent specialPayablesTableComponent;
	
	private Company company = null;
	
	private Vector<String> propertyIds = createPropertyIds();
	
	private class JobPartForm 
		extends MultilingualValidationForm<JobPart>
	{
		public JobPartForm() 
		{
			super(JobPart.class);
		}
	}
	
	private class BranchChangeListener implements Property.ValueChangeListener
	{
		@Override
		public void valueChange(ValueChangeEvent event)
		{
			if (branchField == null || managingCompanyPersonPicker == null) return;
			
			managingCompanyPersonPicker.setValue(null);
			
			if (branchField.getValue() != null)
			{
				managingCompanyPersonPicker.setBranch((Branch) branchField.getValue());
			}
			else
			{
				managingCompanyPersonPicker.setBranch(null);
			}
		}
	}
	
	private BranchChangeListener branchChangeListener = new BranchChangeListener();
	
	public JobPartComponent()
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);

	}
	
	@Override
	public void dataBind() 
	{
		form.setItemDataSource(this.getModel(), propertyIds);
		
	}

	private static Vector<String> createPropertyIds()
	{
		Vector<String> properties = new Vector<String>();
		
		properties.add("description");
		properties.add("branch");
		properties.add("startDate");
		properties.add("endDate");
		properties.add("managingCompanyPerson");
		properties.add("siteType");
		properties.add("expeditionLocation");
		properties.add("expeditionGeoLocation");
		properties.add("comments");
		properties.add("paidDays");
		properties.add("specialPayables");

		return properties;
	}

	@Override
	protected void setupUI() 
	{
		super.setupUI();
		
		this.form.setImmediate(true);
		this.form.setWriteThrough(false);
		
		this.form.setFormFieldFactory(new FormFieldFactory() 
		{
			@Override
			public Field createField(Item item, Object propertyId, Component uiContext) 
			{
				if (propertyId.equals("description"))
				{
					descriptionTextField = new TextArea();
					descriptionTextField.setCaption(getLocalizedString("DESCRIPTION_CAPTION"));
					descriptionTextField.setWidth("100%");
					descriptionTextField.setNullRepresentation("");
					descriptionTextField.setNullSettingAllowed(true);
					
					return descriptionTextField;
				}
				else if (propertyId.equals("branch"))
				{
					if (branchField != null)
					{
						branchField.removeListener(branchChangeListener);
					}
					
					branchField = new BranchPickerField();
					branchField.setCaption(getLocalizedString("BRANCH_CAPTION"));
					branchField.setWidth("100%");
					branchField.setCompanyBrowsingAllowed(true);
					branchField.setCompany(company);
					
					branchField.addListener(branchChangeListener);
					
					branchField.setParentAdjuster(new PickerField.ParentAdjuster<Branch>()
					{

						@Override
						public void addToParent(Branch element)
						{
							if (!getContext().getSession().isLoaded(element, "jobParts")) 
								return;
					
							element.getJobParts().add(getModel().getBean());
						}

						@Override
						public void removeFromParent(Branch element)
						{
							if (!getContext().getSession().isLoaded(element, "jobParts")) 
								return;
					
							element.getJobParts().remove(getModel().getBean());
						}
					});
					
					return branchField;
				}
				else if (propertyId.equals("startDate"))
				{
					startDateField = new DateField();
					startDateField.setCaption(getLocalizedString("START_DATE_CAPTION"));
					startDateField.setWidth("100%");
					startDateField.setResolution(DateField.RESOLUTION_DAY);
					
					return startDateField;
				}
				else if (propertyId.equals("endDate"))
				{
					endDateField = new DateField();
					endDateField.setCaption(getLocalizedString("END_DATE_CAPTION"));
					endDateField.setWidth("100%");
					endDateField.setResolution(DateField.RESOLUTION_DAY);
					
					return endDateField;
				}
				else if (propertyId.equals("managingCompanyPerson"))
				{
					managingCompanyPersonPicker = new BranchCompanyPersonPicker();
					managingCompanyPersonPicker.setCaption(getLocalizedString("MANAGING_COMPANY_PERSON_CAPTION"));
					managingCompanyPersonPicker.setWidth("100%");
					managingCompanyPersonPicker.setBranch(getModel().getBean().getBranch());
					
					return managingCompanyPersonPicker;
				}
				else if (propertyId.equals("comments") && !isUserStudent())
				{
					commentsTextArea = new TextArea();
					commentsTextArea.setCaption(getLocalizedString("COMMENTS_CAPTION"));
					commentsTextArea.setWidth("100%");
					commentsTextArea.setNullRepresentation("");
					commentsTextArea.setHeight("135px");
					
					return commentsTextArea;
				}
				else if (propertyId.equals("siteType"))
				{
					siteTypeComboBox = new EnumComboBox(JobSiteType.class);
					siteTypeComboBox.setCaption(getLocalizedString("SITE_TYPE_CAPTION"));
					siteTypeComboBox.setWidth("100%");
					siteTypeComboBox.setNullSelectionAllowed(false);
					
					return siteTypeComboBox;
				}
				else if (propertyId.equals("paidDays") && !isUserStudent())
				{
					paidDaysTextField = new TextField();
					paidDaysTextField.setCaption(getLocalizedString("PAID_DAYS_CAPTION"));
					paidDaysTextField.setDescription(getLocalizedString("PAID_DAYS_DESCRIPTION"));
					paidDaysTextField.setWidth("100%");
					paidDaysTextField.setNullRepresentation("");
					paidDaysTextField.setNullSettingAllowed(true);
					
					return paidDaysTextField;
				}
				else if (propertyId.equals("expeditionLocation"))
				{
					expeditionLocationPickerField = new LocationPickerField();
					expeditionLocationPickerField.setCaption(getLocalizedString("EXPEDITION_LOCATION_CAPTION"));
					expeditionLocationPickerField.setDescription(getLocalizedString("EXPEDITION_LOCATION_DESCRIPTION"));
					expeditionLocationPickerField.setWidth("100%");
					
					expeditionLocationPickerField.setParentAdjuster(new PickerField.ParentAdjuster<Location>()
					{
						@Override
						public void addToParent(Location element)
						{
							if (!getContext().getSession().isLoaded(element, "jobPartsInExpedition")) 
								return;
					
							element.getJobPartsInExpedition().add(getModel().getBean());
						}

						@Override
						public void removeFromParent(Location element)
						{
							if (!getContext().getSession().isLoaded(element, "jobPartsInExpedition")) 
								return;
					
							element.getJobPartsInExpedition().add(getModel().getBean());
						}
					});
					
					return expeditionLocationPickerField;
				}
				else if (propertyId.equals("expeditionGeoLocation"))
				{
					expeditionGeoLocationPickerField = new GeoLocationPickerField();
					expeditionGeoLocationPickerField.setCaption(getLocalizedString("EXPEDITION_GEO_LOCATION_CAPTION"));
					expeditionGeoLocationPickerField.setDescription(getLocalizedString("EXPEDITION_GEO_LOCATION_DESCRIPTION"));
					expeditionGeoLocationPickerField.setWidth("100%");
					
					return expeditionGeoLocationPickerField;
				}
				else if (propertyId.equals("specialPayables") && !isUserStudent())
				{
					specialPayablesTableComponent = 
						new JobPartSpecialPayablesTableComponent(getContext().getSelectedCoop());
					specialPayablesTableComponent.setCaption(getLocalizedString("SPECIAL_PAYABLES_CAPTION"));
					specialPayablesTableComponent.setDescription(getLocalizedString("SPECIAL_PAYABLES_DESCRIPTION"));
					specialPayablesTableComponent.setWidth("100%");
					specialPayablesTableComponent.setParentModel(getModel().getBean());
					
					return specialPayablesTableComponent;
				}
				
				return null;
			}
		});
	}

	@Override
	protected void setupLocalizedCaptions(Locale locale) 
	{
		super.setupLocalizedCaptions(locale);
		
		form.setCaption(getLocalizedString("FORM_CAPTION"));
		
		if (descriptionTextField != null)
			descriptionTextField.setCaption(getLocalizedString("DESCRIPTION_CAPTION"));
		
		if (branchField != null)
			branchField.setCaption(getLocalizedString("BRANCH_CAPTION"));
		
		if (startDateField != null)
			startDateField.setCaption(getLocalizedString("START_DATE_CAPTION"));
		
		if (endDateField != null)
			endDateField.setCaption(getLocalizedString("END_DATE_CAPTION"));
		
		if (managingCompanyPersonPicker != null)
			managingCompanyPersonPicker.setCaption(getLocalizedString("MANAGING_COMPANY_PERSON_CAPTION"));
		
		if (commentsTextArea != null)
			commentsTextArea.setCaption(getLocalizedString("COMMENTS_CAPTION"));
		
		if (siteTypeComboBox != null)
			siteTypeComboBox.setCaption(getLocalizedString("SITE_TYPE_CAPTION"));
		
		if (paidDaysTextField != null)
		{
			paidDaysTextField.setCaption(getLocalizedString("PAID_DAYS_CAPTION"));
			paidDaysTextField.setDescription(getLocalizedString("PAID_DAYS_DESCRIPTION"));
		}
		
		if (expeditionLocationPickerField != null)
		{
			expeditionLocationPickerField.setCaption(getLocalizedString("EXPEDITION_LOCATION_CAPTION"));
			expeditionLocationPickerField.setDescription(getLocalizedString("EXPEDITION_LOCATION_DESCRIPTION"));
		}
		
		if (expeditionGeoLocationPickerField != null)
		{
			expeditionGeoLocationPickerField.setCaption(getLocalizedString("EXPEDITION_GEO_LOCATION_CAPTION"));
			expeditionGeoLocationPickerField.setDescription(getLocalizedString("EXPEDITION_GEO_LOCATION_DESCRIPTION"));
		}

		if (specialPayablesTableComponent != null)
		{
			specialPayablesTableComponent.setCaption(getLocalizedString("SPECIAL_PAYABLES_CAPTION"));
			specialPayablesTableComponent.setDescription(getLocalizedString("SPECIAL_PAYABLES_DESCRIPTION"));
		}
	}

	@Override
	public boolean isDataValid() 
	{
		return this.form.isValid();
	}

	@Override
	public void discardChanges() 
	{
		this.form.discard();
	}

	@Override
	public void commitChangesToModel() 
	{
		this.form.commit();
	}

	@Override
	protected Presenter<BeanItem<JobPart>, ICoopContext, ? extends IView<BeanItem<JobPart>, ICoopContext>> 
		supplyPresenter() 
	{
		
		return null;
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout()
	{
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// form
		form = new JobPartForm();
		form.setCaption("Τμήμα Εργασίας");
		form.setImmediate(false);
		form.setWidth("100.0%");
		form.setHeight("-1px");
		mainLayout.addComponent(form);
		
		return mainLayout;
	}

	@Override
	public void setReadOnly(boolean readOnly) 
	{
		super.setReadOnly(readOnly);
		
		this.form.setReadOnly(readOnly);
	}

	@Override
	public void setCompanyForJobPart(Company company) 
	{
		this.company = company;
	}

	@Override
	public Company getCompanyForJobPart() 
	{
		return this.company;
	}

}
