package softeng.coop.ui.composites;

import java.util.List;
import java.util.Locale;
import java.util.Vector;

import softeng.coop.dataaccess.AuthenticatedUser;
import softeng.coop.dataaccess.Department;
import softeng.coop.dataaccess.FacultyUser;
import softeng.coop.dataaccess.Gender;
import softeng.coop.dataaccess.Person;
import softeng.coop.dataaccess.Student;
import softeng.coop.ui.EnumComboBox;
import softeng.coop.ui.ICoopContext;
import softeng.coop.ui.LanguageComboBox;
import softeng.coop.ui.data.AccessCheck;
import softeng.coop.ui.data.AtLeastOneMobilePhoneValidator;
import softeng.coop.ui.data.DataUtilities;
import softeng.coop.ui.data.MinSizeMultilingualValidator;
import softeng.coop.ui.data.MultilingualValidationForm;
import softeng.coop.ui.data.NotNullMultilingualValidator;
import softeng.coop.ui.viewdefinitions.IPersonDataView;
import softeng.ui.vaadin.mvp.IView;
import softeng.ui.vaadin.mvp.Presenter;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.Property;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.util.BeanItem;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Component;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Field;
import com.vaadin.ui.FormFieldFactory;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class PersonDataComponent 
	extends CoopComponent<BeanItem<? extends Person>>
	implements IPersonDataView
{
	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private PersonForm personForm;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	public static class PersonForm extends MultilingualValidationForm<Person>//BeanValidationForm<Person>
	{
		private static final long serialVersionUID = 1L;

		public PersonForm()
		{
			super(Person.class);
		}
	}
	
	private static final long serialVersionUID = 1L;
	
	private TextField lastNameTextField;
	private TextField firstNameTextField;
	private TextField emailTextField;
	private TelephonesTableComponent telephonesTableComponent;
	private TextField userNameTextField;
	private TextField fatherNameTextField;
	private TextField motherNameTextField;
	private DateField dateOfBirthDateField;
	private ComboBox genderComboBox;
	private TextField notesTextField;
	private TextField positionTextField;
	private TextField faxNumberTextField;
	private TextField salutationTextField;
	private AddressesTableComponent addressesTableComponent;
	private TextField professorRankField;
	private CheckBox activeCheckBox;
//	private DivisionPickerField divisionPickerField;
	private LanguageComboBox preferredLanguageComboBox;
	private ComboBox divisionComboBox;
	private ComboBox departmentComboBox;
	
	private AccessCheck accessCheck;

	private ViewMode mode;
	private Orientation orientation;
	private boolean isFullyWritable = false;
	
	private static NotNullMultilingualValidator notNullValidator = new NotNullMultilingualValidator();
	private static MinSizeMultilingualValidator minAddressesSizeValidator = new MinSizeMultilingualValidator(1);
	private static MinSizeMultilingualValidator minTelephonesSizeValidator = new MinSizeMultilingualValidator(2);
	private static AtLeastOneMobilePhoneValidator atLeastOneMobilePhoneValidator = new AtLeastOneMobilePhoneValidator();
	
	private static List<String> propertyIds = createPropertyIds();
	
	public enum ViewMode
	{
		Full,
		Compact
	}
	
	public enum Orientation
	{
		Vertical,
		Horizontal
	}
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public PersonDataComponent()
	{
		mode = ViewMode.Full;
		orientation = Orientation.Vertical;
		
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}
	
	@Override
	protected Presenter<BeanItem<? extends Person>, ICoopContext, ? extends IView<BeanItem<? extends Person>, ICoopContext>> supplyPresenter()
	{
		return null;
	}
	
	private static List<String> createPropertyIds()
	{
		Vector<String> list = new Vector<String>();
		
		list.add("rank");
		list.add("surname");
		list.add("name");
		list.add("position");
		list.add("university");
		list.add("department");
		list.add("division");
		list.add("active");
		list.add("salutation");
		list.add("userName");
		list.add("email");
		list.add("faxNumber");
		list.add("preferredLanguage");
		list.add("fatherName");
		list.add("motherName");
		list.add("dateOfBirth");
		list.add("gender");
		list.add("addresses");
		list.add("telephones");
		list.add("notes");
		
		return list;
	}

	@Override
	public void dataBind()
	{
		accessCheck = new AccessCheck(getContext().getSession());
		
		personForm.setItemDataSource(this.getModel(), propertyIds);
	}

	@Override
	protected void setupLocalizedCaptions(Locale locale)
	{
		super.setupLocalizedCaptions(locale);
		
//		if (mode == ViewMode.Full)
		personForm.setCaption(getLocalizedString("PERSON_DATA_CAPTION"));
		
		if (firstNameTextField != null)
			firstNameTextField.setCaption(getLocalizedString("PERSON_NAME_CAPTION"));
		
		if (lastNameTextField != null)
			lastNameTextField.setCaption(getLocalizedString("PERSON_SURNAME_CAPTION"));

		if (userNameTextField != null)
		{
			userNameTextField.setCaption(getLocalizedString("PERSON_USERNAME_CAPTION"));
			userNameTextField.setDescription(getLocalizedString("PERSON_USERNAME_DESCRIPTION"));
		}
		
		if (fatherNameTextField != null)
			fatherNameTextField.setCaption(getLocalizedString("PERSON_FATHER_NAME_CAPTION"));
		
		if (motherNameTextField != null)
			motherNameTextField.setCaption(getLocalizedString("PERSON_MOTHER_NAME_CAPTION"));
		
		if (dateOfBirthDateField != null)
		{
			dateOfBirthDateField.setCaption(getLocalizedString("PERSON_DATE_OF_BIRTH_CAPTION"));
			dateOfBirthDateField.setLocale(locale);
		}
		
		if (genderComboBox != null)
			genderComboBox.setCaption(getLocalizedString("PERSON_GENDER_CAPTION"));
		
		if (notesTextField != null)
			notesTextField.setCaption(getLocalizedString("PERSON_NOTES_CAPTION"));
		
		if (positionTextField != null)
			positionTextField.setCaption(getLocalizedString("POSITION_CAPTION"));
		
		if (faxNumberTextField != null)
			faxNumberTextField.setCaption(getLocalizedString("FAX_NUMBER_CAPTION"));
		
		if (salutationTextField != null)
		{
			salutationTextField.setCaption(getLocalizedString("SALUTATION_CAPTION"));
			salutationTextField.setDescription(getLocalizedString("SALUTATION_DESCRIPTION"));
		}

		if (addressesTableComponent != null)
			addressesTableComponent.setCaption(getLocalizedString("ADDRESSES_CAPTION"));
		
		if (professorRankField != null)
			professorRankField.setCaption(getLocalizedString("PROFESSOR_RANK_CAPTION"));
		
		if (activeCheckBox != null)
			activeCheckBox.setCaption(getLocalizedString("ACTIVE_CAPTION"));
		
		if (telephonesTableComponent != null)
			telephonesTableComponent.setCaption(getLocalizedString("PERSON_TELEPHONES_CAPTION"));

//		if (divisionPickerField != null)
//			divisionPickerField.setCaption(getLocalizedString("DIVISION_CAPTION"));

		if (divisionComboBox != null)
		{
			divisionComboBox.setCaption(getLocalizedString("DIVISION_CAPTION"));
			
			DataUtilities.updateMultilingual(divisionComboBox);
		}
		
		if (departmentComboBox != null)
		{
			departmentComboBox.setCaption(getLocalizedString("DEPARTMENT_CAPTION"));
			
			DataUtilities.updateMultilingual(departmentComboBox);
		}

		if (preferredLanguageComboBox != null)
			preferredLanguageComboBox.setCaption(getLocalizedString("PREFERRED_LANGUAGE_CAPTION"));

	}

	@SuppressWarnings("serial")
	@Override
	protected void setupUI()
	{
		super.setupUI();
		
		// Form setup.
		this.personForm.setImmediate(true);
		this.personForm.setWriteThrough(false);
		
		//check orientation
		if (orientation == Orientation.Horizontal)
		{
			HorizontalLayout horizontal = new HorizontalLayout();
			horizontal.setSpacing(true);
			horizontal.setWidth("100%");
			this.personForm.setLayout(horizontal);
			this.personForm.setCaption("");
		}
		
		this.personForm.setFormFieldFactory(new FormFieldFactory()
		{
			@Override
			public Field createField(Item item, Object propertyId, Component uiContext)
			{
				if (propertyId.equals("name"))
				{
					firstNameTextField = new TextField(getLocalizedString("PERSON_NAME_CAPTION"));
					if (!isFullyWritable)
						firstNameTextField.setReadOnly(getModel().getBean() instanceof AuthenticatedUser);
					else
						firstNameTextField.setReadOnly(personForm.isReadOnly());
					
					firstNameTextField.setWidth("100%");
					
					firstNameTextField.setNullRepresentation("");
					firstNameTextField.setNullSettingAllowed(true);
					
					return firstNameTextField;
				}
				else if (propertyId.equals("surname"))
				{
					lastNameTextField = new TextField(getLocalizedString("PERSON_SURNAME_CAPTION"));
					
					if (!isFullyWritable)
						lastNameTextField.setReadOnly(getModel().getBean() instanceof AuthenticatedUser);
					else
						lastNameTextField.setReadOnly(personForm.isReadOnly());
					
					lastNameTextField.setWidth("100%");
					
					lastNameTextField.setNullRepresentation("");
					lastNameTextField.setNullSettingAllowed(true);
					
					return lastNameTextField;
				}
				else if (propertyId.equals("addresses") && mode==ViewMode.Full && (!isUserStudent() || isModelSelf()))
				{
					addressesTableComponent = 
						new AddressesTableComponent(getLocalizedString("ADDRESSES_CAPTION"));
					
					addressesTableComponent.setWidth("100%");
					
					addressesTableComponent.setParentModel(getModel().getBean());
					
					addressesTableComponent.setReadOnly(personForm.isReadOnly());
					
					if (isModelStudent() && isUserStudent())
						addressesTableComponent.addValidator(minAddressesSizeValidator);
					
					return addressesTableComponent;
				}
				else if (propertyId.equals("userName") && mode==ViewMode.Full && (!isUserStudent() || isModelSelf()))
				{
					userNameTextField = new TextField(getLocalizedString("PERSON_USERNAME_CAPTION"));
					userNameTextField.setDescription(getLocalizedString("PERSON_USERNAME_DESCRIPTION"));
					
					if (!isFullyWritable)
						userNameTextField.setReadOnly(getModel().getBean() instanceof AuthenticatedUser);
					else
						userNameTextField.setReadOnly(personForm.isReadOnly());
					
					userNameTextField.setWidth("100%");
					
					userNameTextField.setNullRepresentation("");
					userNameTextField.setNullSettingAllowed(true);
					
					return userNameTextField;
				}
				else if (propertyId.equals("telephones") && (!isUserStudent() || isModelStudent()))
				{
					telephonesTableComponent = new TelephonesTableComponent();
					telephonesTableComponent.setCaption(getLocalizedString("PERSON_TELEPHONES_CAPTION"));
					telephonesTableComponent.setWidth("100%");
					telephonesTableComponent.setParentModel(getModel().getBean());
					telephonesTableComponent.setReadOnly(personForm.isReadOnly());
					
					if (isModelStudent() && isUserStudent())
					{
						telephonesTableComponent.addValidator(minTelephonesSizeValidator);
						telephonesTableComponent.addValidator(atLeastOneMobilePhoneValidator);
					}
					
					return telephonesTableComponent;
				}
				else if (propertyId.equals("email"))
				{
					emailTextField = new TextField(getLocalizedString("PERSON_EMAIL_CAPTION"));
					emailTextField.setWidth("100%");
					emailTextField.setReadOnly(personForm.isReadOnly());
					
					emailTextField.setNullRepresentation("");
					emailTextField.setNullSettingAllowed(true);
					
					if (isModelStudent())
						emailTextField.addValidator(notNullValidator);
					
					return emailTextField;
				}
				else if (propertyId.equals("fatherName"))
				{
					fatherNameTextField = new TextField(getLocalizedString("PERSON_FATHER_NAME_CAPTION"));
					
					fatherNameTextField.setWidth("100%");
					fatherNameTextField.setReadOnly(personForm.isReadOnly());
					
					fatherNameTextField.setNullRepresentation("");
					fatherNameTextField.setNullSettingAllowed(true);
					
					if (isModelStudent())
						fatherNameTextField.addValidator(notNullValidator);
					
					return fatherNameTextField;
				}
				else if (propertyId.equals("motherName") && mode==ViewMode.Full)
				{
					motherNameTextField = new TextField(getLocalizedString("PERSON_MOTHER_NAME_CAPTION"));
					
					motherNameTextField.setWidth("100%");
					motherNameTextField.setReadOnly(personForm.isReadOnly());
					
					motherNameTextField.setNullRepresentation("");
					motherNameTextField.setNullSettingAllowed(true);
					
					if (isModelStudent() && isUserStudent())
						motherNameTextField.addValidator(notNullValidator);
					
					return motherNameTextField;
				}
				else if (propertyId.equals("dateOfBirth") && mode==ViewMode.Full && (!isUserStudent() || isModelSelf()))
				{
					dateOfBirthDateField = new PopupDateField(getLocalizedString("PERSON_DATE_OF_BIRTH_CAPTION"));
					
					dateOfBirthDateField.setWidth("100%");
					dateOfBirthDateField.setReadOnly(personForm.isReadOnly());
					dateOfBirthDateField.setResolution(DateField.RESOLUTION_DAY);
					
					if (isModelStudent() && isUserStudent())
						dateOfBirthDateField.addValidator(notNullValidator);
					
					return dateOfBirthDateField;
				}
				else if (propertyId.equals("gender") && mode==ViewMode.Full)
				{
					genderComboBox = new EnumComboBox(getLocalizedString("PERSON_GENDER_CAPTION"), Gender.class); 
					genderComboBox.setWidth("100%");
					
					genderComboBox.setTextInputAllowed(false);
					genderComboBox.setReadOnly(personForm.isReadOnly());
					genderComboBox.setNullSelectionAllowed(false);
					
					genderComboBox.addValidator(notNullValidator);
					
					return genderComboBox;
				}
				else if (propertyId.equals("notes") && mode == ViewMode.Full &&
						!isUserStudent())
				{
					notesTextField = new TextField(getLocalizedString("PERSON_NOTES_CAPTION"));
					
					notesTextField.setWidth("100%");
					notesTextField.setHeight("65px");
					
					notesTextField.setNullRepresentation("");
					notesTextField.setNullSettingAllowed(true);
					
					notesTextField.setReadOnly(personForm.isReadOnly());
					
					return notesTextField;
				}
				else if (propertyId.equals("position") && mode == ViewMode.Full && !isUserStudent())
				{
					positionTextField = new TextField();
					positionTextField.setCaption(getLocalizedString("POSITION_CAPTION"));
					positionTextField.setWidth("100%");
					
					positionTextField.setNullRepresentation("");
					positionTextField.setNullSettingAllowed(true);
					
					positionTextField.setReadOnly(personForm.isReadOnly());
					
					return positionTextField;
				}
				else if (propertyId.equals("faxNumber") && mode == ViewMode.Full && !isUserStudent())
				{
					faxNumberTextField = new TextField();
					faxNumberTextField.setCaption(getLocalizedString("FAX_NUMBER_CAPTION"));
					faxNumberTextField.setWidth("100%");
					
					faxNumberTextField.setNullRepresentation("");
					
					faxNumberTextField.setReadOnly(personForm.isReadOnly());
					
					return faxNumberTextField;
				}
				else if (propertyId.equals("salutation") && mode == ViewMode.Full && !isUserStudent())
				{
					salutationTextField = new TextField();
					
					salutationTextField.setCaption(getLocalizedString("SALUTATION_CAPTION"));
					salutationTextField.setDescription(getLocalizedString("SALUTATION_DESCRIPTION"));
					salutationTextField.setWidth("100%");
					
					salutationTextField.setNullRepresentation("");
					salutationTextField.setNullSettingAllowed(true);
					
					salutationTextField.setReadOnly(personForm.isReadOnly());
					
					return salutationTextField;
				}
				else if (propertyId.equals("rank") && !isUserStudent())
				{
					professorRankField = new TextField();

					professorRankField.setCaption(getLocalizedString("PROFESSOR_RANK_CAPTION"));
					
					professorRankField.setNullRepresentation("");
					professorRankField.setNullSettingAllowed(true);
					professorRankField.setReadOnly(personForm.isReadOnly());
					
					professorRankField.setWidth("100%");
					
					return professorRankField;
				}
				/*
				 * Replace with combo box below.
				 * 
				else if (propertyId.equals("division"))
				{
					FacultyUser facultyUser = (FacultyUser)getModel().getBean();
					
					divisionPickerField = new DivisionPickerField(facultyUser.getDepartment());
					
					if (isUserStudent() || facultyUser.getDepartment() == null) 
						divisionPickerField.setReadOnly(true);
					
					divisionPickerField.setWidth("100%");
					divisionPickerField.setCaption(getLocalizedString("DIVISION_CAPTION"));
					
					if (isUserStudent())
						divisionPickerField.setBrowseEnabled(false);
					
					return divisionPickerField;
				}
				*/
				else if (propertyId.equals("active") && mode == ViewMode.Full)
				{
					activeCheckBox = new CheckBox();
					activeCheckBox.setCaption(getLocalizedString("ACTIVE_CAPTION"));
					activeCheckBox.setWidth("100%");
					
					return activeCheckBox;
				}
				else if (propertyId.equals("preferredLanguage") && !isUserStudent() && mode == ViewMode.Full)
				{
					preferredLanguageComboBox = new LanguageComboBox();
					
					preferredLanguageComboBox.setCaption(getLocalizedString("PREFERRED_LANGUAGE_CAPTION"));
					
					preferredLanguageComboBox.setWidth("100%");
					preferredLanguageComboBox.setTextInputAllowed(false);
					preferredLanguageComboBox.setNullSelectionAllowed(false);
					
					return preferredLanguageComboBox;
				}
				else if (mode == ViewMode.Full && propertyId.equals("division") && !isModelStudent())
				{
					divisionComboBox = new ComboBox();
					
					divisionComboBox.setCaption(getLocalizedString("DIVISION_CAPTION"));
					
					divisionComboBox.setWidth("100%");
					
					divisionComboBox.setNullSelectionAllowed(true);
					divisionComboBox.setTextInputAllowed(false);
					
					divisionComboBox.setItemCaptionMode(ComboBox.ITEM_CAPTION_MODE_PROPERTY);
					
					divisionComboBox.setItemCaptionPropertyId("name");
					
					// If there is a 'division' property, we know it is an FacultyUser.
					FacultyUser facultyUser = (FacultyUser)getModel().getBean();
					
					divisionComboBox.setContainerDataSource(
							accessCheck.getDivisionsContainer(facultyUser));
					
					divisionComboBox.setReadOnly(!accessCheck.canBrowseDivisions());
					
					return divisionComboBox;
				}
				else if (mode == ViewMode.Full && propertyId.equals("department") && !isModelStudent())
				{
					departmentComboBox = new ComboBox();
					
					departmentComboBox.setCaption(getLocalizedString("DEPARTMENT_CAPTION"));
					
					departmentComboBox.setWidth("100%");
					
					departmentComboBox.setNullSelectionAllowed(false);
					departmentComboBox.setTextInputAllowed(false);
					
					departmentComboBox.setItemCaptionMode(ComboBox.ITEM_CAPTION_MODE_PROPERTY);
					
					departmentComboBox.setItemCaptionPropertyId("name");
					
					// If there is a 'department' property, we know it is an AuthenticatedUser.
					AuthenticatedUser authenticatedUser = (AuthenticatedUser)getModel().getBean();

					departmentComboBox.setContainerDataSource(
							accessCheck.getDepartmentsContainer(authenticatedUser));
					
					departmentComboBox.addListener(new Property.ValueChangeListener()
					{
						@Override
						public void valueChange(ValueChangeEvent event)
						{
							if (divisionComboBox != null)
							{
								Department department = (Department)departmentComboBox.getValue();
								
								divisionComboBox.setContainerDataSource(accessCheck.getDivisionsContainer(department));
							}
						}
					});
					
					departmentComboBox.setReadOnly(!accessCheck.canBrowseDepartments());
					
					return departmentComboBox;
				}
				
				return null;
			}
		});
		
	}

	@Override
	public boolean isDataValid()
	{
		return this.personForm.isValid();
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout()
	{
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// personForm
		personForm = new PersonForm();
		personForm.setCaption("Στοιχεία χρήστη");
		personForm.setImmediate(false);
		personForm.setWidth("100.0%");
		personForm.setHeight("-1px");
		mainLayout.addComponent(personForm);
		
		return mainLayout;
	}

	@Override
	public void discardChanges()
	{
		this.personForm.discard();
	}

	@Override
	public void commitChangesToModel()
	{
		this.personForm.commit();
	}

	public ViewMode getMode() {
		return mode;
	}

	public void setMode(ViewMode mode) {
		this.mode = mode;
	}

	public Orientation getOrientation() {
		return orientation;
	}

	public void setOrientation(Orientation orientation) {
		this.orientation = orientation;
	}

	@Override
	public void setReadOnly(boolean readOnly) 
	{
		super.setReadOnly(readOnly);
		this.personForm.setReadOnly(readOnly);
	}

	@Override
	public void setViewFullyWritable(boolean isWritable) 
	{
		this.isFullyWritable = isWritable;
	}

	@Override
	public boolean isViewFullyWritable() 
	{
		return this.isFullyWritable;
	}
	
	private boolean isModelStudent()
	{
		if (getModel() != null)
		{
			return getModel().getBean() instanceof Student;
		}
		else
		{
			return false;
		}
	}
	
	private boolean isModelSelf()
	{
		if (getModel() != null)
		{
			return getModel().getBean() == getContext().getSession().getAuthenticatedUser();
		}
		
		return false;
	}
}
