package softeng.coop.ui.composites;

import java.util.Locale;
import java.util.Vector;

import softeng.coop.dataaccess.Category;
import softeng.coop.dataaccess.CoOp;
import softeng.coop.dataaccess.FacultyUser;
import softeng.coop.dataaccess.JobPosting;
import softeng.coop.dataaccess.Location;
import softeng.coop.dataaccess.Registration;
import softeng.coop.ui.ICoopContext;
import softeng.coop.ui.data.MultilingualValidationForm;
import softeng.coop.ui.viewdefinitions.IRegistrationPreferencesView;
import softeng.ui.vaadin.data.NullableNestedProperty;
import softeng.ui.vaadin.mvp.IListener;
import softeng.ui.vaadin.mvp.IView;
import softeng.ui.vaadin.mvp.ModelEvent;
import softeng.ui.vaadin.mvp.Presenter;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.util.BeanItem;
import com.vaadin.ui.Component;
import com.vaadin.ui.Field;
import com.vaadin.ui.FormFieldFactory;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Table.TableDragMode;

public class RegistrationPreferencesComponent 
	extends CoopComponent<BeanItem<Registration>> 
	implements IRegistrationPreferencesView
{
	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private StudentPrefencesForm form;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = 1L;

	private PreferredLocationsTableComponent preferredLocationsTable = 
		new PreferredLocationsTableComponent();
	
	private PreferredJobPostingsTableComponent preferredJobPostingsTable = 
		new PreferredJobPostingsTableComponent();
	
	private PreferredCategoriesTableComponent preferredCategoriesTable = 
		new PreferredCategoriesTableComponent();
	
	private TextArea workExperienceTextArea = new TextArea();
	
	private TextArea notesTextArea = new TextArea();
	
	private CoOp coop;
	
	private static Vector<String> propertyIds = createPropertyIds();
	
	public class StudentPrefencesForm extends MultilingualValidationForm<Registration>
	{
		private static final long serialVersionUID = 1L;

		public StudentPrefencesForm() 
		{
			super(Registration.class);
		}
		
	}

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public RegistrationPreferencesComponent() 
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}
	
	private static Vector<String> createPropertyIds()
	{
		Vector<String> list = new Vector<String>();
		
		list.add("preferredLocations");
		list.add("preferredJobPostings");
		list.add("preferredCategories");
		
		list.add("student.workExperience");
		list.add("student.notes");

		return list;
	}

	@Override
	protected Presenter<BeanItem<Registration>, ICoopContext, 
		? extends IView<BeanItem<Registration>, 
				ICoopContext>> supplyPresenter() 
	{
		return null;
	}

	@Override
	public void dataBind() 
	{
		if (this.getModel() == null)
		{
			coop = null;
		}
		else
		{
			coop = getModel().getBean().getCoop();
			
			if (this.getContext().getSession().getAuthenticatedUser() instanceof FacultyUser)
			{
				this.getModel().addItemProperty(
						"student.workExperience", 
						new NullableNestedProperty(this.getModel().getBean(), "student.workExperience"));
				
				this.getModel().addItemProperty(
						"student.notes", 
						new NullableNestedProperty(this.getModel().getBean(), "student.notes"));
			}
			
		}
		
		form.setItemDataSource(this.getModel(), propertyIds);
	}

	@SuppressWarnings("serial")
	@Override
	protected void setupUI() 
	{
		super.setupUI();
		
		this.form.setWriteThrough(false);
		this.form.setImmediate(true);
		this.form.setCaption(getLocalizedString("PREFERENCES_CAPTION"));
		
		this.form.setFormFieldFactory(new FormFieldFactory() 
		{	
			@Override
			public Field createField(Item item, Object propertyId, Component uiContext) 
			{
				if (propertyId.equals("preferredLocations") && coop.isAllowLocationPreferences())
				{
					//preferredLocationTable = new PreferredLocationTableComponent();
					
					preferredLocationsTable.setReadOnly(isReadOnly());
					preferredLocationsTable.setDragMode(isReadOnly() ? TableDragMode.NONE : TableDragMode.ROW);

					if (!isReadOnly())
					{
						preferredLocationsTable.setDropHandler(preferredLocationsTable.new ReorderDropHandler());
						preferredLocationsTable.setDescription(getLocalizedString("LOCATION_TABLE_DRAG_DESCRIPTION"));
					}
					else
					{
						preferredCategoriesTable.setDropHandler(null);
						preferredLocationsTable.setDescription(null);
					}
					
					preferredLocationsTable.setCaption(getLocalizedString("LOCATION_TABLE_CAPTION"));
					preferredLocationsTable.setWidth("100%");
					preferredLocationsTable.setEditVisible(false);

					preferredLocationsTable.setParentModel(getModel().getBean());
					
					return preferredLocationsTable;
				}
				else if (propertyId.equals("preferredJobPostings") && coop.isAllowJobPostingsPreferences())
				{
					//preferredJobPostingTable = new PreferredJobPostingTableComponent();
					
					preferredJobPostingsTable.setReadOnly(isReadOnly());
					preferredJobPostingsTable.setDragMode(isReadOnly() ? TableDragMode.NONE : TableDragMode.ROW);

					if (!isReadOnly()) 
					{
						preferredJobPostingsTable.setDropHandler(preferredJobPostingsTable.new ReorderDropHandler());
						preferredJobPostingsTable.setDescription(getLocalizedString("JOBPOSTING_TABLE_DRAG_DESCRIPTION"));
					}
					else
					{
						preferredJobPostingsTable.setDropHandler(null);
						preferredJobPostingsTable.setDescription(null);
					}
					
					preferredJobPostingsTable.setCaption(getLocalizedString("JOBPOSTING_TABLE_CAPTION"));
					
					preferredJobPostingsTable.setWidth("100%");
					preferredJobPostingsTable.setEditVisible(false);

					preferredJobPostingsTable.setParentModel(getModel().getBean());
					
					return preferredJobPostingsTable;
				}
				else if (propertyId.equals("preferredCategories") && coop.isAllowCategoryPreferences())
				{
					//preferredJobCategoryTable = new PreferredJobCategoryTableComponent();
					
					preferredCategoriesTable.setReadOnly(isReadOnly());
					preferredCategoriesTable.setDragMode(isReadOnly() ? TableDragMode.NONE : TableDragMode.ROW);
					
					if (!isReadOnly())
					{
						preferredCategoriesTable.setDropHandler(preferredCategoriesTable.new ReorderDropHandler());
						preferredCategoriesTable.setDescription(getLocalizedString("CATEGORY_TABLE_DRAG_DESCRIPTION"));
					}
					else
					{
						preferredCategoriesTable.setDropHandler(null);
						preferredCategoriesTable.setDescription(null);
					}
					
					preferredCategoriesTable.setCaption(getLocalizedString("CATEGORY_TABLE_CAPTION"));
					preferredCategoriesTable.setWidth("100%");
					preferredCategoriesTable.setEditVisible(false);
					
					preferredCategoriesTable.setParentModel(getModel().getBean());
					
					return preferredCategoriesTable;
				}
				else if (propertyId.equals("student.workExperience"))
				{
					workExperienceTextArea.setWidth("100%");
					
					workExperienceTextArea.setCaption(getLocalizedString("WORK_EXPERIENCE_CAPTION"));
					
					workExperienceTextArea.setNullRepresentation("");
					workExperienceTextArea.setNullSettingAllowed(true);
					
					workExperienceTextArea.setReadOnly(true);
					
					return workExperienceTextArea;
				}
				else if (propertyId.equals("student.notes"))
				{
					notesTextArea.setWidth("100%");
					
					notesTextArea.setCaption(getLocalizedString("NOTES_CAPTION"));
					
					notesTextArea.setNullRepresentation("");
					notesTextArea.setNullSettingAllowed(true);
					
					notesTextArea.setReadOnly(true);
					
					return notesTextArea;
				}
				
				return null;
			}
		});
	}



	@Override
	protected void setupLocalizedCaptions(Locale locale) 
	{
		super.setupLocalizedCaptions(locale);
		
		this.form.setCaption(getLocalizedString("PREFERENCES_CAPTION"));
		
		if (this.preferredCategoriesTable != null)
			this.preferredCategoriesTable.setCaption(getLocalizedString("CATEGORY_TABLE_CAPTION"));
		
		if (this.preferredJobPostingsTable != null)
			this.preferredJobPostingsTable.setCaption(getLocalizedString("JOBPOSTING_TABLE_CAPTION"));
		
		if (preferredLocationsTable != null)
			this.preferredLocationsTable.setCaption(getLocalizedString("LOCATION_TABLE_CAPTION"));
		
		if (workExperienceTextArea != null)
			workExperienceTextArea.setCaption(getLocalizedString("WORK_EXPERIENCE_CAPTION"));
		
		if (notesTextArea != null)
			notesTextArea.setCaption(getLocalizedString("NOTES_CAPTION"));
	}


	@Override
	public boolean isDataValid() 
	{
		return this.form.isValid();
	}


	@Override
	public void discardChanges() 
	{
		this.form.discard();
		
	}

	@Override
	public void commitChangesToModel() 
	{
		this.form.commit();
		
	}

	@Override
	public void setHorizontal(boolean horizontal) 
	{
		if (horizontal)
		{
			HorizontalLayout newLayout = new HorizontalLayout();
			newLayout.setSpacing(true);
			newLayout.setWidth("100%");
			this.form.setLayout(newLayout);
		}
		else
		{
			VerticalLayout newLayout = new VerticalLayout();
			newLayout.setSpacing(true);
			newLayout.setWidth("100%");
			this.form.setLayout(newLayout);
		}
		
	}

	@Override
	public void setReadOnly(boolean readOnly) 
	{
		super.setReadOnly(readOnly);
		
		this.form.setReadOnly(readOnly);
		
		if (this.preferredCategoriesTable != null)
		{
			this.preferredCategoriesTable.setReadOnly(readOnly);
			this.preferredCategoriesTable.setDragMode(readOnly ? TableDragMode.NONE : TableDragMode.ROW);
			
			if (!readOnly)
			{
				preferredCategoriesTable.setDropHandler(preferredCategoriesTable.new ReorderDropHandler());
				preferredCategoriesTable.setDescription(getLocalizedString("CATEGORY_TABLE_DRAG_DESCRIPTION"));
			}
			else
			{
				preferredCategoriesTable.setDropHandler(null);
				preferredCategoriesTable.setDescription(null);
			}
		}
		
		if (this.preferredJobPostingsTable != null)
		{
			this.preferredJobPostingsTable.setReadOnly(readOnly);
			this.preferredJobPostingsTable.setDragMode(readOnly ? TableDragMode.NONE : TableDragMode.ROW);
			
			if (!readOnly) 
			{
				preferredJobPostingsTable.setDropHandler(preferredJobPostingsTable.new ReorderDropHandler());
				preferredJobPostingsTable.setDescription(getLocalizedString("JOBPOSTING_TABLE_DRAG_DESCRIPTION"));
			}
			else
			{
				preferredJobPostingsTable.setDropHandler(null);
				preferredJobPostingsTable.setDescription(null);
			}
		}
		
		if (preferredLocationsTable != null)
		{
			this.preferredLocationsTable.setReadOnly(readOnly);
			this.preferredLocationsTable.setDragMode(readOnly ? TableDragMode.NONE : TableDragMode.ROW);
			
			if (!readOnly)
			{
				preferredLocationsTable.setDropHandler(preferredLocationsTable.new ReorderDropHandler());
				preferredLocationsTable.setDescription(getLocalizedString("LOCATION_TABLE_DRAG_DESCRIPTION"));
			}
			else
			{
				preferredCategoriesTable.setDropHandler(null);
				preferredLocationsTable.setDescription(null);
			}
		}
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// form
		form = new StudentPrefencesForm();
		form.setCaption("Προτιμήσεις Φοιτητή");
		form.setImmediate(false);
		form.setWidth("100.0%");
		form.setHeight("-1px");
		mainLayout.addComponent(form);
		
		return mainLayout;
	}

	@Override
	public BeanItem<Location> getSelectedPreferredLocation()
	{
		return preferredLocationsTable.getSelectedItem();
	}

	@Override
	public BeanItem<Category> getSelectedPreferredCategory()
	{
		return preferredCategoriesTable.getSelectedItem();
	}

	@Override
	public BeanItem<JobPosting> getSelectedPreferredJobPosting()
	{
		return preferredJobPostingsTable.getSelectedItem();
	}

	@Override
	public void addSelectedPreferredLocationChangeListener(IListener<ModelEvent<Location>> listener)
	{
		preferredLocationsTable.addSelectedChangeListener(listener);
	}

	@Override
	public void removeSelectedPreferredLocationChangeListener(IListener<ModelEvent<Location>> listener)
	{
		preferredLocationsTable.removeSelectedChangeListener(listener);
	}

	@Override
	public void addSelectedPreferredCategoryChangeListener(IListener<ModelEvent<Category>> listener)
	{
		preferredCategoriesTable.addSelectedChangeListener(listener);
	}

	@Override
	public void removeSelectedPreferredCategoryChangeListener(IListener<ModelEvent<Category>> listener)
	{
		preferredCategoriesTable.removeSelectedChangeListener(listener);
	}

	@Override
	public void addSelectedPreferredJobPostingChangeListener(IListener<ModelEvent<JobPosting>> listener)
	{
		preferredJobPostingsTable.addSelectedChangeListener(listener);
	}

	@Override
	public void removeSelectedPreferredJobPostingChangeListener(IListener<ModelEvent<JobPosting>> listener)
	{
		preferredJobPostingsTable.removeSelectedChangeListener(listener);
	}
}
