package softeng.coop.ui.composites;

import java.util.Locale;

import softeng.coop.dataaccess.Student;
import softeng.coop.ui.ICoopContext;
import softeng.coop.ui.presenters.StudentPreferencesCardPresenter;
import softeng.coop.ui.viewdefinitions.IOkCancelView;
import softeng.coop.ui.viewdefinitions.IRegistrationPreferencesView;
import softeng.coop.ui.viewdefinitions.IStudentPreferencesCardView;
import softeng.coop.ui.viewdefinitions.viewmodels.OkCancelViewModel;
import softeng.ui.vaadin.mvp.IView;
import softeng.ui.vaadin.mvp.Presenter;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItem;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.VerticalLayout;

public class StudentPreferencesCardComponent 
	extends CoopComponent<BeanItem<Student>>
	implements IStudentPreferencesCardView
{
	private static final long serialVersionUID = 1L;

	@AutoGenerated
	private VerticalLayout mainLayout;
	
	@AutoGenerated
	private OkCancelComponent okCancelComponent;
	
	@AutoGenerated
	private RegistrationPreferencesComponent registrationPreferencesComponent;
	
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public StudentPreferencesCardComponent()
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}
	
	@Override
	protected void setupLocalizedCaptions(Locale locale) 
	{
		super.setupLocalizedCaptions(locale);
		
		
	}

	@Override
	protected Presenter<BeanItem<Student>, ICoopContext, ? extends IView<BeanItem<Student>, ICoopContext>> 
		supplyPresenter() 
	{
		
		return new StudentPreferencesCardPresenter(this);
	}

	@Override
	public void dataBind() 
	{
		
		this.okCancelComponent.setModel(OkCancelViewModel.Save);
		this.okCancelComponent.dataBind();
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// studentPreferencesComponent
		registrationPreferencesComponent = new RegistrationPreferencesComponent();
		registrationPreferencesComponent.setImmediate(false);
		registrationPreferencesComponent.setWidth("100.0%");
		registrationPreferencesComponent.setHeight("-1px");
		mainLayout.addComponent(registrationPreferencesComponent);
		
		// okCancelComponent
		okCancelComponent = new OkCancelComponent();
		okCancelComponent.setImmediate(false);
		okCancelComponent.setWidth("-1px");
		okCancelComponent.setHeight("-1px");
		mainLayout.addComponent(okCancelComponent);
		mainLayout.setComponentAlignment(okCancelComponent, new Alignment(10));
		
		return mainLayout;
	}

	@Override
	public void commitChangesToModel()
	{
		registrationPreferencesComponent.commitChangesToModel();
	}

	@Override
	public void discardChanges()
	{
		registrationPreferencesComponent.discardChanges();
	}

	@Override
	public IOkCancelView getOkCancelView() 
	{
		return this.okCancelComponent;
	}

	@Override
	public boolean isDataValid() 
	{
		return registrationPreferencesComponent.isDataValid();
	}

	@Override
	public IRegistrationPreferencesView getRegistrationPreferencesView()
	{
		return registrationPreferencesComponent;
	}

}
