package softeng.coop.ui.composites;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.Vector;

import softeng.coop.dataaccess.Category;
import softeng.coop.dataaccess.CoOp;
import softeng.coop.dataaccess.Group;
import softeng.coop.dataaccess.Job;
import softeng.coop.dataaccess.JobPosting;
import softeng.coop.dataaccess.Location;
import softeng.coop.dataaccess.Registration;
import softeng.coop.ui.ICoopContext;
import softeng.coop.ui.composites.TableComponent.ColumnSpecification;
import softeng.coop.ui.data.DataItem;
import softeng.coop.ui.data.DataItemContainer;
import softeng.coop.ui.data.GroupMembersColumnGenerator;
import softeng.coop.ui.data.MultilingualValidationForm;
import softeng.coop.ui.presenters.TwinSelectTablePresenter;
import softeng.coop.ui.viewdefinitions.ITwinSelectTableComponentView;
import softeng.ui.vaadin.mvp.IListener;
import softeng.ui.vaadin.mvp.IView;
import softeng.ui.vaadin.mvp.IViewListener;
import softeng.ui.vaadin.mvp.ModelEvent;
import softeng.ui.vaadin.mvp.Presenter;
import softeng.ui.vaadin.mvp.ViewEvent;
import softeng.ui.vaadin.mvp.ViewEventSubscription;
import softeng.ui.vaadin.ui.SortableDynamicTable;

import com.vaadin.addon.beanvalidation.BeanValidationForm;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Item;
import com.vaadin.data.Property;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.util.BeanItem;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Component;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Field;
import com.vaadin.ui.FormFieldFactory;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class TwinSelectTableComponent
	extends CoopComponent<CoOp>
	implements ITwinSelectTableComponentView
{
	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private HorizontalLayout detaillHorizontalLayout;

	@AutoGenerated
	private JobDetailsComponent jobDetailsComponent;

	@AutoGenerated
	private GroupDetailsComponent groupDetailsComponent;

	@AutoGenerated
	private JobPostingComponent jobPostingDetailsComponent;

	@AutoGenerated
	private HorizontalLayout tableHorizontalLayout;

	@AutoGenerated
	private VerticalLayout jobsTableVerticalLayout;

	@AutoGenerated
	private CheckBox fullJobViewCheckBox;

	@AutoGenerated
	private SortableDynamicTable assignedJobTable;

	@AutoGenerated
	private VerticalLayout buttonsVerticalLayout;

	@AutoGenerated
	private PopupDateField startDatePopupDateField;

	@AutoGenerated
	private Button removeAssignmentButton;

	@AutoGenerated
	private Button assignJobButton;

	@AutoGenerated
	private VerticalLayout groupAvailableVerticalLayout;

	@AutoGenerated
	private FilterOptionsForm groupFilterOptionsForm;

	@AutoGenerated
	private SortableDynamicTable groupAvailableTable;

	@AutoGenerated
	private VerticalLayout jobPostingsVerticalLayout;

	@AutoGenerated
	private FilterOptionsForm jobPostingFilterOptionsForm;

	@AutoGenerated
	private SortableDynamicTable jobPostingTable;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = 1L;
	
	private ViewEventSubscription<CoOp, ICoopContext, ITwinSelectTableComponentView> addingJobEvent =
		new ViewEventSubscription<CoOp, ICoopContext, ITwinSelectTableComponentView>();
	private ViewEventSubscription<CoOp, ICoopContext, ITwinSelectTableComponentView> deletingJobEvent =
		new ViewEventSubscription<CoOp, ICoopContext, ITwinSelectTableComponentView>();
	
	
	private static class FilterOptionsForm
		extends MultilingualValidationForm<FilterOptions>
	{

		public FilterOptionsForm() 
		{
			super(FilterOptions.class);
		}
		
	}
	
	private BeanItem<FilterOptions> jobPostingFilterOptionsItem =  
		new BeanItem<ITwinSelectTableComponentView.FilterOptions>(new FilterOptions());
	private BeanItem<FilterOptions> groupFilterOptionsItem = 
		new BeanItem<ITwinSelectTableComponentView.FilterOptions>(new FilterOptions());
	
	private static ArrayList<String> jobPostingsFilterPropertyIds = 
		createJobPostingsFilterPropertyIds();
	
	private static ArrayList<String> groupsFilterPropertyIds =
		createGroupsFilterPropertyIds();
	
	private Vector<ColumnSpecification> jobPostingSpecifications = new Vector<ColumnSpecification>();
	private Vector<String> jobPostingVisibleColumns;
	private Vector<ColumnSpecification> groupSpecifications = new Vector<ColumnSpecification>();
	private Vector<String> groupVisibleColumns = new Vector<String>();
	private Vector<ColumnSpecification> jobSpecifications = new Vector<ColumnSpecification>();
	private Vector<String> jobVisibleColumns;
	
	private DataItemContainer<JobPosting> jobPostingContainer;
	private DataItemContainer<Group> groupContainer;
	private DataItemContainer<Job> jobContainer;
	
	private List<JobPosting> jobPostingsWithRemainingSeats = new Vector<JobPosting>();
	private List<Group> coopGroups = new Vector<Group>();
	private List<Job> setOfAssignedJobs = new Vector<Job>();
	
	private LocationPickerField jobPostingLocationPickerField;
	private LocationPickerField groupLocationPickerField;
	private CategoryPickerField jobPostingCategoryPickerField;
	private CategoryPickerField groupCategoryPickerField;
	private CheckBox onlyQualifiedForAssignmentCheckBox; 

	
	private static ArrayList<String> createJobPostingsFilterPropertyIds()
	{
		ArrayList<String> list = new ArrayList<String>();
		
		list.add("locationFilter");
		list.add("categoryFilter");
		
		return list;
	}
	
	private static ArrayList<String> createGroupsFilterPropertyIds()
	{
		ArrayList<String> list = new ArrayList<String>();

		list.add("locationFilter");
		list.add("categoryFilter");
		list.add("qualifiedForAssignmentOnly");
		
		return list;
	}

	// Column generator for group priority.
	// Computes the mean of all priorities in the group's registrations.
	private static class PriorityColumnGenerator
		implements Table.ColumnGenerator
	{
		@Override
		public Object generateCell(Table source, Object itemId, Object columnId)
		{
			Group group = (Group)itemId;
			
			if (group == null) return null;
			
			int registrationsCount = 0;
			
			float priority = 0.0f;
			
			for (Registration registration : group.getRegistrations())
			{
				registrationsCount++;
				
				if (registration.getPriority() != null) priority += registration.getPriority();
			}
			
			if (registrationsCount > 0) priority /= (float)registrationsCount;
			
			return priority;
		}
	}
	
	private static class RemainingSeatsColumnGenerator
		implements Table.ColumnGenerator
	{

		@Override
		public Object generateCell(Table source, Object itemId, Object columnId)
		{
			JobPosting jobPosting = (JobPosting)itemId;
			
			if (jobPosting == null) return null;
			
			int remainingSeats = jobPosting.getSeatsNumber() - jobPosting.getJobs().size();
			
			return remainingSeats;
		}
	
	}
	
	public class GroupForm extends BeanValidationForm<Group>
	{
		public GroupForm() 
		{
			super(Group.class);
		}	
	}
	
	public class StudentPreferencesForm extends BeanValidationForm<Registration>
	{
		public StudentPreferencesForm() 
		{
			super(Registration.class);
		}	
	}
	
	public TwinSelectTableComponent() 
	{	
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		//setup column specifications and visible columns for JobPostings Table
		// Vaadin Hack: In order for the column to be sortable, it has to be named an existing property.
		jobPostingVisibleColumns = new Vector<String>();
		jobPostingVisibleColumns.add("name");
		jobPostingVisibleColumns.add("id");
		jobPostingVisibleColumns.add("company.name");
		jobPostingVisibleColumns.add("description");

		ColumnSpecification nameSpecification = new ColumnSpecification("name", "JOB_POSTING_TABLE_NAME_CAPTION");
		jobPostingSpecifications.add(nameSpecification);

		ColumnSpecification remainingSeatsSpecification = 
			new ColumnSpecification("id", "JOB_POSTING_TABLE_REMAININGSEATS_CAPTION", new RemainingSeatsColumnGenerator());
		jobPostingSpecifications.add(remainingSeatsSpecification);
		this.jobPostingTable.addGeneratedColumn("id", remainingSeatsSpecification.getColumnGenerator());
		
		ColumnSpecification companySpecification = new ColumnSpecification("company.name", "JOB_POSTING_TABLE_COMPANY_CAPTION");
		jobPostingSpecifications.add(companySpecification);
		
		ColumnSpecification descriptionSpecification = new ColumnSpecification("description", "JOB_POSTING_TABLE_DESCRIPTION_CAPTION");
		jobPostingSpecifications.add(descriptionSpecification);
		
		//setup column specifications and visible columns for Groups Table
		/* Remove static display of group comments and replace it by dynamic members listing */
//		ColumnSpecification commentsSpecification = new ColumnSpecification("comments", "GROUP_TABLE_NAME_CAPTION");
//		groupSpecifications.add(commentsSpecification);
//		groupVisibleColumns.add("comments");

		// Group members and priority generated columns follow.
		// Vaadin Hack: In order for the column to be sortable, it has to be named an existing property.
		ColumnSpecification groupMembersSpecification = new ColumnSpecification("members", "GROUP_TABLE_NAME_CAPTION", new GroupMembersColumnGenerator());
		groupSpecifications.add(groupMembersSpecification);
		groupVisibleColumns.add("members");
		groupAvailableTable.addGeneratedColumn("members", groupMembersSpecification.getColumnGenerator());
		
		ColumnSpecification prioritySpecification = new ColumnSpecification("priority", "GROUP_PRIORITY_CAPTION", new PriorityColumnGenerator());
		groupSpecifications.add(prioritySpecification);
		groupVisibleColumns.add("priority");
		groupAvailableTable.addGeneratedColumn("priority", prioritySpecification.getColumnGenerator());
		
		//setup column specifications and visible columns for Jobs Table
		/* Remove static display of group comments and replace it by dynamic members listing */
//		ColumnSpecification groupNameSpecification = new ColumnSpecification("group.comments", "JOB_TABLE_GROUPNAME_CAPTION");
		jobVisibleColumns = new Vector<String>();
		
		jobVisibleColumns.add("group.comments");
		jobVisibleColumns.add("jobPosting.name");
		jobVisibleColumns.add("jobPosting.company.name");
		
		ColumnSpecification groupNameSpecification = new ColumnSpecification("group.comments", "JOB_TABLE_GROUPNAME_CAPTION", new GroupMembersColumnGenerator());
		jobSpecifications.add(groupNameSpecification);
		assignedJobTable.addGeneratedColumn("group.comments", groupNameSpecification.getColumnGenerator());
		ColumnSpecification jobPostingName = new ColumnSpecification("jobPosting.name", "JOB_TABLE_JOBNAME_CAPTION");
		jobSpecifications.add(jobPostingName);
		ColumnSpecification companyName = new ColumnSpecification("jobPosting.company.name", "JOB_TABLE_COMPANY_CAPTION");
		jobSpecifications.add(companyName);
		
		// Listen to selection of group members preferences.
		
		groupDetailsComponent.getRegistrationPreferencesComponent().addSelectedPreferredCategoryChangeListener(new IListener<ModelEvent<Category>>()
		{
			@Override
			public void onEvent(ModelEvent<Category> event)
			{
				onSelectedPreferredCategoryChange(event);
			}
		});
		
		groupDetailsComponent.getRegistrationPreferencesComponent().addSelectedPreferredJobPostingChangeListener(new IListener<ModelEvent<JobPosting>>()
		{
			@Override
			public void onEvent(ModelEvent<JobPosting> event)
			{
				onSelectedPreferredJobPostingChange(event);
			}
		});
		
		groupDetailsComponent.getRegistrationPreferencesComponent().addSelectedPreferredLocationChangeListener(new IListener<ModelEvent<Location>>()
		{
			@Override
			public void onEvent(ModelEvent<Location> event)
			{
				onSelectedPreferredLocationChanged(event);
			}
		});
		
	}
	
	protected void onSelectedPreferredLocationChanged(ModelEvent<Location> event)
	{
		if (jobPostingLocationPickerField != null)
		{
			jobPostingLocationPickerField.setValue(event.getModel());
		}
		
		updateSelectedPreferredJobPostingChange();
	}

	protected void onSelectedPreferredJobPostingChange(ModelEvent<JobPosting> event)
	{
		jobPostingTable.setValue(event.getModel());
		
		if (event.getModel() != null)
		{
			jobPostingTable.setCurrentPageFirstItemId(event.getModel());
		}
	}

	protected void onSelectedPreferredCategoryChange(ModelEvent<Category> event)
	{
		if (jobPostingCategoryPickerField != null)
		{
			jobPostingCategoryPickerField.setValue(event.getModel());
		}
		
		updateSelectedPreferredJobPostingChange();
	}
	
	private void updateSelectedPreferredJobPostingChange()
	{
		BeanItem<JobPosting> preferredJobPostingItem = 
			groupDetailsComponent.getRegistrationPreferencesComponent().getSelectedPreferredJobPosting();
		
		if (preferredJobPostingItem != null)
		{
			JobPosting preferredJobPosting = preferredJobPostingItem.getBean();
			
			jobPostingTable.setValue(preferredJobPosting);
			jobPostingTable.setCurrentPageFirstItemId(preferredJobPosting);
		}
	}

	@Override
	protected void setupUI() 
	{
		super.setupUI();
		
		startDatePopupDateField.setResolution(DateField.RESOLUTION_DAY);
		
		this.jobPostingTable.setSelectable(true);
		this.jobPostingTable.setImmediate(true);
		
		this.groupAvailableTable.setSelectable(true);
		this.groupAvailableTable.setImmediate(true);
		
		this.assignedJobTable.setSelectable(true);
		this.assignedJobTable.setImmediate(true);
		
		this.fullJobViewCheckBox.setImmediate(true);
		this.fullJobViewCheckBox.setValue(false);
		
		assignJobButton.addListener(new ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) 
			{
				onAssignJob();
			}

		});
		
		removeAssignmentButton.addListener(new ClickListener() 
		{
			
			@Override
			public void buttonClick(ClickEvent event) 
			{
				onRemoveJob();
				
			}
		});
		
		//set listeners for the table selected values, so that to enable or disable the buttons
		assignedJobTable.addListener(new Property.ValueChangeListener() 
		{	
			@Override
			public void valueChange(ValueChangeEvent event) 
			{
				if(assignedJobTable.getValue() != null)
				{
					removeAssignmentButton.setEnabled(true);
					jobDetailsComponent.setModel(new DataItem<Job>(
							(Job) assignedJobTable.getValue(), 
							getContext().getSession().getJobsManager())
					);
					jobDetailsComponent.dataBind();
				}
				else
				{
					removeAssignmentButton.setEnabled(false);
					jobDetailsComponent.setModel(null);
					jobDetailsComponent.dataBind();
				}
			}
		});
		
		
		jobPostingTable.addListener(new Property.ValueChangeListener() 
		{	
			@Override
			public void valueChange(ValueChangeEvent event) 
			{
				if (jobPostingTable.getValue() != null && groupAvailableTable.getValue() != null)
					assignJobButton.setEnabled(true);
				else 
					assignJobButton.setEnabled(false);	
				
				if (jobPostingTable.getValue() != null)
				{
					jobPostingDetailsComponent.setModel(new DataItem<JobPosting>(
							(JobPosting) jobPostingTable.getValue(), 
							getContext().getSession().getBaseManager()));
					jobPostingDetailsComponent.dataBind();
					jobPostingDetailsComponent.setReadOnly(true);
				}
				else
				{
					jobPostingDetailsComponent.setModel(null);
					jobPostingDetailsComponent.dataBind();
				}
			}
		});
		
		groupAvailableTable.addListener(new Property.ValueChangeListener() 
		{	
			@Override
			public void valueChange(ValueChangeEvent event) 
			{
				if (jobPostingTable.getValue() != null && groupAvailableTable.getValue() != null)
					assignJobButton.setEnabled(true);
				else 
					assignJobButton.setEnabled(false);	
				
				groupDetailsComponent.setModel((Group) groupAvailableTable.getValue());
				groupDetailsComponent.dataBind();
			}
		});	
		
		fullJobViewCheckBox.addListener(new Property.ValueChangeListener() 
		{
			
			@Override
			public void valueChange(ValueChangeEvent event) 
			{
				if (fullJobViewCheckBox.getValue().equals(true))
				{
					detaillHorizontalLayout.setExpandRatio(jobPostingDetailsComponent, 0f);
					detaillHorizontalLayout.setExpandRatio(groupDetailsComponent, 0f);
					detaillHorizontalLayout.setExpandRatio(jobDetailsComponent, 1f);
				}
				else
				{
					detaillHorizontalLayout.setExpandRatio(jobPostingDetailsComponent, 33f);
					detaillHorizontalLayout.setExpandRatio(groupDetailsComponent, 33f);
					detaillHorizontalLayout.setExpandRatio(jobDetailsComponent, 34f);
				}
					
			}
		});
		
		jobPostingFilterOptionsForm.setFormFieldFactory(new FormFieldFactory()
		{
			
			@Override
			public Field createField(Item item, Object propertyId, Component uiContext) 
			{
				if (propertyId.equals("locationFilter"))
				{
					jobPostingLocationPickerField = new LocationPickerField();
					jobPostingLocationPickerField.setCaption(getLocalizedString("FILTER_OPTIONS_LOCATION_CAPTION"));
					jobPostingLocationPickerField.setWidth("100%");
					
					return jobPostingLocationPickerField;
				}
				else if (propertyId.equals("categoryFilter"))
				{
					jobPostingCategoryPickerField = new CategoryPickerField();
					jobPostingCategoryPickerField.setCaption(getLocalizedString("FILTER_OPTIONS_CATEGORY_CAPTION"));
					jobPostingCategoryPickerField.setWidth("100%");
					
					return jobPostingCategoryPickerField;
				}
				return null;
			}
		});
		
		groupFilterOptionsForm.setFormFieldFactory(new FormFieldFactory() 
		{
			
			@Override
			public Field createField(Item item, Object propertyId, Component uiContext) 
			{
				if (propertyId.equals("locationFilter"))
				{
					groupLocationPickerField = new LocationPickerField();
					groupLocationPickerField.setCaption(getLocalizedString("FILTER_OPTIONS_LOCATION_CAPTION"));
					groupLocationPickerField.setWidth("100%");
					
					return groupLocationPickerField;
				}
				else if (propertyId.equals("categoryFilter"))
				{
					groupCategoryPickerField = new CategoryPickerField();
					groupCategoryPickerField.setCaption(getLocalizedString("FILTER_OPTIONS_CATEGORY_CAPTION"));
					groupCategoryPickerField.setWidth("100%");
					
					return groupCategoryPickerField;
				}
				else if (propertyId.equals("qualifiedForAssignmentOnly"))
				{
					onlyQualifiedForAssignmentCheckBox = new CheckBox();
					onlyQualifiedForAssignmentCheckBox.setCaption(getLocalizedString("QUALIFIED_FOR_ASSIGNMENT_ONLY_CAPTION"));
					onlyQualifiedForAssignmentCheckBox.setWidth("100%");
					
					return onlyQualifiedForAssignmentCheckBox;
				}
				
				return null;
			}
		});
		
		jobPostingFilterOptionsForm.setImmediate(true);
		jobPostingFilterOptionsForm.setWriteThrough(true);
		jobPostingFilterOptionsForm.setItemDataSource(jobPostingFilterOptionsItem, jobPostingsFilterPropertyIds);
		
		groupFilterOptionsForm.setImmediate(true);
		groupFilterOptionsForm.setWriteThrough(true);
		groupFilterOptionsForm.setItemDataSource(groupFilterOptionsItem, groupsFilterPropertyIds);
	}
	
	
	private void onAssignJob() 
	{
		JobPosting selectedJobPosting = getSelectedJobPosting();
		
		if (groupAvailableTable.getValue()!= null && selectedJobPosting != null)
			addingJobEvent.fire(new ViewEvent<CoOp, ICoopContext, ITwinSelectTableComponentView>(this));

		if (selectedJobPosting.getSeatsNumber() <= selectedJobPosting.getJobs().size())
			jobPostingTable.setValue(null);
		
		groupAvailableTable.setValue(null);
	}
	
	private void onRemoveJob() 
	{
		if (assignedJobTable.getValue() != null)
			deletingJobEvent.fire(new ViewEvent<CoOp, ICoopContext, ITwinSelectTableComponentView>(this));

		assignedJobTable.setValue(null);
	}
	
	@Override
	protected Presenter<CoOp, ICoopContext, ? extends IView<CoOp, ICoopContext>> supplyPresenter() 
	{
		return new TwinSelectTablePresenter(this);
	}
	
	@Override
	public void dataBind() 
	{
		CoOp currentCoOp = this.getModel();
		
		if (currentCoOp == null) return;

		startDatePopupDateField.setValue(new Date());
		
		//bind all assigned Jobs
		bindJobs(currentCoOp);
		
	}

	
	private void bindJobs(CoOp currentCoOp) 
	{
		jobContainer =
			new DataItemContainer<Job>(
					Job.class, 
					setOfAssignedJobs,
					this.getContext().getSession().getJobsManager()
			);
		
		//add ids to be loaded
		jobContainer.addNestedContainerProperty("group.comments");
		jobContainer.addNestedContainerProperty("jobPosting.name");
		jobContainer.addNestedContainerProperty("jobPosting.company.name");
		
		jobContainer.setContainerPropertyIds(jobVisibleColumns);
		
		assignedJobTable.setContainerDataSource(jobContainer);
		assignedJobTable.setVisibleColumns(jobVisibleColumns.toArray());
	}
	
	public Collection<String> getSpecifiedGroupPropertyIds()
	{
		Vector<String> list = new Vector<String>(groupSpecifications.size());
		
		for (ColumnSpecification groupColumnSpecification : groupSpecifications)
		{
			if (groupColumnSpecification.getColumnGenerator() != null) continue;
			list.add(groupColumnSpecification.getPropertyId());
		}
		
		return list;
	}

	public Collection<String> getVisibleGroupPropertyIds()
	{
		Vector<String> list = new Vector<String>(groupSpecifications.size());
		
		for (ColumnSpecification groupColumnSpecification : groupSpecifications)
		{
			list.add(groupColumnSpecification.getPropertyId());
		}
		
		return list;
	}
	
	private void bindAvailableGroups(CoOp currentCoOp) 
	{	
		groupContainer = 
			new DataItemContainer<Group>(
					Group.class, 
					coopGroups,
					this.getContext().getSession().getStudentsManager(),
					getSpecifiedGroupPropertyIds()
			);
		
		this.groupAvailableTable.setContainerDataSource(groupContainer);
		
		this.groupAvailableTable.setVisibleColumns(getVisibleGroupPropertyIds().toArray());
	}

	private void bindJobPostings(CoOp currentCoOp) 
	{
		jobPostingContainer = 
			new DataItemContainer<JobPosting>(
					JobPosting.class, 
					jobPostingsWithRemainingSeats, 
					this.getContext().getSession().getJobPostingsManager()
			);
		
		//ids to be loaded
		jobPostingContainer.addNullableNestedContainerProperty("company.name");
		
		jobPostingContainer.setContainerPropertyIds(jobPostingVisibleColumns);
		
		this.jobPostingTable.setContainerDataSource(jobPostingContainer);
		
		this.jobPostingTable.setVisibleColumns(jobPostingVisibleColumns.toArray());
	}

	@Override
	public JobPosting getSelectedJobPosting() 
	{
		return (JobPosting) jobPostingTable.getValue();
	}

	@Override
	public Group getSelectedGroup() 
	{
		return (Group) groupAvailableTable.getValue();
	}

	@Override
	public Job getSelectedJob() 
	{
		return (Job) assignedJobTable.getValue();
	}
	
	@Override
	public void addJobAssignedListener(
			IViewListener<CoOp, ICoopContext, ITwinSelectTableComponentView> listener) 
	{
		this.addingJobEvent.add(listener);
		
	}

	@Override
	public void removeJobAssignedListener(
			IViewListener<CoOp, ICoopContext, ITwinSelectTableComponentView> listener) 
	{
		this.addingJobEvent.remove(listener);
	}

	@Override
	public void addJobAssignmentRemovedListener(
			IViewListener<CoOp, ICoopContext, ITwinSelectTableComponentView> listener) 
	{
		this.deletingJobEvent.add(listener);	
	}

	@Override
	public void removeJobAssignmentRemovedListener(
			IViewListener<CoOp, ICoopContext, ITwinSelectTableComponentView> listener) 
	{
		this.deletingJobEvent.remove(listener);
	}

	@Override
	protected void setupLocalizedCaptions(Locale locale) 
	{
		super.setupLocalizedCaptions(locale);
		
		setupLocalizedTableHeaders(jobPostingSpecifications, this.jobPostingTable, jobPostingContainer, jobPostingVisibleColumns);
		setupLocalizedTableHeaders(groupSpecifications, this.groupAvailableTable, groupContainer, groupVisibleColumns);
		setupLocalizedTableHeaders(jobSpecifications, this.assignedJobTable, jobContainer, jobVisibleColumns);
		
		this.assignJobButton.setCaption(getLocalizedString("ASSIGN_BUTTON_CAPTION"));
		this.removeAssignmentButton.setCaption(getLocalizedString("REMOVE_ASSIGNMENT_BUTTON_CAPTION"));
		
		this.jobPostingTable.setCaption(getLocalizedString("JOB_POSTING_TABLE_CAPTION"));
		if (this.getContext().getSelectedCoop().isGroupCoOp())
			this.groupAvailableTable.setCaption(getLocalizedString("GROUP_TABLE_GROUP_CAPTION"));
		else
			this.groupAvailableTable.setCaption(getLocalizedString("GROUP_TABLE_STUDENT_CAPTION"));
		
		this.assignedJobTable.setCaption(getLocalizedString("JOB_TABLE_CAPTION"));
		
		if (this.jobPostingLocationPickerField != null)
			this.jobPostingLocationPickerField.setCaption(getLocalizedString("FILTER_OPTIONS_LOCATION_CAPTION"));
		
		if (this.jobPostingCategoryPickerField != null)
			this.jobPostingCategoryPickerField.setCaption(getLocalizedString("FILTER_OPTIONS_CATEGORY_CAPTION"));
		
		if (this.onlyQualifiedForAssignmentCheckBox != null)
			this.onlyQualifiedForAssignmentCheckBox.setCaption(getLocalizedString("QUALIFIED_FOR_ASSIGNMENT_ONLY_CAPTION"));
	}

	@Override
	public void removeJobPostingFromContainer(JobPosting jobPosting) 
	{
		//this.jobPostingTable.removeItem(jobPosting);
		this.jobPostingContainer.removeItem(jobPosting);
	}

	@Override
	public void addJobPostingToContainer(JobPosting jobPosting) 
	{
		//this.jobPostingTable.addItem(jobPosting);
		this.jobPostingContainer.addItem(jobPosting);
	}

	@Override
	public void removeGroupFromContainer(Group group) 
	{
		//this.groupAvailableTable.removeItem(group);
		this.groupContainer.removeItem(group);
	}

	@Override
	public void addGroupToContainer(Group group) 
	{
		//this.groupAvailableTable.addItem(group);
		this.groupContainer.addItem(group);
	}

	@Override
	public void removeJobFromContainer(Job job) 
	{
		//this.assignedJobTable.removeItem(job);
		this.jobContainer.removeItem(job);
		this.removeAssignmentButton.setEnabled(false);
	}

	@Override
	public void addJobToContainer(Job job) 
	{
		if (job == null) 
			throw new IllegalArgumentException("Argument 'job' must not be null.");
		
		//jobContainer.addItem(job);
		jobContainer.addItemAt(0, job);
		
		this.assignJobButton.setEnabled(false);
		
		this.assignedJobTable.setValue(job);
		this.assignedJobTable.setCurrentPageFirstItemId(job);
	}
	
	/*
	 * Setup localized Table Header and rebind
	 */
	private void setupLocalizedTableHeaders(Collection<ColumnSpecification> columnSpecifications, Table table, Container container, Collection<String> visibleColumns)
	{
		for (ColumnSpecification specification : columnSpecifications)
		{
			table.setColumnHeader(specification.getPropertyId(), getLocalizedString(specification.getCaptionResourceId()));
		}
		
		// Refresh the contents by re-binding.
		if (container != null)
		{
			table.setContainerDataSource(container);
			table.setVisibleColumns(visibleColumns.toArray());
		}
	}

	@Override
	public void refreshJobPostingsTable() 
	{
		this.jobPostingTable.refreshRowCache();
		
	}

	@Override
	public Date getJobStartDate() 
	{
		return (Date) startDatePopupDateField.getValue();
	}

	@Override
	public BeanItem<FilterOptions> getJobPostingsFilterOptions() 
	{
		return this.jobPostingFilterOptionsItem;
	}

	@Override
	public BeanItem<FilterOptions> getGroupFilterOptions() 
	{
		return this.groupFilterOptionsItem;
	}

	@Override
	public List<JobPosting> getJobPostings() 
	{
		return this.jobPostingsWithRemainingSeats;
	}

	@Override
	public void setJobPostings(List<JobPosting> container) 
	{
		this.jobPostingsWithRemainingSeats = container;
		
		bindJobPostings(getContext().getSelectedCoop());
	}

	@Override
	public List<Group> getGroups() 
	{
		return this.coopGroups;
	}

	@Override
	public void setGroups(List<Group> container) 
	{
		this.coopGroups = container;
		
		bindAvailableGroups(getContext().getSelectedCoop());
	}

	@Override
	public List<Job> getJobs() 
	{
		return this.setOfAssignedJobs;
	}

	@Override
	public void setJobs(List<Job> container) 
	{
		this.setOfAssignedJobs = container;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout()
	{
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// tableHorizontalLayout
		tableHorizontalLayout = buildTableHorizontalLayout();
		mainLayout.addComponent(tableHorizontalLayout);
		
		// detaillHorizontalLayout
		detaillHorizontalLayout = buildDetaillHorizontalLayout();
		mainLayout.addComponent(detaillHorizontalLayout);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildTableHorizontalLayout()
	{
		// common part: create layout
		tableHorizontalLayout = new HorizontalLayout();
		tableHorizontalLayout.setImmediate(false);
		tableHorizontalLayout.setWidth("100.0%");
		tableHorizontalLayout.setHeight("-1px");
		tableHorizontalLayout.setMargin(false);
		tableHorizontalLayout.setSpacing(true);
		
		// jobPostingsVerticalLayout
		jobPostingsVerticalLayout = buildJobPostingsVerticalLayout();
		tableHorizontalLayout.addComponent(jobPostingsVerticalLayout);
		tableHorizontalLayout.setExpandRatio(jobPostingsVerticalLayout, 0.33f);
		
		// groupAvailableVerticalLayout
		groupAvailableVerticalLayout = buildGroupAvailableVerticalLayout();
		tableHorizontalLayout.addComponent(groupAvailableVerticalLayout);
		tableHorizontalLayout.setExpandRatio(groupAvailableVerticalLayout, 0.33f);
		
		// buttonsVerticalLayout
		buttonsVerticalLayout = buildButtonsVerticalLayout();
		tableHorizontalLayout.addComponent(buttonsVerticalLayout);
		tableHorizontalLayout.setExpandRatio(buttonsVerticalLayout, 0.15f);
		tableHorizontalLayout.setComponentAlignment(buttonsVerticalLayout, new Alignment(48));
		
		// jobsTableVerticalLayout
		jobsTableVerticalLayout = buildJobsTableVerticalLayout();
		tableHorizontalLayout.addComponent(jobsTableVerticalLayout);
		tableHorizontalLayout.setExpandRatio(jobsTableVerticalLayout, 0.19f);
		
		return tableHorizontalLayout;
	}

	@AutoGenerated
	private VerticalLayout buildJobPostingsVerticalLayout()
	{
		// common part: create layout
		jobPostingsVerticalLayout = new VerticalLayout();
		jobPostingsVerticalLayout.setImmediate(false);
		jobPostingsVerticalLayout.setWidth("100.0%");
		jobPostingsVerticalLayout.setHeight("-1px");
		jobPostingsVerticalLayout.setMargin(false);
		jobPostingsVerticalLayout.setSpacing(true);
		
		// jobPostingTable
		jobPostingTable = new SortableDynamicTable();
		jobPostingTable.setCaption("Θέσεις Εργασίας");
		jobPostingTable.setImmediate(false);
		jobPostingTable.setWidth("100.0%");
		jobPostingTable.setHeight("175px");
		jobPostingsVerticalLayout.addComponent(jobPostingTable);
		
		// jobPostingFilterOptionsForm
		jobPostingFilterOptionsForm = new FilterOptionsForm();
		jobPostingFilterOptionsForm.setCaption("Επιλογές Θέσεων Εργασίας");
		jobPostingFilterOptionsForm.setImmediate(false);
		jobPostingFilterOptionsForm.setWidth("100.0%");
		jobPostingFilterOptionsForm.setHeight("-1px");
		jobPostingsVerticalLayout.addComponent(jobPostingFilterOptionsForm);
		
		return jobPostingsVerticalLayout;
	}

	@AutoGenerated
	private VerticalLayout buildGroupAvailableVerticalLayout()
	{
		// common part: create layout
		groupAvailableVerticalLayout = new VerticalLayout();
		groupAvailableVerticalLayout.setImmediate(false);
		groupAvailableVerticalLayout.setWidth("100.0%");
		groupAvailableVerticalLayout.setHeight("-1px");
		groupAvailableVerticalLayout.setMargin(false);
		groupAvailableVerticalLayout.setSpacing(true);
		
		// groupAvailableTable
		groupAvailableTable = new SortableDynamicTable();
		groupAvailableTable.setCaption("Διαθέσιμοι Φοιτητές");
		groupAvailableTable.setImmediate(false);
		groupAvailableTable.setWidth("100.0%");
		groupAvailableTable.setHeight("175px");
		groupAvailableVerticalLayout.addComponent(groupAvailableTable);
		
		// groupFilterOptionsForm
		groupFilterOptionsForm = new FilterOptionsForm();
		groupFilterOptionsForm.setCaption("Επιλογές Ομάδων Εργασίας");
		groupFilterOptionsForm.setImmediate(false);
		groupFilterOptionsForm.setWidth("100.0%");
		groupFilterOptionsForm.setHeight("-1px");
		groupAvailableVerticalLayout.addComponent(groupFilterOptionsForm);
		
		return groupAvailableVerticalLayout;
	}

	@AutoGenerated
	private VerticalLayout buildButtonsVerticalLayout()
	{
		// common part: create layout
		buttonsVerticalLayout = new VerticalLayout();
		buttonsVerticalLayout.setImmediate(false);
		buttonsVerticalLayout.setWidth("100.0%");
		buttonsVerticalLayout.setHeight("-1px");
		buttonsVerticalLayout.setMargin(true);
		buttonsVerticalLayout.setSpacing(true);
		
		// assignJobButton
		assignJobButton = new Button();
		assignJobButton.setCaption("Ανάθεση");
		assignJobButton.setEnabled(false);
		assignJobButton.setImmediate(true);
		assignJobButton.setWidth("100.0%");
		assignJobButton.setHeight("-1px");
		buttonsVerticalLayout.addComponent(assignJobButton);
		
		// removeAssignmentButton
		removeAssignmentButton = new Button();
		removeAssignmentButton.setCaption("Κατάργηση");
		removeAssignmentButton.setEnabled(false);
		removeAssignmentButton.setImmediate(true);
		removeAssignmentButton.setWidth("100.0%");
		removeAssignmentButton.setHeight("-1px");
		buttonsVerticalLayout.addComponent(removeAssignmentButton);
		
		// startDatePopupDateField
		startDatePopupDateField = new PopupDateField();
		startDatePopupDateField.setImmediate(false);
		startDatePopupDateField.setWidth("100.0%");
		startDatePopupDateField.setHeight("-1px");
		startDatePopupDateField.setInvalidAllowed(false);
		buttonsVerticalLayout.addComponent(startDatePopupDateField);
		buttonsVerticalLayout.setComponentAlignment(startDatePopupDateField, new Alignment(48));
		
		return buttonsVerticalLayout;
	}

	@AutoGenerated
	private VerticalLayout buildJobsTableVerticalLayout()
	{
		// common part: create layout
		jobsTableVerticalLayout = new VerticalLayout();
		jobsTableVerticalLayout.setImmediate(false);
		jobsTableVerticalLayout.setWidth("100.0%");
		jobsTableVerticalLayout.setHeight("-1px");
		jobsTableVerticalLayout.setMargin(false);
		jobsTableVerticalLayout.setSpacing(true);
		
		// assignedJobTable
		assignedJobTable = new SortableDynamicTable();
		assignedJobTable.setCaption("Ανατεθημένες Θέσεις");
		assignedJobTable.setImmediate(false);
		assignedJobTable.setWidth("100.0%");
		assignedJobTable.setHeight("170px");
		jobsTableVerticalLayout.addComponent(assignedJobTable);
		
		// fullJobViewCheckBox
		fullJobViewCheckBox = new CheckBox();
		fullJobViewCheckBox.setCaption("Πλήρης Εμφάνιση");
		fullJobViewCheckBox.setImmediate(false);
		fullJobViewCheckBox.setWidth("100.0%");
		fullJobViewCheckBox.setHeight("-1px");
		jobsTableVerticalLayout.addComponent(fullJobViewCheckBox);
		jobsTableVerticalLayout.setComponentAlignment(fullJobViewCheckBox, new Alignment(10));
		
		return jobsTableVerticalLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildDetaillHorizontalLayout()
	{
		// common part: create layout
		detaillHorizontalLayout = new HorizontalLayout();
		detaillHorizontalLayout.setImmediate(false);
		detaillHorizontalLayout.setWidth("100.0%");
		detaillHorizontalLayout.setHeight("-1px");
		detaillHorizontalLayout.setMargin(false);
		detaillHorizontalLayout.setSpacing(true);
		
		// jobPostingDetailsComponent
		jobPostingDetailsComponent = new JobPostingComponent();
		jobPostingDetailsComponent.setImmediate(false);
		jobPostingDetailsComponent.setWidth("100.0%");
		jobPostingDetailsComponent.setHeight("-1px");
		detaillHorizontalLayout.addComponent(jobPostingDetailsComponent);
		detaillHorizontalLayout.setExpandRatio(jobPostingDetailsComponent, 0.33f);
		
		// groupDetailsComponent
		groupDetailsComponent = new GroupDetailsComponent();
		groupDetailsComponent.setImmediate(false);
		groupDetailsComponent.setWidth("100.0%");
		groupDetailsComponent.setHeight("-1px");
		detaillHorizontalLayout.addComponent(groupDetailsComponent);
		detaillHorizontalLayout.setExpandRatio(groupDetailsComponent, 0.33f);
		
		// jobDetailsComponent
		jobDetailsComponent = new JobDetailsComponent();
		jobDetailsComponent.setImmediate(false);
		jobDetailsComponent.setWidth("100.0%");
		jobDetailsComponent.setHeight("-1px");
		detaillHorizontalLayout.addComponent(jobDetailsComponent);
		detaillHorizontalLayout.setExpandRatio(jobDetailsComponent, 0.34f);
		
		return detaillHorizontalLayout;
	}
}
