package softeng.coop.ui.composites;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;

import softeng.coop.business.Session;
import softeng.coop.dataaccess.AuthenticatedUser;
import softeng.coop.dataaccess.CoOp;
import softeng.coop.dataaccess.Department;
import softeng.coop.dataaccess.Division;
import softeng.coop.dataaccess.FacultyUser;
import softeng.coop.dataaccess.Professor;
import softeng.coop.dataaccess.Registration;
import softeng.coop.dataaccess.Student;
import softeng.coop.dataaccess.University;
import softeng.coop.ui.ICoopContext;
import softeng.coop.ui.data.AccessCheck;
import softeng.coop.ui.data.DataItemContainer;
import softeng.coop.ui.data.DataUtilities;
import softeng.coop.ui.data.MultilingualValidationForm;
import softeng.coop.ui.data.SelectItem;
import softeng.coop.ui.presenters.UserManagementCardPresenter;
import softeng.coop.ui.viewdefinitions.IOkCancelView;
import softeng.coop.ui.viewdefinitions.IUserManagementCardView;
import softeng.coop.ui.viewdefinitions.viewmodels.OkCancelViewModel;
import softeng.coop.ui.viewdefinitions.viewmodels.UserType;
import softeng.ui.vaadin.mvp.IListener;
import softeng.ui.vaadin.mvp.IView;
import softeng.ui.vaadin.mvp.IViewListener;
import softeng.ui.vaadin.mvp.ModelEvent;
import softeng.ui.vaadin.mvp.Presenter;
import softeng.ui.vaadin.mvp.ViewEvent;
import softeng.ui.vaadin.mvp.ViewEventSubscription;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.Property;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.util.BeanItem;
import com.vaadin.event.FieldEvents;
import com.vaadin.event.FieldEvents.TextChangeEvent;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Component;
import com.vaadin.ui.Field;
import com.vaadin.ui.FormFieldFactory;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.AbstractTextField.TextChangeEventMode;

public class UserManagementCardComponent 
	extends CoopComponent<BeanItem<Department>> 
	implements IUserManagementCardView
{

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private OkCancelComponent okCancelComponent;

	@AutoGenerated
	private HorizontalLayout cardHorizontalLayout;

	@AutoGenerated
	private VerticalLayout coopVerticalLayout;

	@AutoGenerated
	private AdditionalStudentDataComponent additionalStudentDataComponent;

	@AutoGenerated
	private HorizontalLayout buttonsHorizontalLayout;

	@AutoGenerated
	private Button buttonRemoveSelectedRegistration;

	@AutoGenerated
	private Button buttonRegisterCurrentCoop;

	@AutoGenerated
	private ListSelect coOpListSelect;

	@AutoGenerated
	private VerticalLayout personDataVerticalLayout;

	@AutoGenerated
	private UserRoleTableComponent userRoleTableComponent;

	@AutoGenerated
	private PersonDataComponent personDataComponent;

	@AutoGenerated
	private VerticalLayout selectVerticalLayout;

	@AutoGenerated
	private FilterOptionsForm filterOptionsForm;

	@AutoGenerated
	private UsersTableComponent userTableComponent;

	@AutoGenerated
	private OptionGroup userTypeOptionGroup;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = 1L;

	private static class FilterOptionsForm
		extends MultilingualValidationForm<FilterOptions>
	{
		private static final long serialVersionUID = 1L;

		public FilterOptionsForm()
		{
			super(FilterOptions.class);
		}
	}
	
	private BeanItem<FilterOptions> filterOptionsItem;
	
	private ArrayList<String> filterPropertyIds = 
		createFilterPropertyIds();
	
	private CheckBox noAmaCheckBox;
	private CheckBox noIbanCheckBox;
	private CheckBox notAssignedToJobCheckBox;
	private CheckBox inSelectedCoopCheckBox;
	private CheckBox withoutUsernameCheckBox;
	private TextField surnamePrefixTextField;
	private ComboBox academicYearComboBox;
	private ComboBox divisionComboBox;
	private ComboBox departmentComboBox;
	private ComboBox universityComboBox;
	private TextField creationYearTextField;
	private CheckBox allRequiredFieldsCompleteCheckBox;
	
	private AccessCheck accessCheck;
	
	private ViewEventSubscription<BeanItem<Department>, ICoopContext, IUserManagementCardView> selectedUserTypeChangeSubscription =
		new ViewEventSubscription<BeanItem<Department>, ICoopContext, IUserManagementCardView>();
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public UserManagementCardComponent() 
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);

	}

	private ArrayList<String> createFilterPropertyIds()
	{
		ArrayList<String> propertyIds = new ArrayList<String>();
		
		propertyIds.add("surnamePrefix");
		propertyIds.add("university");
		propertyIds.add("department");
		propertyIds.add("division");
		propertyIds.add("creationYear");
		propertyIds.add("allRequiredFieldsComplete");
		propertyIds.add("noIban");
		propertyIds.add("noAma");
		propertyIds.add("notAssignedToJob");
		propertyIds.add("inSelectedCoop");
		propertyIds.add("withoutUsername");
		propertyIds.add("academicYear");
		
		return propertyIds;
	}
	
	@Override
	protected Presenter<BeanItem<Department>, ICoopContext, ? extends IView<BeanItem<Department>, ICoopContext>> 
		supplyPresenter() 
	{
		return new UserManagementCardPresenter(this);
	}

	@Override
	public void dataBind() 
	{
		if (this.getModel() == null)
			return;
		
		if (this.userTypeOptionGroup.getContainerDataSource() == null || 
				this.userTypeOptionGroup.getContainerDataSource().size() == 0)
		{
			
			Session session = getContext().getSession();
			
			DataItemContainer<SelectItem<String>> container = 
				new DataItemContainer<SelectItem<String>>(SelectItem.class, session.getBaseManager());
	
			if (session.getStudentsManager() != null && session.getStudentsManager().isWriteable())
				container.addItem(new SelectItem<String>("Student", "STUDENT_CAPTION", this));
			
			if (session.getFacultyUsersManager() != null && session.getFacultyUsersManager().isWriteable())
			{
				container.addItem(new SelectItem<String>("Faculty", "FACULTY_CAPTION", this));
				container.addItem(new SelectItem<String>("Professor", "PROFESSOR_CAPTION", this));
			}		
			
			this.userTypeOptionGroup.setContainerDataSource(container);
		}
		
		this.userTableComponent.setParentModel(this.getModel().getBean());
	}

	@SuppressWarnings("serial")
	@Override
	protected void setupUI() 
	{	
		super.setupUI();
		
		Session session = getContext().getSession();
		
		accessCheck = new AccessCheck(session);
		
		AuthenticatedUser currentUser = session.getAuthenticatedUser();
		
		FilterOptions filterOptions = new FilterOptions();
		
		filterOptions.setUniversity(currentUser.getDepartment().getUniversity());
		
		if (!accessCheck.canBrowseDepartments()) filterOptions.setDepartment(currentUser.getDepartment());
		
		filterOptionsItem =
			new BeanItem<IUserManagementCardView.FilterOptions>(filterOptions);
		
		buttonRegisterCurrentCoop.setIcon(new ThemeResource("../images/actions/add.png"));
		buttonRemoveSelectedRegistration.setIcon(new ThemeResource("../images/actions/remove.png"));
		
		getOkCancelView().setModel(OkCancelViewModel.Save);
		
		this.userTypeOptionGroup.setImmediate(true);
		this.userTypeOptionGroup.setCaption(getLocalizedString("OPTION_GROUP_CAPTION"));
		
		this.userTableComponent.setImmediate(true);
		this.userTableComponent.setCaption(getLocalizedString("USER_TABLE_CAPTION"));
		this.userTableComponent.setEditVisible(false);
		this.userTableComponent.setDeleteVisible(true);
		this.userTableComponent.setHeight("330px");
		
		
		personDataComponent.setViewFullyWritable(true);
		
		userRoleTableComponent.setEditVisible(false);
		userRoleTableComponent.setCaption(getLocalizedString("USER_ROLE_TABLE_CAPTION"));
		userRoleTableComponent.setHeight("200px");
		userRoleTableComponent.setVisible(false);
		
		additionalStudentDataComponent.setViewFullyWritable(true);
		
		showFacultyView();
		
		coOpListSelect.setCaption(getLocalizedString("CHOOSE_COOP_TABLE_CAPTION"));
		coOpListSelect.setImmediate(true);
		coOpListSelect.setNullSelectionAllowed(false);
		
		buttonRemoveSelectedRegistration.setEnabled(false);
		
		userTypeOptionGroup.addListener(new Property.ValueChangeListener() 
		{
			
			@Override
			public void valueChange(ValueChangeEvent event) 
			{
				onUserTypeOptionGroupValueChanged();
			}
		});
		
		this.userTableComponent.addSelectedChangeListener(new IListener<ModelEvent<AuthenticatedUser>>() 
		{
			
			@Override
			public void onEvent(ModelEvent<AuthenticatedUser> event) 
			{
				onSelectedUserChanged(userTableComponent.getSelectedItem());	
			}
		});
		
		this.coOpListSelect.addListener(new Property.ValueChangeListener() 
		{
			
			@Override
			public void valueChange(ValueChangeEvent event) 
			{
				onCoOpListSelectValueChanged();
			}
		});
		
		
		filterOptionsForm.setFormFieldFactory(new FormFieldFactory() 
		{
			@Override
			public Field createField(Item item, Object propertyId, Component uiContext) 
			{
				if (propertyId.equals("noAma"))
				{
					noAmaCheckBox = new CheckBox();
					noAmaCheckBox.setCaption(getLocalizedString("NO_AMA_CAPTION"));
					noAmaCheckBox.setWidth("100%");
					
					return noAmaCheckBox;
				}
				else if (propertyId.equals("noIban"))
				{
					noIbanCheckBox = new CheckBox();
					noIbanCheckBox.setCaption(getLocalizedString("NO_IBAN_CAPTION"));
					noIbanCheckBox.setWidth("100%");
					
					return noIbanCheckBox;
				}
				else if (propertyId.equals("allRequiredFieldsComplete"))
				{
					allRequiredFieldsCompleteCheckBox = new CheckBox();
					allRequiredFieldsCompleteCheckBox.setCaption(getLocalizedString("ALL_REQUIRED_FIELDS_COMPLETE_CAPTION"));
					allRequiredFieldsCompleteCheckBox.setWidth("100%");
					
					allRequiredFieldsCompleteCheckBox.addListener(new Property.ValueChangeListener()
					{
						@Override
						public void valueChange(ValueChangeEvent event)
						{
							boolean areRequired = allRequiredFieldsCompleteCheckBox.booleanValue();
							
							if (noIbanCheckBox != null)
								noIbanCheckBox.setEnabled(!areRequired);
						}
					});
					
					return allRequiredFieldsCompleteCheckBox;
				}
				else if (propertyId.equals("notAssignedToJob"))
				{
					notAssignedToJobCheckBox = new CheckBox();
					notAssignedToJobCheckBox.setCaption(getLocalizedString("NOT_ASSIGNED_TO_JOBS_CAPTION"));
					notAssignedToJobCheckBox.setWidth("100%");
					
					return notAssignedToJobCheckBox;
				}
				else if (propertyId.equals("inSelectedCoop"))
				{
					inSelectedCoopCheckBox = new CheckBox();
					inSelectedCoopCheckBox.setCaption(getLocalizedString("IN_SELECTED_COOP_CAPTION"));
					inSelectedCoopCheckBox.setWidth("100%");
					
					return inSelectedCoopCheckBox;
				}
				else if (propertyId.equals("withoutUsername"))
				{
					withoutUsernameCheckBox = new CheckBox();
					withoutUsernameCheckBox.setCaption(getLocalizedString("WITHOUT_USERNAME_CAPTION"));
					withoutUsernameCheckBox.setWidth("100%");
					
					return withoutUsernameCheckBox;
				}
				else if (propertyId.equals("surnamePrefix"))
				{
					surnamePrefixTextField = new TextField();
					surnamePrefixTextField.setCaption(getLocalizedString("SURNAME_PREFIX_CAPTION"));
					surnamePrefixTextField.setWidth("100%");
					surnamePrefixTextField.setNullRepresentation("");
					surnamePrefixTextField.setNullSettingAllowed(true);
					
					surnamePrefixTextField.addListener(new FieldEvents.TextChangeListener()
					{
					@Override
						public void textChange(TextChangeEvent event)
						{
							String text = event.getText();
							surnamePrefixTextField.setValue(text.isEmpty() ? null : text);
						}
					});
					
					
					return surnamePrefixTextField;
				}
				else if (propertyId.equals("academicYear"))
				{
					academicYearComboBox = DataUtilities.createYearComboBox();
					
					academicYearComboBox.setWidth("100%");
					
					academicYearComboBox.setCaption(getLocalizedString("ACADEMIC_YEAR_CAPTION"));
					
					return academicYearComboBox;
				}
				else if (propertyId.equals("creationYear"))
				{
					creationYearTextField = new TextField();
					
					creationYearTextField.setWidth("100%");
					
					creationYearTextField.setNullRepresentation("");
					creationYearTextField.setNullSettingAllowed(true);
					
					creationYearTextField.setCaption(getLocalizedString("CREATION_YEAR_CAPTION"));
					creationYearTextField.setDescription(getLocalizedString("CREATION_YEAR_DESCRIPTION"));
					
					creationYearTextField.setTextChangeEventMode(TextChangeEventMode.LAZY);
					creationYearTextField.setTextChangeTimeout(700);
					
					creationYearTextField.addListener(new FieldEvents.TextChangeListener()
					{
						@Override
						public void textChange(TextChangeEvent event)
						{
							creationYearTextField.setValue(event.getText());
						}
					});
					
					return creationYearTextField;
				}
				else if (propertyId.equals("division") && accessCheck.canBrowseDivisions())
				{
					divisionComboBox = new ComboBox();
					
					divisionComboBox.setCaption(getLocalizedString("DIVISION_CAPTION"));
					
					divisionComboBox.setWidth("100%");
					
					divisionComboBox.setNullSelectionAllowed(true);
					divisionComboBox.setTextInputAllowed(false);
					
					divisionComboBox.setItemCaptionMode(ComboBox.ITEM_CAPTION_MODE_PROPERTY);
					
					divisionComboBox.setItemCaptionPropertyId("name");
					
					divisionComboBox.setContainerDataSource(
							accessCheck.getDivisionsContainer(filterOptionsItem.getBean().getDepartment()));
					
					divisionComboBox.setEnabled(divisionComboBox.getContainerDataSource().size() > 0);

					return divisionComboBox;
				}
				else if (propertyId.equals("department") && accessCheck.canBrowseDepartments())
				{
					departmentComboBox = new ComboBox();
					
					departmentComboBox.setCaption(getLocalizedString("DEPARTMENT_CAPTION"));
					
					departmentComboBox.setWidth("100%");
					
					departmentComboBox.setNullSelectionAllowed(true);
					departmentComboBox.setTextInputAllowed(false);
					
					departmentComboBox.setItemCaptionMode(ComboBox.ITEM_CAPTION_MODE_PROPERTY);
					
					departmentComboBox.setItemCaptionPropertyId("name");
					
					departmentComboBox.setContainerDataSource(
							accessCheck.getDepartmentsContainer(filterOptionsItem.getBean().getUniversity()));
					
					departmentComboBox.setEnabled(departmentComboBox.getContainerDataSource().size() > 1);
					
					departmentComboBox.addListener(new Property.ValueChangeListener()
					{
						
						@Override
						public void valueChange(ValueChangeEvent event)
						{
							if (divisionComboBox != null)
							{
								Department department = filterOptionsItem.getBean().getDepartment();
								
								DataItemContainer<Division> divisionsContainer = accessCheck.getDivisionsContainer(department);
								
								divisionComboBox.setContainerDataSource(divisionsContainer);
								
								divisionComboBox.setEnabled(divisionsContainer.size() > 1);
							}
						}
					});
					
					return departmentComboBox;
				}
				else if (propertyId.equals("university") && accessCheck.canBrowseUniversities())
				{
					universityComboBox = new ComboBox();
					
					universityComboBox.setCaption(getLocalizedString("UNIVERSITY_CAPTION"));
					
					universityComboBox.setWidth("100%");
					
					universityComboBox.setNullSelectionAllowed(true);
					universityComboBox.setTextInputAllowed(false);
					
					universityComboBox.setItemCaptionMode(ComboBox.ITEM_CAPTION_MODE_PROPERTY);
					
					universityComboBox.setItemCaptionPropertyId("name");
					
					universityComboBox.setContainerDataSource(accessCheck.getUniversitiesContainer());
					
					universityComboBox.setEnabled(universityComboBox.getContainerDataSource().size() > 1);
					
					universityComboBox.addListener(new Property.ValueChangeListener()
					{
						@Override
						public void valueChange(ValueChangeEvent event)
						{
							if (departmentComboBox != null)
							{
								University university = filterOptionsItem.getBean().getUniversity();
								
								DataItemContainer<Department> departmentsContainer = accessCheck.getDepartmentsContainer(university);
								
								departmentComboBox.setContainerDataSource(departmentsContainer);
								
								departmentComboBox.setEnabled(departmentsContainer.size() > 1);
							}
							
							if (divisionComboBox != null)
							{
								divisionComboBox.setContainerDataSource(accessCheck.getDivisionsContainer((Department)null));
								
								divisionComboBox.setEnabled(false);
							}
						}
					});
					
					return universityComboBox;
				}
				
				return null;
			}
		});
		
		VerticalLayout filterOptionsLayout = new VerticalLayout();
		filterOptionsLayout.setSpacing(true);
		
		filterOptionsForm.setLayout(filterOptionsLayout);
		filterOptionsForm.setImmediate(true);
		filterOptionsForm.setItemDataSource(filterOptionsItem, filterPropertyIds);
		this.filterOptionsForm.setCaption(getLocalizedString("OPTIONS_CAPTION"));
		this.filterOptionsForm.setVisible(false);
		
	}

	private void onSelectedUserChanged(BeanItem<? extends AuthenticatedUser> user)
	{
		if (user != null)
		{
			if (user.getBean() instanceof Student)
			{
				showRegistrationsTable(true);
				
				personDataComponent.setModel(user);
				personDataComponent.dataBind();
				
				@SuppressWarnings("unchecked")
				BeanItem<Student> userStudent =(BeanItem<Student>)user;
				
				additionalStudentDataComponent.setModel(userStudent);
				additionalStudentDataComponent.dataBind();
				
				//find user active registrations and add them to the coOpListSelect
				Student studentBean = (Student) user.getBean();
				Set<Registration> studentRegistrations = studentBean.getRegistrations();
				
				Collection<CoOp> studentCoops = new HashSet<CoOp>();
				
				if (studentRegistrations != null)
				{
					for (Registration registration : studentRegistrations)
						studentCoops.add(registration.getCoop());
					
					DataItemContainer<Registration> extendendedContainer = 
						new DataItemContainer<Registration>(Registration.class, 
							studentRegistrations, 
							this.getContext().getSession().getCoOpsManager()
						);
					
					extendendedContainer.addNestedContainerProperty("coop.name");
					
					coOpListSelect.setContainerDataSource(extendendedContainer);
					
					coOpListSelect.setItemCaptionPropertyId("coop.name");
					
					//disable add current coop button if user is already registered
					if (studentCoops.contains(this.getContext().getSelectedCoop()))
						this.buttonRegisterCurrentCoop.setEnabled(false);
					else
						this.buttonRegisterCurrentCoop.setEnabled(true);
				} 
				else
				{
					coOpListSelect.setContainerDataSource(new DataItemContainer<Registration>(
							Registration.class, 
							this.getContext().getSession().getStudentsManager())
					);
				}
				
			}
			else if (user.getBean() instanceof Professor)
			{
				personDataComponent.setModel(user);
				personDataComponent.dataBind();
				
				additionalStudentDataComponent.setModel(null);
				additionalStudentDataComponent.dataBind();
				
				userRoleTableComponent.setVisible(true);
				
				if (user.getBean().getRoles() != null)
					userRoleTableComponent.setModel(user.getBean().getRoles());
				userRoleTableComponent.setParentModel(user.getBean());
				userRoleTableComponent.dataBind();
			}
			else if (user.getBean() instanceof FacultyUser)
			{
				personDataComponent.setModel(user);
				personDataComponent.dataBind();
				
				additionalStudentDataComponent.setModel(null);
				additionalStudentDataComponent.dataBind();
				
				userRoleTableComponent.setVisible(true);
				
				if (user.getBean().getRoles() != null)
					userRoleTableComponent.setModel(user.getBean().getRoles());	
				userRoleTableComponent.setParentModel(user.getBean());
				userRoleTableComponent.dataBind();
			}
		}
		else
		{
			showRegistrationsTable(false);
			
			personDataComponent.setModel(null);
			personDataComponent.dataBind();
			
			additionalStudentDataComponent.setModel(null);
			additionalStudentDataComponent.dataBind();
			
			userRoleTableComponent.setParentModel(null);
			userRoleTableComponent.setModel(null);
			userRoleTableComponent.dataBind();
			userRoleTableComponent.setVisible(false);
			
			coOpListSelect.setContainerDataSource(null);
		}
	}
	
	@Override
	protected void setupLocalizedCaptions(Locale locale) 
	{
		super.setupLocalizedCaptions(locale); 
		
		if (buttonRegisterCurrentCoop != null)
			buttonRegisterCurrentCoop.setCaption(getLocalizedString("BUTTON_REGISTER_CAPTION"));

		if (buttonRemoveSelectedRegistration != null)
			buttonRemoveSelectedRegistration.setCaption(getLocalizedString("BUTTON_REMOVE_REGISTRATION_CAPTION"));
		
		if (coOpListSelect != null)
			coOpListSelect.setCaption(getLocalizedString("CHOOSE_COOP_TABLE_CAPTION"));
		
		if (userTypeOptionGroup != null)
			userTypeOptionGroup.setCaption(getLocalizedString("OPTION_GROUP_CAPTION"));
		
		if (userTableComponent != null)
			userTableComponent.setCaption(getLocalizedString("USER_TABLE_CAPTION"));
		
		if (userRoleTableComponent != null)
			userRoleTableComponent.setCaption(getLocalizedString("USER_ROLE_TABLE_CAPTION"));
		
		if (coOpListSelect != null)
			coOpListSelect.setCaption(getLocalizedString("CHOOSE_COOP_TABLE_CAPTION"));
		
		if (noAmaCheckBox != null)
			noAmaCheckBox.setCaption(getLocalizedString("NO_AMA_CAPTION"));
		
		if (noIbanCheckBox != null)
			noIbanCheckBox.setCaption(getLocalizedString("NO_IBAN_CAPTION"));
		
		if (allRequiredFieldsCompleteCheckBox != null)
			allRequiredFieldsCompleteCheckBox.setCaption(getLocalizedString("ALL_REQUIRED_FIELDS_COMPLETE_CAPTION"));
		
		if (notAssignedToJobCheckBox != null)
			notAssignedToJobCheckBox.setCaption(getLocalizedString("NOT_ASSIGNED_TO_JOBS_CAPTION"));
		
		if (inSelectedCoopCheckBox != null)
			inSelectedCoopCheckBox.setCaption(getLocalizedString("IN_SELECTED_COOP_CAPTION"));
		
		if (withoutUsernameCheckBox != null)
			withoutUsernameCheckBox.setCaption(getLocalizedString("WITHOUT_USERNAME_CAPTION"));
		
		if (surnamePrefixTextField != null)
			surnamePrefixTextField.setCaption(getLocalizedString("SURNAME_PREFIX_CAPTION"));
		
		if (academicYearComboBox != null)
			academicYearComboBox.setCaption(getLocalizedString("ACADEMIC_YEAR_CAPTION"));

		if (divisionComboBox != null)
		{
			divisionComboBox.setCaption(getLocalizedString("DIVISION_CAPTION"));
			
			DataUtilities.updateMultilingual(divisionComboBox);
		}
		
		if (creationYearTextField != null)
		{
			creationYearTextField.setCaption(getLocalizedString("CREATION_YEAR_CAPTION"));
			creationYearTextField.setDescription(getLocalizedString("CREATION_YEAR_DESCRIPTION"));
		}
		
		// Save selected user, because the updating of the combo box will cause a refresh to the table.
		AuthenticatedUser selectedUser = userTableComponent.getSelectedValue();
		
		if (departmentComboBox != null)
		{
			departmentComboBox.setCaption(getLocalizedString("DEPARTMENT_CAPTION"));
			
			DataUtilities.updateMultilingual(departmentComboBox);
		}
		
		if (universityComboBox != null)
		{
			universityComboBox.setCaption(getLocalizedString("UNIVERSITY_CAPTION"));
		
			DataUtilities.updateMultilingual(universityComboBox);
		}
		
		userTableComponent.setSelectedValue(selectedUser);
		
		if (filterOptionsForm != null)
			filterOptionsForm.setCaption(getLocalizedString("OPTIONS_CAPTION"));
		
	}
	
	private void showStudentSearchOptions()
	{
		filterOptionsForm.setVisible(true);
		
		if (noAmaCheckBox != null) noAmaCheckBox.setVisible(true);
		
		if (noIbanCheckBox != null) noIbanCheckBox.setVisible(true);
		
		if (notAssignedToJobCheckBox != null) notAssignedToJobCheckBox.setVisible(true);
		
		if (inSelectedCoopCheckBox != null) inSelectedCoopCheckBox.setVisible(true);
		
		if (academicYearComboBox != null) academicYearComboBox.setVisible(true);
		
		if (withoutUsernameCheckBox != null) withoutUsernameCheckBox.setVisible(true);
		
		if (divisionComboBox != null) divisionComboBox.setVisible(false);
		
		if (departmentComboBox != null) departmentComboBox.setVisible(false);
		
		if (universityComboBox != null) universityComboBox.setVisible(false);
		
		if (creationYearTextField != null) creationYearTextField.setVisible(true);
		
		if (allRequiredFieldsCompleteCheckBox != null) allRequiredFieldsCompleteCheckBox.setVisible(true); 
	}
	
	private void showFacultyUserSearchOptions()
	{
		filterOptionsForm.setVisible(true);
		
		if (noAmaCheckBox != null) noAmaCheckBox.setVisible(false);
		
		if (noIbanCheckBox != null) noIbanCheckBox.setVisible(false);
		
		if (notAssignedToJobCheckBox != null) notAssignedToJobCheckBox.setVisible(false);
		
		if (inSelectedCoopCheckBox != null) inSelectedCoopCheckBox.setVisible(false);
		
		if (academicYearComboBox != null) academicYearComboBox.setVisible(false);
		
		if (withoutUsernameCheckBox != null) withoutUsernameCheckBox.setVisible(false);
		
		if (divisionComboBox != null) divisionComboBox.setVisible(true);
		
		if (departmentComboBox != null) departmentComboBox.setVisible(true);
		
		if (universityComboBox != null) universityComboBox.setVisible(true);
		
		if (creationYearTextField != null) creationYearTextField.setVisible(false);

		if (allRequiredFieldsCompleteCheckBox != null) allRequiredFieldsCompleteCheckBox.setVisible(false); 
	}

	private void showStudentView()
	{
		this.personDataComponent.setVisible(true);
		//this.personDataVerticalLayout.setExpandRatio(personDataComponent, 0.3f);
		this.cardHorizontalLayout.setExpandRatio(personDataVerticalLayout, 0.4f);
		this.userRoleTableComponent.setVisible(false);
		
		showStudentSearchOptions();
		
		this.additionalStudentDataComponent.setVisible(true);
		//this.coopVerticalLayout.setExpandRatio(additionalStudentDataComponent, 0.4f);
		
		this.cardHorizontalLayout.setExpandRatio(coopVerticalLayout, 0.4f);

		this.showRegistrationsTable(false);
	}
	
	private void showFacultyView()
	{
		this.personDataComponent.setVisible(true);
		this.userRoleTableComponent.setVisible(false);
		this.cardHorizontalLayout.setExpandRatio(personDataVerticalLayout, 1f);
		
		showFacultyUserSearchOptions();
		
		this.additionalStudentDataComponent.setVisible(false);
		//this.coopVerticalLayout.setExpandRatio(additionalStudentDataComponent, 0f);
		
		this.cardHorizontalLayout.setExpandRatio(coopVerticalLayout, 0f);

		this.showRegistrationsTable(false);
	}
	
	private void showProfessorView()
	{
		this.personDataComponent.setVisible(true);
		this.userRoleTableComponent.setVisible(false);
		this.cardHorizontalLayout.setExpandRatio(personDataVerticalLayout, 1f);
		
		showFacultyUserSearchOptions();
		
		this.additionalStudentDataComponent.setVisible(false);
		//this.coopVerticalLayout.setExpandRatio(additionalStudentDataComponent, 0f);
		
		this.cardHorizontalLayout.setExpandRatio(coopVerticalLayout, 0f);

		this.showRegistrationsTable(false);
	}

	@Override
	public BeanItem<AuthenticatedUser> getSelectedUser() 
	{
		if (this.userTableComponent.getSelectedItem() != null)
			return this.userTableComponent.getSelectedItem();
		else
			return null;
	}

	private void onUserTypeOptionGroupValueChanged()
	{
		switch (getSelectedUserType())
		{
			case Student:
				showStudentView();
				break;
				
			case Professor:
				showProfessorView();
				break;
				
			case Faculty:
				showFacultyView();
				break;
		}
		
		selectedUserTypeChangeSubscription.fire(
				new ViewEvent<BeanItem<Department>, ICoopContext, IUserManagementCardView>(this));
		
	}

	private void onCoOpListSelectValueChanged() 
	{
		if (coOpListSelect.getValue() == null)
		{
			buttonRemoveSelectedRegistration.setEnabled(false);
			return;
		}
		else
		{
			buttonRemoveSelectedRegistration.setEnabled(true);
		}
		
		Registration selectedRegistration = (Registration) coOpListSelect.getValue();
		coOpListSelect.setDescription(coOpListSelect.getItemCaption(selectedRegistration));
	}

	@Override
	public IOkCancelView getOkCancelView() 
	{
		return this.okCancelComponent;
	}

	@Override
	public boolean isDataValid() 
	{
		return personDataComponent.isDataValid()&&additionalStudentDataComponent.isDataValid();
	}

	@Override
	public void discardChanges() 
	{
		userTableComponent.discard();
		
		personDataComponent.discardChanges();
		
		if (this.getSelectedUser().getBean() instanceof Student)
			additionalStudentDataComponent.discardChanges();
	}

	@Override
	public void commitChangesToModel() 
	{
		userTableComponent.commit();
		
		personDataComponent.commitChangesToModel();
		
		if (this.getSelectedUser().getBean() instanceof Student)
			additionalStudentDataComponent.commitChangesToModel();
		
	}


	@Override
	public BeanItem<FilterOptions> getFilterOptions() 
	{
		return this.filterOptionsItem;
	}

	@Override
	public UsersTableComponent getUserTable() 
	{
		return this.userTableComponent;
	}

	@Override
	public Button getButtonRegisterCurrentCoop() 
	{
		return this.buttonRegisterCurrentCoop;
	}

	@Override
	public Button getButtonRemoveSelectedRegistration() 
	{
		return this.buttonRemoveSelectedRegistration;
	}

	@Override
	public Registration getSelectedRegistration() 
	{
		return (Registration) this.coOpListSelect.getValue();
	}

	@Override
	public ListSelect getCoOpsRegistrationTable() 
	{
		return this.coOpListSelect;
	}

	@Override
	public UserType getSelectedUserType()
	{
		@SuppressWarnings("unchecked")
		SelectItem<String> userTypeItem = 
			(SelectItem<String>) userTypeOptionGroup.getValue();
		
		if (userTypeItem == null) return UserType.None;
		
		return Enum.valueOf(UserType.class, userTypeItem.getValue());
	}

	@Override
	public void addSelectedUserTypeChangeListener(IViewListener<BeanItem<Department>, ICoopContext, IUserManagementCardView> listener)
	{
		selectedUserTypeChangeSubscription.add(listener);
	}

	@Override
	public void removeSelectedUserTypeChangeListener(IViewListener<BeanItem<Department>, ICoopContext, IUserManagementCardView> listener)
	{
		selectedUserTypeChangeSubscription.remove(listener);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout()
	{
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// cardHorizontalLayout
		cardHorizontalLayout = buildCardHorizontalLayout();
		mainLayout.addComponent(cardHorizontalLayout);
		
		// okCancelComponent
		okCancelComponent = new OkCancelComponent();
		okCancelComponent.setImmediate(false);
		okCancelComponent.setWidth("-1px");
		okCancelComponent.setHeight("-1px");
		mainLayout.addComponent(okCancelComponent);
		mainLayout.setComponentAlignment(okCancelComponent, new Alignment(10));
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildCardHorizontalLayout()
	{
		// common part: create layout
		cardHorizontalLayout = new HorizontalLayout();
		cardHorizontalLayout.setImmediate(false);
		cardHorizontalLayout.setWidth("100.0%");
		cardHorizontalLayout.setHeight("-1px");
		cardHorizontalLayout.setMargin(false);
		cardHorizontalLayout.setSpacing(true);
		
		// selectVerticalLayout
		selectVerticalLayout = buildSelectVerticalLayout();
		cardHorizontalLayout.addComponent(selectVerticalLayout);
		cardHorizontalLayout.setExpandRatio(selectVerticalLayout, 0.2f);
		
		// personDataVerticalLayout
		personDataVerticalLayout = buildPersonDataVerticalLayout();
		cardHorizontalLayout.addComponent(personDataVerticalLayout);
		cardHorizontalLayout.setExpandRatio(personDataVerticalLayout, 0.4f);
		
		// coopVerticalLayout
		coopVerticalLayout = buildCoopVerticalLayout();
		cardHorizontalLayout.addComponent(coopVerticalLayout);
		cardHorizontalLayout.setExpandRatio(coopVerticalLayout, 0.4f);
		
		return cardHorizontalLayout;
	}

	@AutoGenerated
	private VerticalLayout buildSelectVerticalLayout()
	{
		// common part: create layout
		selectVerticalLayout = new VerticalLayout();
		selectVerticalLayout.setImmediate(false);
		selectVerticalLayout.setWidth("100.0%");
		selectVerticalLayout.setHeight("-1px");
		selectVerticalLayout.setMargin(false);
		selectVerticalLayout.setSpacing(true);
		
		// userTypeOptionGroup
		userTypeOptionGroup = new OptionGroup();
		userTypeOptionGroup.setCaption("Χρήστες ανά κατηγορία");
		userTypeOptionGroup.setImmediate(false);
		userTypeOptionGroup.setWidth("100.0%");
		userTypeOptionGroup.setHeight("-1px");
		selectVerticalLayout.addComponent(userTypeOptionGroup);
		
		// userTableComponent
		userTableComponent = new UsersTableComponent();
		userTableComponent.setImmediate(false);
		userTableComponent.setWidth("100.0%");
		userTableComponent.setHeight("-1px");
		selectVerticalLayout.addComponent(userTableComponent);
		
		// filterOptionsForm
		filterOptionsForm = new FilterOptionsForm();
		filterOptionsForm.setImmediate(false);
		filterOptionsForm.setWidth("100.0%");
		filterOptionsForm.setHeight("-1px");
		selectVerticalLayout.addComponent(filterOptionsForm);
		
		return selectVerticalLayout;
	}

	@AutoGenerated
	private VerticalLayout buildPersonDataVerticalLayout()
	{
		// common part: create layout
		personDataVerticalLayout = new VerticalLayout();
		personDataVerticalLayout.setImmediate(false);
		personDataVerticalLayout.setWidth("100.0%");
		personDataVerticalLayout.setHeight("-1px");
		personDataVerticalLayout.setMargin(false);
		personDataVerticalLayout.setSpacing(true);
		
		// personDataComponent
		personDataComponent = new PersonDataComponent();
		personDataComponent.setImmediate(false);
		personDataComponent.setWidth("100.0%");
		personDataComponent.setHeight("-1px");
		personDataVerticalLayout.addComponent(personDataComponent);
		
		// userRoleTableComponent
		userRoleTableComponent = new UserRoleTableComponent();
		userRoleTableComponent.setImmediate(false);
		userRoleTableComponent.setWidth("100.0%");
		userRoleTableComponent.setHeight("-1px");
		personDataVerticalLayout.addComponent(userRoleTableComponent);
		
		return personDataVerticalLayout;
	}

	@AutoGenerated
	private VerticalLayout buildCoopVerticalLayout()
	{
		// common part: create layout
		coopVerticalLayout = new VerticalLayout();
		coopVerticalLayout.setImmediate(false);
		coopVerticalLayout.setWidth("100.0%");
		coopVerticalLayout.setHeight("-1px");
		coopVerticalLayout.setMargin(false);
		coopVerticalLayout.setSpacing(true);
		
		// coOpListSelect
		coOpListSelect = new ListSelect();
		coOpListSelect.setCaption("Διαθέσιμες Πρακτικές Ασκήσεις");
		coOpListSelect.setImmediate(false);
		coOpListSelect.setWidth("100.0%");
		coOpListSelect.setHeight("-1px");
		coopVerticalLayout.addComponent(coOpListSelect);
		
		// buttonsHorizontalLayout
		buttonsHorizontalLayout = buildButtonsHorizontalLayout();
		coopVerticalLayout.addComponent(buttonsHorizontalLayout);
		coopVerticalLayout.setComponentAlignment(buttonsHorizontalLayout, new Alignment(10));
		
		// additionalStudentDataComponent
		additionalStudentDataComponent = new AdditionalStudentDataComponent();
		additionalStudentDataComponent.setImmediate(false);
		additionalStudentDataComponent.setWidth("100.0%");
		additionalStudentDataComponent.setHeight("-1px");
		coopVerticalLayout.addComponent(additionalStudentDataComponent);
		
		return coopVerticalLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildButtonsHorizontalLayout()
	{
		// common part: create layout
		buttonsHorizontalLayout = new HorizontalLayout();
		buttonsHorizontalLayout.setImmediate(false);
		buttonsHorizontalLayout.setWidth("-1px");
		buttonsHorizontalLayout.setHeight("-1px");
		buttonsHorizontalLayout.setMargin(false);
		buttonsHorizontalLayout.setSpacing(true);
		
		// buttonRegisterCurrentCoop
		buttonRegisterCurrentCoop = new Button();
		buttonRegisterCurrentCoop.setCaption("Προσθήκη");
		buttonRegisterCurrentCoop.setImmediate(true);
		buttonRegisterCurrentCoop.setWidth("120px");
		buttonRegisterCurrentCoop.setHeight("-1px");
		buttonsHorizontalLayout.addComponent(buttonRegisterCurrentCoop);
		
		// buttonRemoveSelectedRegistration
		buttonRemoveSelectedRegistration = new Button();
		buttonRemoveSelectedRegistration.setCaption("Διαγραφή");
		buttonRemoveSelectedRegistration.setImmediate(true);
		buttonRemoveSelectedRegistration.setWidth("120px");
		buttonRemoveSelectedRegistration.setHeight("-1px");
		buttonsHorizontalLayout.addComponent(buttonRemoveSelectedRegistration);
		
		return buttonsHorizontalLayout;
	}
	
	private void showRegistrationsTable(boolean show)
	{
		coOpListSelect.setVisible(show);
		buttonRegisterCurrentCoop.setVisible(show);
		buttonRemoveSelectedRegistration.setVisible(show);
	}
}
